# -*- coding: utf-8 -*-
"""A.C.C.E.S.S. scenarios, part 3 — CONTROL, TOOLS and COMMUNITY."""

SCENARIOS = [
{
 "section": "CONTROL",
 "hook": "THE ACCESSIBLE VIEWING PLATFORM",
 "archetype": "The Closed Room With A Ramp / When The Safe Space Has One Gatekeeper",
 "clinical": "Controlled Environment / Access Gatekeeping",
 "who": "The person with the wristband list, the radio, or the key to the lift. Sometimes staff, sometimes a volunteer, sometimes the guy who has simply been doing it for years and nobody checks. Decides who gets up there, who stays, and who is being difficult.",
 "scene": "The platform is genuinely the best thing about this festival for you — sightlines, space, somewhere to be that is not a crowd. It is also small, elevated, roped off, and run by one man who controls who comes up. He has started saving you a spot. He has started mentioning that he saved you a spot. On Saturday he asks, warmly, in front of the others up there, whether you are going to come find him later.",
 "tells": [
  "One person controls entry and there is no posted process or named supervisor",
  "Access is framed as a personal favor rather than an entitlement",
  "Your place is “saved” for you, repeatedly and audibly",
  "Other disabled attendees have been quietly excluded and nobody explained why",
  "The same person is there every shift, every year, and “just handles it”",
  "Raising anything would cost you the only place on site that works for you",
 ],
 "happening": "Any resource that is scarce, essential, and controlled by one unsupervised person becomes leverage regardless of the intentions of whoever holds it. Accessible platforms, accessible camping, the golf cart, the lift, the interpreter roster — these are exactly that shape, and they sit in a blind spot because they are framed as provisions rather than as power. The risk is not that such spaces are unsafe; they are often the best-run part of a festival. The risk is structural: when the cost of complaining is losing the one thing that makes the weekend possible, complaints do not get made, and the absence of complaints gets read as everything being fine.",
 "check": "A.C.C.E.S.S. — “E” CHECK: “If I had a problem with this person, who else could I go to — by name?” If there is no second name, the space has a gate, not a policy.",
 "darkTitle": "The Cost Of Complaining Is The Whole Weekend",
 "dark": "This is why these situations run for years. A person in this role who is exploiting it is protected by arithmetic that everybody can do: reporting him means losing platform access, possibly for the rest of the event, possibly at every event he works. So people wait, and compare notes afterwards, and discover it was all of them. The pattern repeats across every gatekept accommodation in every scene, and it ends the same way each time — not because one person was brave, but because several found each other. If you are reading this and recognizing it: you are not the first one, and the others are findable.",
 "move": "Find the second name on arrival — the accessibility coordinator, the duty manager, the number on the back of the wristband — before you need it, while asking is neutral. Introduce yourself to another regular on the platform. Two disabled people who know each other's names is already a network, and it is the thing gatekeeping depends on not existing.",
 "say": "Who's the accessibility lead on shift, and what's the best way to reach them? I like knowing before I need it.",
 "truth": "An accommodation that depends on one person's goodwill is not an accommodation. It is a favor, and favors can be withdrawn.",
},
{
 "section": "TOOLS",
 "hook": "YOUR ACCESS PLAN",
 "archetype": "The Fifteen Minutes That Make The Weekend Work",
 "clinical": "Preventive Planning / Access Infrastructure",
 "who": "This page is the boring one and it is the one that works. Everything here is done before you arrive, in a calm room, by a version of you who is not tired, not overloaded, and not being asked anything by anyone.",
 "scene": "It is the Tuesday before. You have fifteen minutes and a notes app. Everything that will go wrong on Saturday night is currently a thing you can fix in one sentence, and on Saturday night it will not be, because the whole point of Saturday night is that you will not have the capacity to invent a plan from nothing.",
 "tells": [
  "Terrain and distance: where you sleep, where the accessible toilets are, how far, what surface",
  "The two-person rota: who does what, and who is the backup for each",
  "Meds on your body, spare elsewhere, photo of the label and dose on your phone",
  "The quiet places, located on the map before you need one",
  "The accessibility coordinator's name and contact, obtained on arrival",
  "One off-site person who expects a check-in and will notice if it does not come",
 ],
 "happening": "Everything in this guide is easier to counter in advance than in the moment, because every mechanism in it works by targeting a depleted version of you. Pre-commitment is the general answer: decisions made Tuesday hold on Saturday in a way that Saturday's decisions do not. This is also the part where you get to stop treating your access needs as a negotiation. Written down as logistics — surfaces, distances, timings, names — they stop being a thing you justify to people and become a thing you operate. That shift in framing is doing as much work as any individual item on the list.",
 "check": "A.C.C.E.S.S. — “E” CHECK: “Can I answer, right now, how I physically leave from where I will be tonight?” If not, that is the fifteen minutes.",
 "darkTitle": "The Plan Is For The Version Of You Who Cannot Make One",
 "dark": "Here is the reason this page is not optional filler. Every mechanism in this guide — the helper who consolidates, the quiet place that is private, the ask at the bottom of an overload — works by arriving when your capacity is lowest. None of them work on Tuesday. That asymmetry is the whole game, and the plan is the only move that plays on your side of it, because it lets a rested version of you make the decisions and hands them to a depleted version who only has to follow. People skip this page because nothing has gone wrong yet. That is precisely when it costs fifteen minutes instead of a weekend.",
 "move": "Write the six lines above in a note titled with the festival's name. Share it with your two people before you travel. Photograph your meds. Get the coordinator's contact at the gate, not on Sunday.",
 "say": "Here's my access plan for the weekend — two minutes to read. Tell me if you can't cover the bit I've put you down for, that's completely fine, I'd just rather know now.",
 "truth": "The plan is not because you expect something to go wrong. The plan is so that a tired version of you does not have to invent one.",
},
{
 "section": "TOOLS",
 "hook": "SCRIPTS FOR WHEN WORDS ARE EXPENSIVE",
 "archetype": "Pre-Written Sentences for Low-Capacity Moments",
 "clinical": "Self-Advocacy Scripting / Cognitive Load Reduction",
 "who": "For anyone whose speech, processing, or patience goes first when things get hard — which by Sunday is most people, and for a lot of us is Thursday. Scripts are not weakness. They are the same reason pilots read checklists out loud.",
 "scene": "Somebody is standing too close, asking something that needs a real answer, and the part of your brain that builds sentences has gone. You know what you want. You cannot currently construct it. Every second of silence makes the next one harder, and the person in front of you is reading the silence as agreement.",
 "tells": [
  "You freeze or go flat when you most need to say no",
  "You say yes to end an interaction and regret it inside a minute",
  "Your speech gets harder exactly when the stakes get higher",
  "You need processing time and people fill it",
  "Written or typed communication is easier than spoken, and nobody offers it",
  "You have said “it's fine” about something that was not fine, this weekend",
 ],
 "happening": "Under load, generating a novel sentence is expensive and retrieving a memorized one is cheap. That difference is the entire technique. Pre-written lines survive shutdown, overload, pain, and the specific pressure of an audience, because they do not require you to compose anything — you are reading, not writing. They also remove the part that usually costs the most, which is deciding how much to explain. The scripts below explain nothing. That is deliberate: explanation invites negotiation, and negotiation is the thing you do not have the resources for right now.",
 "check": "A.C.C.E.S.S. — “C” CHECK: “Do I have a sentence ready, or am I going to have to build one?” Ready is the difference between a no and a yes you did not mean.",
 "darkTitle": "Silence Gets Read As Yes",
 "dark": "The part that does real damage is not the freeze itself — it is what other people do with it. A pause while you assemble a sentence gets read as consideration, then as agreement, and somebody who wants a yes will take it and move. Afterwards it is extremely hard to explain that you did not agree, you just could not answer in time, because from the outside those look identical and the other person will say honestly that you did not object. This is why non-speaking and intermittently-speaking people are disproportionately affected, and why the counter is not courage. It is having the sentence already built, so that answering costs nothing you do not currently have.",
 "move": "Put four of these in your phone's notes, pinned, in large text, so you can hold the screen up instead of speaking if that is where you are. Practise saying two of them out loud before you travel, so your mouth already knows the shape.",
 "say": "I need a minute before I answer. — I'm not deciding anything tonight. — No, and I'm not going to explain it. — I need you to step back, please. — Can you type it? I'm not processing speech right now.",
 "truth": "A sentence you prepared on Tuesday is still your sentence on Saturday. Borrowing from your own calm self is not cheating.",
},
{
 "section": "COMMUNITY",
 "hook": "FOUND YOUR PEOPLE VS BEING SOMEBODY'S PROJECT",
 "archetype": "Real Crip And ND Community, And How To Tell",
 "clinical": "Authentic Community vs Benevolent Tokenization",
 "who": "The good version is other disabled and neurodivergent people, and the non-disabled people who have been around them long enough to have stopped performing. The other version means well, sometimes intensely, and needs you to be receiving something.",
 "scene": "Two things happen the same weekend. A woman with a cane and a folding stool sees you doing the arithmetic about the distance to the second stage, and says without ceremony that the north path is flat and there is a bench two-thirds of the way, and then talks to you about the lineup for twenty minutes and never mentions either of your bodies again. And a man tells you three times that his camp is a safe space for you and asks whether you are comfortable and asks again and asks whether you are sure.",
 "tells": [
  "Real: gives you information and then moves on to the actual subject",
  "Real: assumes competence — asks before helping, accepts no without a second attempt",
  "Real: you are allowed to be annoying, wrong, or boring without losing standing",
  "Project: needs you to confirm they are doing well at including you",
  "Project: helps without asking, and is hurt when that lands badly",
  "Project: your presence in their camp gets mentioned to other people",
 ],
 "happening": "Real community is identifiable by one thing: whether you can decline without it costing you. In genuine crip and ND space, refusing help, leaving early, going non-verbal, or simply being unimpressive changes nothing about your standing — there is no ledger. Tokenizing warmth is transactional even when it is sincere, and the transaction is that your comfort confirms someone's self-image, which means your discomfort becomes a problem for them rather than for you. The scene has an enormous amount of the real thing in it. It also has people for whom your inclusion is a credential, and the two can sit in the same camp.",
 "check": "A.C.C.E.S.S. — “S” CHECK: “Can I say no here and have it change nothing?” If declining costs you standing, it was never community. It was an arrangement.",
 "darkTitle": "When Your Inclusion Is Somebody's Credential",
 "dark": "The uncomfortable version: a person whose self-image depends on being good to you has a stake in you staying in a position where they can be good to you. That rarely looks like malice. It looks like discouraging the other camp, being hurt when you make plans elsewhere, reminding people how welcome you are here. The consequence is the same as the deliberate version on the first page of this guide — your options narrow — and it is harder to name because everyone involved, including them, believes it is kindness. The test stays the same and stays cheap: decline something small and see whether the temperature changes.",
 "move": "Test cheaply and early: decline one small offer and watch what the relationship does. Then find the other disabled and neurodivergent people on site, because they are the network that makes everything else in this guide survivable — the platform regulars, the quiet-zone regulars, the ones with the good folding chair.",
 "say": "Thanks — I'm good, I've got a system. — Hey, are you here every year? What's the terrain like round the back stages?",
 "truth": "The people who are actually your people will let you be ordinary. That is the whole test, and it works in under a minute.",
},
]
