# -*- coding: utf-8 -*-
"""A.C.C.E.S.S. scenarios, part 2 — CONDITION and CONTROL."""

SCENARIOS = [
{
 "section": "CONDITION",
 "hook": "LET'S GET YOU SOMEWHERE QUIETER",
 "archetype": "The Overload Navigator / Sensory Load As A Steering Wheel",
 "clinical": "Environmental Coercion / Engineered Decision Fatigue",
 "who": "Notices — correctly — that you are struggling with the noise and light, and offers the relief. Sometimes that is kindness and the quiet place is the medical tent. Sometimes the quiet place is his tent, and the route there went past the loudest stage on site for longer than it needed to.",
 "scene": "Four hours in, the bass from the main stage is doing the thing where it stops being sound and becomes a physical pressure in your jaw. Your ability to hold a sentence together is going. He says he knows somewhere quiet. You would agree to almost anything right now to make it stop, and some part of you clocks that, and the part of you that would normally clock it properly is the part that is currently offline.",
 "tells": [
  "Waits until you are visibly overloaded before making the ask",
  "The quiet place is private rather than designated — his tent, not the chill dome",
  "Takes a route that extends the overload rather than shortening it",
  "Discourages the sensory tools that would fix it without him — loops, defenders, the quiet zone",
  "Frames leaving as an emergency requiring immediate agreement",
  "Is unbothered by asking you to make decisions in a state where deciding is hardest",
 ],
 "happening": "Decision-making degrades measurably under sensory load, and for autistic and sensory-sensitive people the degradation arrives sooner and steeper. A person who has noticed this has a reliable instrument: they do not need to argue you into anything, they only need to wait, and to ask at the bottom. Nothing about this is exotic — it is the same mechanism as the 3am ask, the twentieth-hour ask, the ask after the long walk. What is specific here is that the pressure is ambient and continuous, the venue supplies it for free, and steering you through it looks exactly like helping.",
 "check": "A.C.C.E.S.S. — “S” CHECK: “Am I agreeing to this, or agreeing to make it stop?” Those feel identical from the inside. Only one of them is a decision.",
 "darkTitle": "Relief Is Not Consent",
 "dark": "The cruelty of this one is that it uses your own coping strategy against you. Getting out of overload is the correct instinct — your body is right — and that correctness is what makes the offer so hard to refuse. Afterwards it is also what makes it hard to name: you went willingly, you wanted to go, you were relieved to go. All true. And none of it means you agreed to what happened once the noise stopped. Wanting the noise to end is not consent to whatever is on the other side of the noise. If the quiet place is private and the person offering it is the reason you are deciding badly, the answer is a designated quiet space with staff in it, every time.",
 "move": "Pre-commit while you are regulated: name the quiet places on the map Thursday, put loops or defenders somewhere you can reach one-handed, and agree a signal with one person that means walk me to the chill dome and stay. Pre-committing is the whole technique — you are deciding now for a version of you who will not be able to.",
 "say": "I'm at capacity, so I'm not deciding anything right now. I'm going to the quiet zone with Sam and I'll find you after.",
 "truth": "Decisions made to end sensory pain are not decisions. They are escapes. Know your exits before you need them, and make them ones that do not require agreeing to anything.",
},
{
 "section": "CONDITION",
 "hook": "YOU SEEMED FINE EARLIER",
 "archetype": "The Mask Auditor / Using Your Coping Against You",
 "clinical": "Masking Exploitation / Capacity Misattribution",
 "who": "Has seen you hold it together and now treats that as your baseline. Cites your good hours back at you when you set a limit in your bad ones. Sometimes genuinely confused. Sometimes using it.",
 "scene": "Friday you were sharp, funny, on it for six straight hours, because you were masking hard and it cost you everything you had. Sunday you cannot process a sentence with three clauses in it and you need to leave. He says you were fine on Friday. He says you managed then. He says, and this is the one that lands, that it feels like you only get tired when there is something you do not want to do.",
 "tells": [
  "Cites your best hour as proof of your real capacity",
  "Treats a variable condition as a chosen inconsistency",
  "Suggests your limits are convenient or strategic",
  "Is surprised by fatigue after long social effort, repeatedly, having been told",
  "Uses “but you did it before” as an argument rather than a question",
  "Never asks what it cost",
 ],
 "happening": "Masking and the crash that follows it are well documented, and so is the cost: sustained camouflaging is associated with exhaustion and worse mental health outcomes, and the better you are at it the less anyone believes the crash. Fluctuating and invisible conditions generate the same problem — a person who saw your good hour now has evidence, and evidence is what gets used on you. Most people doing this are not malicious; they are pattern-matching badly. But it produces exactly the conditions someone deliberate needs: your own limits become debatable, and each time you defend them you spend energy you did not have, until conceding is cheaper than arguing. That is the mechanism, whoever is running it.",
 "check": "A.C.C.E.S.S. — “C” CHECK: “Am I explaining my capacity, or defending it?” Explaining is information. Defending means somebody has made it a negotiation, and it was never theirs to negotiate.",
 "darkTitle": "Believed On Friday, Doubted On Sunday",
 "dark": "This is the groundwork for the thing that matters later. A person who has spent a weekend establishing that your limits are inconsistent has also established that your account of things is inconsistent — and if something happens, that is the frame already sitting in everyone's head. It is the same reason disabled people's reports get discounted in general: the credibility was undermined before the incident, usually by nothing more sinister than repetition. Notice who argues with your capacity. Not because arguing means they will hurt you, but because the ones who will need that groundwork laid, and they lay it in public, in advance, sounding reasonable.",
 "move": "Stop justifying. State the limit as a fact with no evidence attached, because evidence invites cross-examination. Then use your people: the ones who saw Friday's cost are the ones who can say so without you spending anything.",
 "say": "Friday cost me today. That's how this works for me. I'm heading back — not up for discussing it.",
 "truth": "A limit is not a claim that needs supporting. You do not owe anyone the receipts for your own body.",
},
{
 "section": "CONTROL",
 "hook": "NOBODY'S GOING TO BELIEVE THAT",
 "archetype": "The Discrediter / Pre-Loading Your Unreliability",
 "clinical": "Testimonial Injustice / Credibility Undermining",
 "who": "Has been telling a gentle, affectionate story about you all weekend — that you get confused, that you exaggerate, that you had a lot on board, that you are a bit much by Sunday. Says it fondly. Says it to everyone. Says it before anything has happened.",
 "scene": "You tell a camp mate what happened. You watch her face do a thing. Not disbelief exactly — something slower and worse, a recalculation. And you realize you have heard the groundwork for that face all weekend, in the affectionate way he kept saying you were away with it, in the way he checked with other people whether you had taken anything, in the three separate times he mentioned to somebody else that you get muddled.",
 "tells": [
  "Narrates your reliability to third parties when you are not there to hear it",
  "Frames your condition, meds, or substance use as a reason to discount you",
  "Is warm about it — concern is the delivery mechanism",
  "Establishes the frame before any incident, not after",
  "Positions himself as the calm one and you as the one who needs interpreting",
  "Speaks for you in conversations you are physically present for",
 ],
 "happening": "This is testimonial injustice — the documented pattern where a person's account is given less weight because of who they are rather than what they said — and disabled people, particularly those with cognitive, psychiatric, or communication disabilities, are among the most consistently affected. The barrier to reporting most often named by disabled survivors is the expectation of not being believed, and that expectation is usually correct and usually pre-installed. What makes the festival version sharp is speed: a weekend is long enough to seed a reputation in a group of strangers and short enough that nobody has a competing impression to weigh it against.",
 "check": "A.C.C.E.S.S. — “A” CHECK: “Is somebody explaining me to people, when I am standing right here?” Being interpreted to others is how being doubted gets built.",
 "darkTitle": "Why They Pick Us",
 "dark": "Say the ugly part plainly, because knowing it is protective: a person looking for someone to hurt and not be caught for is looking for a low-credibility target, and our whole culture pre-supplies that. Not because of anything about us — because of what people already assume. That is the actual reason victimization rates are higher, and it has nothing to do with vulnerability in the sense people mean when they say it. The counter is not becoming more credible, which is not available to you and is not your job. The counter is documentation, which does not care whether anyone finds you credible: a timestamped message to somebody not at this festival, sent at the time, saying who you are with and where. It is boring and it is the single most useful thing in this guide.",
 "move": "Build a record that exists outside this weekend and outside your own account. Text one off-site person a name and a location each time you go anywhere with someone new — short, dated, ordinary. If the discrediting is already running, go to a specific person with a specific factual sentence rather than to the group.",
 "say": "I'd rather speak for myself, thanks. — [to your off-site person] With Dane, north camp, 11:40pm. Tell me you got this.",
 "truth": "You cannot argue somebody into believing you. You can make a record that does not need them to.",
},
]
