# -*- coding: utf-8 -*-
"""A.C.C.E.S.S. scenarios, part 1 of 2 — CAPTURE and CONDITION."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "I'LL BE YOUR HANDS THIS WEEKEND",
 "archetype": "The Volunteer Carer / The Helper Who Becomes The Gate",
 "clinical": "Caregiver Grooming / Manufactured Dependency",
 "who": "Shows up early, helps beautifully, and keeps helping until helping is the only way anything gets done. Learns your routine faster than your friends did. Frames every act of assistance as devotion rather than logistics, so that by day three declining anything feels like rejecting a person instead of declining a task.",
 "scene": "He offered to push on the gravel stretch Thursday and he was genuinely good at it — read the terrain, asked before every curb, never grabbed the handles without saying so. By Friday he is carrying your meds because your bag was full. By Saturday he knows the schedule better than you do, and when you mention going to the silent disco with the two people from your camp, he says he doesn't mind, he'll come, it's easier, they don't know how to do the transfer properly.",
 "tells": [
  "Helps with one thing, then quietly becomes the route to all things",
  "Learns your routine and your medication times unusually fast",
  "Frames assistance as love or devotion rather than as a task anyone could do",
  "Discourages other people from helping — “they don't know how you like it”",
  "Is present for every interaction you have with anyone else",
  "Reacts to you making a plan without him as though it were a betrayal",
 ],
 "happening": "This is dependency grooming with an accessibility costume on. The mechanism is not the helping — the helping is often real and skilled. The mechanism is consolidation: the steady narrowing of who can assist you until one person controls movement, medication, and access to everyone else. Disabled people are victimized at substantially higher rates than non-disabled people, and the perpetrator is disproportionately someone occupying a care or assistance role, because that role supplies proximity, privacy, physical contact, and a ready-made explanation for all three. The tell is never a single act. It is the direction of travel: every week he is load-bearing for one more thing, and every week there is one fewer person who could take over.",
 "check": "A.C.C.E.S.S. — “S” CHECK: “If this person left right now, would my weekend still work — or would it stop?” If it would stop, that is not closeness. That is a single point of failure with feelings attached.",
 "darkTitle": "The Helper Nobody Questions",
 "dark": "The reason this role is chosen is that it is socially armored. A man pushing your chair reads as a good man to every single person who walks past, which means he can stand closer, stay longer, and be alone with you more than anyone else at this festival — in full view, with everyone approving. If you later say something was wrong, you are contradicting a thing a hundred people watched and admired. That is the actual asset, and it is why the same role attracts the same people at every event. None of this makes the good ones bad. It makes the question worth asking early, while the answer is still cheap: who else could do this, and do they have my number?",
 "move": "Keep at least two people who can do any given task, and use both in the first twenty-four hours so it is normal rather than a statement. Split the functions on purpose — the person who pushes is not the person who holds meds is not the person who knows the plan. If someone objects to redundancy, that objection is the finding.",
 "say": "I run a two-person system for everything — it's how I stay independent, not a comment on you. Can you take the morning and let Rae take the evening?",
 "truth": "Help you can only get from one person is not help. It is a bottleneck, and bottlenecks are where people who want control go to stand.",
},
{
 "section": "CAPTURE",
 "hook": "YOU'RE SO INSPIRING",
 "archetype": "The Admirer / Inspiration As An Opening Move",
 "clinical": "Objectification via Idealization / Inspiration Framing",
 "who": "Approaches with enormous warmth and a compliment about your existence rather than anything you did. Talks about your courage within ninety seconds of meeting you. Wants to tell you what seeing you here means to them, at length, and wants you to receive it.",
 "scene": "You are in the line for water. A woman you have never met takes your hand — takes it, does not ask — and tells you that seeing you out here has genuinely changed her whole weekend, that she was complaining about the walk and then she saw you, and she just had to say it. She is crying a little. Three people are watching. You have about four seconds to decide whether to be gracious about a thing you did not agree to.",
 "tells": [
  "Compliments your existence rather than anything you chose or made",
  "Touches you, your chair, or your service animal while saying it",
  "Uses words like brave, courage, inspiring about you getting through a normal day",
  "Wants a photograph, sometimes before asking your name",
  "Positions your presence as being about their emotional experience",
  "Reacts badly to a flat “thanks” — the gratitude is what was being purchased",
 ],
 "happening": "Inspiration framing converts a person into a symbol, and symbols do not get to have boundaries. Once you are a source of someone's uplift, declining anything reads as cruelty — you are refusing to be the good thing that happened to them today. It is usually not predatory. It is usually a person feeling something clumsily out loud. But it does exactly the same work as a deliberate opening move: it establishes touch without consent, creates an audience that expects grace from you, and installs a debt in a stranger's favor inside two minutes. People who are running something deliberate use it because it works, and because the follow-up — I just feel a connection with you — is already half-built.",
 "check": "A.C.C.E.S.S. — “A” CHECK: “Is this about something I did, or about what my existence is doing for them?” Warmth about your work is a compliment. Warmth about your existence is a job you did not apply for.",
 "darkTitle": "The Audience Is The Trap",
 "dark": "The spectators are not incidental — they are the pressure. A stranger who wanted a private moment would not do this in a queue. Doing it in front of people means any “please let go of my hand” has a cost, and both of you know it. This is the same architecture as the public grand gesture that makes a no expensive, and it is the reason the follow-up ask so often arrives about ninety seconds later, while the audience is still there and still approving. You are allowed to be the one who breaks the scene. The discomfort belongs to the person who started it.",
 "move": "Answer the content, not the frame, and keep your hands to yourself first: pull back, say something flat and unmemorable, redirect to a task. Flatness is the tool. A symbol cannot survive a boring answer.",
 "say": "Ah, thanks. I'm just here for the music, same as you. — Hey, could you pass me that?",
 "truth": "You did not come here to be somebody's feeling. Being ordinary in public is a thing you are allowed to insist on.",
},
{
 "section": "CAPTURE",
 "hook": "LET ME CARRY YOUR MEDS",
 "archetype": "The Keeper / Medication As A Leash",
 "clinical": "Medication Control / Coercive Access to Essentials",
 "who": "Reasonable, practical, and correct that your bag is full. Offers to hold the thing you cannot go twelve hours without. Sometimes a partner, sometimes a friend, sometimes the helper from page one who has already been given three other jobs.",
 "scene": "Your bag is genuinely overloaded and he is genuinely trying to help and the pouch with the afternoon dose genuinely does fit better in his pocket. Then it is 4pm and he is at the other stage and not answering, and you are doing the arithmetic about how bad this gets, and discovering that the answer to “how long can I wait” is now a question about somebody else's schedule.",
 "tells": [
  "Offers to hold medication, insulin, inhalers, or a charger you medically depend on",
  "Is slow to return them, with a good reason each time",
  "Suggests you don't need a dose right now, or that you seem fine",
  "Uses the meds as a reason you should come with him rather than bringing them to you",
  "Gets wounded at the suggestion you keep your own",
  "Is the only person who knows where they are",
 ],
 "happening": "Whoever controls access to something you cannot skip controls your movements, your timing, and eventually your willingness to argue. This is textbook coercive control and it is well documented in intimate-partner contexts involving disabled partners — withholding medication, mobility equipment, or assistive technology is one of the most common forms it takes, precisely because it is invisible to outsiders and easy to explain away as forgetfulness. At a festival it needs no cruelty to work. Ordinary flakiness produces the same dependency, and a person who wants leverage only has to notice how well it worked and do it again.",
 "check": "A.C.C.E.S.S. — “C” CHECK: “Am I holding everything I cannot skip — meds, dose, charger, spare?” If the answer routes through somebody else's pocket, that is a leash regardless of who is holding it.",
 "darkTitle": "The Dose You Have To Ask For",
 "dark": "The second half of this is the part people miss: once the asking starts, the asking itself becomes the leverage. You begin choosing your battles — not raising the thing that annoyed you, not saying you want to go to the other stage — because you have to ask this person for something at six o'clock and you do not want it to be awkward. Nobody threatened anything. Nobody had to. That quiet self-editing around a person who holds something essential is the clearest early sign of coercive control there is, and at a festival it can install itself in a single weekend. Carry your own. Carry a spare somewhere else. Tell one other person where the spare is.",
 "move": "Split your supply: primary on your body, spare in a second location with a second person, and a photograph of the label and dose on your phone. Never consolidate. If someone is already holding them, retrieve them in daylight, in company, cheerfully, with a logistics reason and no accusation.",
 "say": "I keep my own — pharmacy rules, and I've been burned before. Can I grab that back off you? I'll take the water bottle instead, that's the heavy bit.",
 "truth": "Anything you cannot skip lives on your body. That is not distrust. That is the same reason you keep your own passport.",
},
]
