# -*- coding: utf-8 -*-
"""B.U.I.L.D. scenarios."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "WE'RE NOT A COMPANY, WE'RE A FAMILY",
 "archetype": "The Crew That Pays In Belonging",
 "clinical": "Familial Framing / Labor Obligation Substitution",
 "who": "Warm, genuinely bonded, and absolutely running on unpaid hours. Recruits on love of the work. Uses family language exactly where a normal employer would use a contract, and only ever in the direction of asking.",
 "scene": "The build crew is the best group of people you have ever worked with and the first four days are the happiest you have been in a year. On day five you realize nobody has mentioned money since the first conversation, the sixteen-hour days have become the schedule rather than the exception, and when you ask about the rate the lead says, kindly, that this is not really that kind of thing, that everybody here is doing it for the same reason, and that the family looks after each other.",
 "tells": [
  "Family language appears exactly where terms should be",
  "No written agreement, and asking for one reads as a trust problem",
  "Hours expand without the deal changing",
  "Asking about money is treated as a character flaw rather than a question",
  "Looking after each other is invoked when asking, never when paying",
  "Everyone senior has a real job title in the outside world",
 ],
 "happening": "Familial framing is the most efficient way to extract labor, because it converts a commercial question into a loyalty question — and once that conversion has happened, asking about your rate makes you the person who does not love the thing, in front of people whose respect you now depend on. Build crews are especially exposed because the work is genuinely joyful, the bonds are genuinely real, and the culture genuinely is one of mutual aid. All of that is true and none of it is a contract. The test is directional: notice whether family gets invoked when something is being asked of you, or also when something is owed to you.",
 "check": "B.U.I.L.D. — “B” CHECK: “If I could not work another shift from tomorrow, what would I actually be owed — in writing?” If the answer is a feeling, you do not have a deal.",
 "darkTitle": "Family Is Load-Bearing In One Direction",
 "dark": "Watch what happens at the edges, because that is where the frame reveals itself. Somebody gets injured on a family crew and discovers there is no insurance, no sick pay, and no employer, because they were never an employee — they were family, and family has no legal standing. Somebody raises a concern about a senior member and discovers the family closes, because a family protects its own and you are the newest one. That is the same mechanism the cult chapter of this scene's literature describes, arriving in work boots. It does not mean the warmth is fake. It means warmth is not a substitute for terms, and the crews that have both are the ones worth staying with.",
 "move": "Get the deal in a message before the first shift — hours, what you get, what happens if you are injured, who pays for the ferry home. A text is a written agreement. Then keep working and enjoy the crew, which is genuinely one of the best things in this scene.",
 "say": "Love it here, in for the full build. Can you drop me a quick message with the hours and what the deal covers — mostly so I know where I stand if I get hurt.",
 "truth": "A real family will write it down without being wounded about it. Only the extractive version treats the question as an insult.",
},
{
 "section": "CONDITION",
 "hook": "THE NINETY-SIXTH HOUR",
 "archetype": "Fatigue As The Actual Hazard",
 "clinical": "Cumulative Fatigue / Impairment-Equivalent Performance",
 "who": "Nobody. This one is the schedule. Day nine of a build, fourth consecutive sixteen-hour day, everybody running on catering coffee and the fact that the gates open Thursday whatever happens.",
 "scene": "You have been awake for nineteen hours and you are about to make a cut you have made a thousand times. The thing is you have made it a thousand times, which is why you are doing it now instead of stopping, and which is also why your hands are doing it while your attention is somewhere else. Everyone around you is in the same state and nobody is going to be the one who says the crew should stand down, because the schedule is the schedule.",
 "tells": [
  "Consecutive long shifts with no rostered rest",
  "Experienced people making basic errors and laughing about it",
  "Microsleeps, dropped tools, losing the thread mid-sentence",
  "Safety-critical work scheduled at the end of shifts rather than the start",
  "Nobody empowered to stop the job without it being a confrontation",
  "The build is behind and that has quietly become everyone's justification",
 ],
 "happening": "Sustained sleep restriction degrades reaction time, judgment, and risk assessment measurably, and past roughly seventeen to nineteen hours awake the impairment is comparable to being over the legal driving limit — with the extra problem that self-assessment degrades alongside performance, so the more impaired you are the more confident you feel. Occupational injury data across construction and events points the same way: serious incidents cluster late in long stretches, among experienced workers, on routine tasks. The hazard is not the dangerous job you were nervous about. It is the easy one you have done a thousand times, at hour nineteen.",
 "check": "B.U.I.L.D. — “D” CHECK: “How long have I been awake, and is this task one I would let a drunk person do?” If you would not, the honest answer is that the site currently has one.",
 "darkTitle": "Competence Is Why It Gets You",
 "dark": "The cruel part is that skill is the risk factor here, not the protection. Novices are slow and frightened, which keeps their attention on the task. Experienced hands run the cut on autopilot, which is exactly the faculty fatigue takes first, and it is why the amputations and the falls in this industry belong overwhelmingly to people who had done that job for years. There is a second layer specific to build: the incident happens on a site with no medical yet, no public, thin signal, and everyone else also exhausted. The margin you are relying on is not there. Stopping is not weakness on a build crew — it is the only intervention with any evidence behind it.",
 "move": "Name it as a crew rather than as an individual, because the social cost is what keeps it running: agree a hard stop hour for safety-critical work, and agree that anyone can call fatigue on anyone without argument. Schedule the height work, the plant, and the blades for the start of a shift.",
 "say": "I'm nineteen hours in — I'm not cutting tonight, I'll do it first thing and it'll be better work. Anyone else past it should say now, nobody's keeping score.",
 "truth": "The most experienced person on site is the one most likely to be hurt at hour ninety-six. That is not an insult. It is the data.",
},
{
 "section": "CONDITION",
 "hook": "IT'S JUST YOU OUT THERE TONIGHT",
 "archetype": "The Half-Built Site / Isolation Before The Festival Exists",
 "clinical": "Environmental Isolation / Absent Safety Infrastructure",
 "who": "The site itself, during load-in. Dark, enormous, mostly empty, with the medical tent not up yet, security not started, no public, patchy signal, and people you have never met driving plant around in the dark.",
 "scene": "You are finishing a run of cable at the far end of a field at eleven at night. There is one work light. The nearest other human is about four hundred metres away and does not know exactly where you are. Your phone has one bar. Every single protection this festival will have by Friday — rangers, medical, welfare, crowds of witnesses — does not exist yet, and will not for six days.",
 "tells": [
  "Lone working at night with nobody holding your location",
  "Medical, welfare, and security not yet operational on site",
  "Plant moving in the dark without a banksman",
  "No radio, or a radio on a channel nobody is monitoring",
  "Accommodation shared with people who have not been vetted at all",
  "No headcount — nobody would notice by morning",
 ],
 "happening": "Everything else in this book assumes a populated festival: witnesses, a medical tent you can walk to, rangers, other people's phones. Build phase has none of that, and it is also when the workforce is smallest, least known to each other, and most exhausted. Two separate risks stack in that gap — the industrial one, where an ordinary injury becomes serious because nobody finds you for two hours, and the interpersonal one, where every pattern in this book operates without any of the infrastructure that usually constrains it. Crew accommodation in particular is often a field of strangers with no vetting and no lock, which is not a comment on crew, it is a description of the conditions.",
 "check": "B.U.I.L.D. — “I” CHECK: “Does one named person know where I am and when I am due back?” Not the crew. A person, with a time.",
 "darkTitle": "The Six Days Before Anyone Is Watching",
 "dark": "Say the plain version: the safest time to harm someone at a festival is before it is a festival. No public, no cameras, no rangers, no welfare tent, a small pool of people who all outrank you in tenure, and a culture that will close ranks around the build because the build is behind. The people this lands on hardest are new crew, and especially young or lone women and anyone who needed this gig — because raising anything means losing the accommodation you are currently sleeping in, on a site you cannot leave without a lift. That is the structural problem, and it is why the buddy rule is not fussiness. Two people, a stated return time, and one person off-site who expects to hear from you.",
 "move": "Buddy anything at height, with plant, with blades, or after dark — no exceptions, arranged as a crew norm rather than a personal request. Put a location and a return time to one named person every night. Know where the first-aider is, and where the vehicle keys live.",
 "say": "Buddy rule after dark, I'm not doing the far field on my own. — Back by half eleven, if I'm not, come find me, I'm at the north cable run.",
 "truth": "The festival's safety net goes up on Wednesday. You have been on site since the Thursday before. Build your own until then.",
},
{
 "section": "CONTROL",
 "hook": "SETTLE UP AFTER THE EVENT",
 "archetype": "The Deal That Shrinks At The End / Payment As Leverage",
 "clinical": "Wage Withholding / Retrospective Renegotiation",
 "who": "The production manager with a spreadsheet and a cash-flow problem. Pleasant all build. Becomes hard to find on the Monday, and when found, remembers the arrangement differently and has the advantage of being the one who writes it down.",
 "scene": "The agreement was a day rate and expenses. It is Monday, the site is half struck, and the number he says now is lower — because the days you did were partly travel, because the accommodation counts against it, because the original figure was always a best case. You have no contract. You have a fortnight of sixteen-hour days, a van you paid the diesel for, and no leverage at all, because the work is already done.",
 "tells": [
  "Terms agreed verbally and never confirmed in writing",
  "Payment scheduled entirely after the work is complete",
  "Deductions appearing at settle-up that were never mentioned",
  "Your accommodation or transport home is in their gift",
  "Other crew have had the same conversation and did not compare notes",
  "The implication that complaining costs you next season",
 ],
 "happening": "All the leverage in a build arrangement sits at the end, which is why unscrupulous production will schedule payment there and why the honest ones pay staged. Once your labor is spent it cannot be withdrawn, and the threat that does the real work is rarely stated: next year's booking. In a scene where work comes by reputation and relationship, being known as difficult about money is a genuine cost, and everybody doing this knows you have done that arithmetic. It is the same structure as the vendor non-payment page in M.A.R.K.E.T., with one addition — they may also control whether you have a bed tonight and a way home tomorrow.",
 "check": "B.U.I.L.D. — “L” CHECK: “Do I have the agreed terms in writing, and a dated log of hours I actually worked?” Memory loses to a spreadsheet, every time.",
 "darkTitle": "Next Year Is The Threat Nobody Says",
 "dark": "The unspoken sentence doing all the work is that there is always next season, and you want to be on it. That is what keeps crews quiet about underpayment for years at a time, and it is why the problem is almost never one bad payer — it is a whole circuit where everybody has been shorted and nobody compared figures, because comparing figures is exactly what the threat prevents. The single most effective move available is the one that costs nothing and feels the most awkward: ask two other crew what they were paid. Wage secrecy is the mechanism. Breaking it is the counter, and crews that talk openly about rates do not have this problem.",
 "move": "Get the terms in a message before shift one and stage the payment — something up front, something mid-build. Log hours daily in a dated note with photographs of the work. Keep your own route home so your exit is never in their gift. Afterwards: a dated written demand, politely, with the log attached, beats a phone call every time.",
 "say": "Before I start — can you confirm the rate, the days, and what's covered, just in a text? And I'd want a third up front. Standard for me, nothing personal.",
 "truth": "Your labor is only leverage before you spend it. Write the terms down while you still have some.",
},
{
 "section": "TOOLS",
 "hook": "THE BUILD CREW KIT",
 "archetype": "The Five Things That Make A Build Survivable",
 "clinical": "Preventive Infrastructure / Worker Protection Basics",
 "who": "For anyone taking a build gig, at any level, on any crew — including the good ones, because the good ones do all of this already and will respect you for it.",
 "scene": "You are packing. What goes in the bag now is what you will have at hour ninety-six on a dark field with no signal and a production office that has gone home. Everything on this page takes ten minutes to arrange before you travel and is impossible to arrange afterwards.",
 "tells": [
  "The deal in writing: rate, days, what's covered, injury, transport home",
  "A dated hours log you fill in daily, with photos of the work",
  "Your own PPE — boots, gloves, hi-vis, glasses, ear protection, head torch",
  "Your own route home that nobody else controls",
  "One off-site person with the site address who expects a daily check-in",
  "The name of the site first-aider and where the trauma kit actually is",
 ],
 "happening": "Every pattern in this guide is defeated by something arranged in advance rather than negotiated in the moment, and the moment is always the worst time — you are tired, you are isolated, the work is already done, and the other party holds the leverage. Bringing your own PPE is the clearest example: it removes the most common coercive sentence on any site, which is that there is not a spare and the job still needs doing. Owning your route home removes the second. These are not signs of distrust. Experienced crew arrive with all of it, and the crews worth working for notice and think better of you.",
 "check": "B.U.I.L.D. — “U” CHECK: “Can I refuse a task right now without losing my bed or my lift?” If not, fix that before you need to refuse anything.",
 "darkTitle": "The Kit Is What Makes No Possible",
 "dark": "Every item on that list exists to make one sentence survivable: no, I am not doing that. Your own boots mean nobody can tell you the job goes ahead in trainers. Your own transport means refusing does not strand you. The written deal means walking away does not cost you a fortnight's pay. The check-in means somebody notices. Refusal is not a matter of courage on a build site, it is a matter of what refusing costs — and everything on that list is there to lower the price until it is something you can actually afford to say.",
 "move": "Pack the kit, send the deal message, name your off-site person, and find the first-aider and the trauma kit in your first hour on site. Then do the work, which is some of the best work there is.",
 "say": "Got my own PPE and my own van, so I'm sorted. Who's the first-aider this build, and where's the trauma kit living?",
 "truth": "Every bit of that kit buys you the same thing: the ability to say no and still have a bed, a lift, and a wage.",
},
{
 "section": "COMMUNITY",
 "hook": "THE CREW THAT ACTUALLY HOLDS",
 "archetype": "Real Solidarity Versus A Family That Only Takes",
 "clinical": "Authentic Crew Culture vs Extractive Belonging",
 "who": "The real thing is unglamorous and specific: people who tell each other their rates, who cover a shift without a ledger, who stop the job when somebody is unfit, and who back the newest person over the most senior one when the newest person is right.",
 "scene": "Two crews. On the first, a lad two days in says he is not comfortable going up in that wind, and the lead says fine, get the ground kit, and nothing else is ever said about it. On the second, the same sentence produces a silence, and then a joke, and then somebody else goes up instead — and everybody learns what happens if you say it.",
 "tells": [
  "Real: refusing an unsafe task costs nothing, visibly, in public",
  "Real: people talk openly about rates and compare them",
  "Real: the newest person is listened to when they flag something",
  "Extractive: family gets invoked only when something is being asked",
  "Extractive: raising a concern about a senior member closes the group",
  "Extractive: everyone has been shorted and nobody has compared figures",
 ],
 "happening": "Build crews produce some of the most genuine solidarity in this scene — shared hardship, real skill, work that would be impossible alone — and that is exactly why the extractive version is so effective, because it is wearing the same clothes. The difference is not warmth, both have warmth. The difference is what the group does when somebody's interests conflict with the schedule: a real crew absorbs the cost, an extractive one transfers it to the person with the least standing. Watch one refusal and one complaint and you will know which one you are on, usually within the first week.",
 "check": "B.U.I.L.D. — “U” CHECK: “What happened the last time somebody here said no to a task?” That answer is the crew's actual culture, whatever the culture says about itself.",
 "darkTitle": "The Silence After The Refusal",
 "dark": "It is worth knowing how a crew goes bad, because it is rarely a decision. It is one refusal met with a silence, and then a joke, and everybody present filing that away. After that the unsafe tasks get done by whoever needs the gig most, which is always the youngest, newest, most precarious person there, and the crew genuinely believes it has no safety problem because nobody says no any more. If you are senior on a crew: the most protective thing available to you is to publicly accept the next refusal you get, immediately and without comment. Everyone watching learns what it costs, and the answer is nothing, and that is how a crew that holds gets built.",
 "move": "Talk about rates out loud. Accept refusals without comment, especially if you are senior. Buddy the newest person on their first night shift. Cover a shift for somebody without starting a ledger, and let that be the culture rather than the exception.",
 "say": "Fair enough, grab the ground kit. — What are you on for this one? I'm on two-forty, worth knowing if they're paying people differently.",
 "truth": "Watch what happens after one person says no. That is the whole crew, revealed in about four seconds.",
},
]
