# -*- coding: utf-8 -*-
"""F.L.O.W. scenarios, part 1 — CAPTURE and CONDITION."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "I'LL TEACH YOU THE REAL STUFF",
 "archetype": "The Mentor With A Waiting List / Skill Access As Currency",
 "clinical": "Mentorship Grooming / Skill Gatekeeping",
 "who": "Genuinely good, visibly senior, and the reason half this circle can do what they do. Teaches selectively. Makes it clear that being taught is a thing you are chosen for, and that the choosing is ongoing.",
 "scene": "He has been doing this for fifteen years and the thing he does with a staff is the reason you started. He offers to work with you properly — not in the jam, at his camp, after, when it's quiet and there's space. The first session is the best hour of instruction you have ever had. The second session he corrects your stance with his hands and holds the correction slightly longer than the correction needs.",
 "tells": [
  "Teaching happens privately and late rather than in open practice",
  "Access to instruction is framed as being chosen, and is reviewable",
  "Physical correction escalates in duration or location over sessions",
  "Discourages you from training with others — they'll teach you bad habits",
  "Mentions what he could do for your booking or your profile",
  "The lesson quality is real, which is what makes leaving expensive",
 ],
 "happening": "Skill is the currency in this scene and a person who controls access to it controls a great deal. The mechanism is the same as every other access trap in this book, but it has an unusual protection: the teaching is genuinely valuable, so the cost of walking away is real and everybody can see it. That asymmetry is what gets exploited. It is also why the correction-by-touch escalation works — in a discipline where hands-on adjustment is legitimate and constant, the line between instruction and testing is exactly where a person can operate while retaining deniability, and where you will second-guess yourself for weeks.",
 "check": "F.L.O.W. — “O” CHECK: “Would this lesson be identical if it happened at 2pm in the open jam?” If the answer is no, the privacy is doing something the teaching does not need.",
 "darkTitle": "The Adjustment That Tests You",
 "dark": "The escalation is deliberately gradual and it is designed to be unreportable. A hand on the hip is technique. The same hand, a beat longer, is a test — and if you do not react, the next one is longer. Every individual step is defensible and the whole staircase is not, which is precisely why it is built in steps. Dance, martial arts, aerial, and acro have all documented this shape, and it works the same way here. The counter is not deciding where the line is in the moment, when you are mid-correction and unsure. It is deciding beforehand that instruction happens where people can see it, and treating any pressure to move it somewhere quieter as the finding rather than as a scheduling preference.",
 "move": "Train in the open. Take instruction from at least two people so no single person is your route to progress. If a session has already moved somewhere private, bring someone — “my friend wants to watch” is unarguable and tells you a great deal by how it lands.",
 "say": "I learn better in the jam — more eyes, more feedback. Can we do it there? I'll bring Kai, they've been wanting to work on the same thing.",
 "truth": "A teacher worth having will teach you in daylight with people watching. The ones who need the room quiet are not protecting your focus.",
},
{
 "section": "CAPTURE",
 "hook": "TAKE IT, IT'S YOURS",
 "archetype": "The Gear Gifter / Props With A Ledger",
 "clinical": "Reciprocity Debt / Material Obligation",
 "who": "Generous, well-equipped, and quick to notice what you cannot afford. Hands you a set of pro-grade props, a rig, a costume, a fire kit. Does not want anything for it, says so repeatedly, and mentions its value twice.",
 "scene": "Your poi are entry-level and everyone knows it. He has a spare set of the ones you have been saving for — seven hundred dollars of them — and he wants you to have them, no, really, take them, he has three sets. Two weeks later there is an afterparty you do not want to go to and the sentence in your head, unprompted, is that he gave you the poi.",
 "tells": [
  "The gift is expensive enough to be uncomfortable and given fast",
  "Refusing is treated as an insult rather than a choice",
  "Its value gets mentioned more than once, casually",
  "Given in front of other people, so the generosity is witnessed",
  "Followed within weeks by an ask that is hard to decline",
  "Taking it back is floated, lightly, when you say no to something",
 ],
 "happening": "Reciprocity is the strongest lever in the book — a received gift creates a felt obligation that operates below deliberation, and it does not care whether you asked for the gift or wanted it. Gift economy culture supercharges it, because the frame says a gift is pure, which removes your permission to be suspicious of one. Expensive gear is a particularly efficient version: it is high value, it is useful daily, it visibly improves your practice, and every time you use it you renew the debt. Most gifts in this scene are exactly what they look like. The tell is not generosity. It is generosity that arrives before the relationship has any other content.",
 "check": "F.L.O.W. — “O” CHECK: “Would I be comfortable saying no to this person tomorrow?” If the gear makes that harder, the gear is doing something other than spinning.",
 "darkTitle": "The Ledger Nobody Admits Exists",
 "dark": "The damage is not the moment the ask arrives — it is the weeks before, when you quietly start being easier to be around. You stop raising the thing that bothered you. You go to the thing you did not want to go to. Nobody has threatened anything and there is nothing to report, and if you told a friend they would say he sounds nice. That self-editing in advance of a demand that has not been made is the whole mechanism, and it is the most reliably reported experience of people who later realized they had been managed. If you want to test it cheaply: decline something small this week and watch whether the temperature of the friendship changes.",
 "move": "Price the gift and settle it — pay something, trade something, or return it. If none of that is possible, say out loud and early what the gift does not buy, which converts an unspoken ledger into a stated one and removes its power.",
 "say": "These are amazing and I'm not comfortable with a gift this size — let me pay you half, or I'll take them as a loan for the season and get them back to you.",
 "truth": "A real gift survives you saying no to the giver a week later. Test it early, while the test is cheap.",
},
{
 "section": "CONDITION",
 "hook": "SAFETY THIRD",
 "archetype": "The Culture That Jokes About The Thing That Kills You",
 "clinical": "Normalized Risk / Social Override of Safety Protocol",
 "who": "Not a person — a room. The collective eye-roll when someone asks for a safety brief. The laugh when you check your fuel. The lightly impatient veteran waiting while you do a rig inspection everybody else skipped.",
 "scene": "You are about to burn. The safety is a guy you met an hour ago who is holding a duvetyne blanket like it is a beach towel, and when you ask whether he has done this before he says yeah, loads, and looks at his phone. The circle is waiting. Asking again in front of everyone would make you the difficult one. You have about four seconds to decide whether being the difficult one is worse than the other thing.",
 "tells": [
  "Safety checks treated as a personality flaw rather than procedure",
  "A designated safety who cannot describe what they would actually do",
  "Fuel handled near lit tools, or depot uncovered",
  "“Safety third” said in a context where it is not a joke",
  "Nobody has asked who is calling stop, or what stop sounds like",
  "The social cost of pausing is visibly higher than the cost of proceeding",
 ],
 "happening": "Normalized deviance is the documented process by which a group repeatedly gets away with skipping a step until the skipped step becomes the standard. Every fire and aerial community runs on it to some degree, because the consequence is rare and the friction is constant, and the people most exposed are the newest — who have the least standing to pause and the most to lose by being seen as green. The joke is doing real work here: it pre-frames anyone who insists on the check as humorless, which means the insisting costs something, which means fewer people insist. That is not culture, it is a mechanism, and it runs whether or not anybody in the circle intends it.",
 "check": "F.L.O.W. — “F” CHECK: “Have I personally checked my fuel, my depot, and my safety — by asking them what they would do?” Secondhand assurance is not a check.",
 "darkTitle": "The Four Seconds",
 "dark": "Burn injuries in this scene cluster around exactly this moment — not around difficult tricks, around skipped checks under social pressure with an audience waiting. The specific failure is almost always mundane: fuel too close, a depot uncovered, a safety who had never actually done it, nobody having agreed what the stop call was. And the reason it is mundane is the reason it is preventable. The four seconds of being the difficult one is the entire intervention. People who have been burned describe those four seconds with total clarity afterwards, every time — they remember deciding not to ask again. Ask again. The circle waits, and then forgets by morning, and you do not have a graft.",
 "move": "Run your own check out loud, every time, in the same words, so it becomes your known habit rather than a comment on this circle: fuel, depot, safety, stop call. Ask the safety one question they have to answer — what do you do if my wick catches my sleeve? Their answer is the check.",
 "say": "Quick one before I light — what's the stop call, and what do you do if it goes up my arm? Not being difficult, I just do this every time.",
 "truth": "The circle's patience is not a safety system. Being briefly annoying is cheaper than being briefly on fire.",
},
{
 "section": "CONDITION",
 "hook": "YOU'RE ON IN TWENTY, IT'S FINE",
 "archetype": "The Show Must Go On / Performing Through Injury",
 "clinical": "Injury Minimization / Occupational Pressure",
 "who": "The organizer with a running order, the troupe lead with a headcount, and — most often — you, doing the arithmetic about letting people down and arriving at the wrong answer.",
 "scene": "Your shoulder went on the last rehearsal and you can feel it in a way that is new. You are on in twenty. There is no understudy because there is never an understudy. The set is four minutes. Four minutes is nothing. You have already decided you are doing it, and you are now assembling reasons, which is a different mental activity from deciding and it is worth noticing that you are doing it.",
 "tells": [
  "No cover, no contingency, and that is treated as normal",
  "Your injury is reframed as a scheduling problem",
  "“It's only four minutes” applied to a load-bearing body part",
  "Someone else's disappointment is the thing being weighed, not the joint",
  "You are assembling reasons rather than reaching a decision",
  "Pulling out has a reputational price everyone can name",
 ],
 "happening": "Performing-arts and circus injury research keeps finding the same thing: the significant injuries are disproportionately not freak accidents but re-injuries and compensations, sustained by people who continued while compromised. The economics drive it — no cover, no sick pay, gigs awarded by reputation, and a culture that reads reliability as showing up regardless. In a festival context it is sharper still, because the gig is often unpaid or trade, so you are risking a shoulder for a wristband and the thing keeping you in the air is not money but not wanting to be the person who dropped out.",
 "check": "F.L.O.W. — “O” CHECK: “Am I deciding, or justifying?” If you are listing reasons, the decision already happened and it was not made by your judgment.",
 "darkTitle": "What Four Minutes Costs",
 "dark": "The ugly arithmetic is that four minutes of a compromised shoulder, rotator cuff, or ankle can end a practice you spent a decade building, and the people asking you to do it will have forgotten by the next event. Aerialists lose careers to exactly this. The second half is worse: performing impaired — injured, exhausted, or altered — also puts your base, your spotter, and anybody underneath you at risk, so the loyalty argument that got you into the air is actually pointing the other way. The culture that will pressure you to go on is the same culture that will not cover your physio. Decide accordingly.",
 "move": "Set the rule before the season, not in the twenty minutes: a named list of injuries that mean you do not perform, agreed with yourself while nothing is at stake. Then it is a policy you are following rather than a judgment you are making under pressure.",
 "say": "Shoulder's gone, so I'm out tonight — that's firm. I can still do the ground set or safety for someone else if that helps you fill it.",
 "truth": "Nobody in that crowd will remember the set. You will be carrying the shoulder for thirty years.",
},
]
