# -*- coding: utf-8 -*-
"""F.L.O.W. scenarios, part 2 — CONTROL, TOOLS and COMMUNITY."""

SCENARIOS = [
{
 "section": "CONTROL",
 "hook": "I RIGGED IT MYSELF",
 "archetype": "The Rigger Who Owns The Point / Life Safety As Leverage",
 "clinical": "Safety-Critical Dependency / Technical Gatekeeping",
 "who": "The one with the hardware, the certification everyone assumes he has, and the only ladder. Rigs for everybody. Decides whose point goes up, when, and how high. Has never been asked to show anything.",
 "scene": "You want to fly and he is the only person here who can hang you. He is warm about it, competent-looking, and slightly dismissive when you ask what the anchor is rated to — he says he has been doing this since before you were spinning. Later he mentions, in the same warm voice, that some people get priority because they are part of the crew and you could be part of the crew.",
 "tells": [
  "One person rigs everything and no second competent person exists on site",
  "Deflects or jokes when asked about ratings, inspection, or load path",
  "Rigging priority tracks social closeness rather than the running order",
  "No written check, no second pair of eyes, no logbook",
  "Access to flying is described as something you earn from him socially",
  "Asking technical questions is treated as an insult rather than as normal",
 ],
 "happening": "Aerial rigging is life safety — a single point failure is a fall from height — and the entire discipline's professional practice is built on redundancy, documentation, and independent inspection precisely because competence cannot be established by reputation. When a festival has one unsupervised rigger, two things are true at once: the technical risk is unmanaged, and a person now controls something people want badly enough to trade for. The second follows from the first. It is the accessible-platform pattern from the A.C.C.E.S.S. guide, with the stakes raised from a good view to your spine.",
 "check": "F.L.O.W. — “W” CHECK: “Can this person tell me the load path and the rating, without irritation?” Competence explains itself. Only insecurity gets offended by the question.",
 "darkTitle": "Two Failures Sharing One Cause",
 "dark": "An unchecked rigger is both a fall risk and a coercion risk, and they are the same structural fact: nobody is watching, and the thing he controls is something you will trade for. That is how these situations run for years without a complaint — the people who could complain need the point, and the people who could check him were never appointed. If you take one thing from this page: a competent rigger will answer a technical question with relief, because it means somebody else in the room is thinking. The irritation is the signal. It means he has not been asked before, and that is the actual finding — not about him specifically, about the whole arrangement.",
 "move": "Ask the three questions before you ever go up: what is the anchor, what is it rated to, and who checked it besides you. Do not fly on a point nobody but its own rigger has inspected. Find the second competent person on site on arrival — if there is not one, that is your answer about flying this weekend.",
 "say": "Before I go up — what's the anchor and the rating, and who's your second pair of eyes on it? I ask everyone, it's not about you.",
 "truth": "Redundancy is the whole discipline. A rig with one person and no check is not a rig, it is a bet.",
},
{
 "section": "CONTROL",
 "hook": "THE CLIP'S ALREADY UP",
 "archetype": "The Filmer / Your Body As Somebody Else's Content",
 "clinical": "Image Appropriation / Non-Consensual Distribution",
 "who": "Always filming, often good at it, and operating on the assumption that a public performance is a public license. Sometimes a friend with a phone. Sometimes an account with two hundred thousand followers and a monetization deal.",
 "scene": "You burned last night. This morning there is a clip of it on an account you have never heard of, forty thousand views, your face clearly visible, your name nowhere, a brand tagged in the caption. The comments are mostly about your body. Somebody has stitched it. You did not know a camera was there, and the account owner, when you message, is genuinely baffled that you are not pleased.",
 "tells": [
  "Films without asking and treats performing as blanket consent",
  "Cannot say where footage will end up or who else gets it",
  "Credits the venue and the brand but not the performer",
  "Reacts to a takedown request as though you are being ungrateful",
  "Monetized account, unmonetized subject",
  "Costume, aerial, and fire performers get framed body-first",
 ],
 "happening": "Performing in public does not transfer your rights in your own image, and it never has — but the practical position is that enforcement is slow, cross-border, and expensive, so the operative protection is the one you set up in advance rather than the one you litigate afterwards. What makes this acute for flow and aerial performers is the combination of revealing costume, physical spectacle, and a distribution system that rewards exactly the framing you did not choose. The version that does real harm is not the friendly clip, it is the reposted one, where it travels without context, without your name, and often into spaces you would never have agreed to.",
 "check": "F.L.O.W. — “L” CHECK: “Have I said, out loud, before I start, what I consent to being filmed and posted?” Silence gets read as a yes by people who wanted a yes.",
 "darkTitle": "It Does Not Come Back Down",
 "dark": "Once a clip is stitched, reposted, and mirrored, there is no version of this where you get it back. The realistic goal is containment, not removal — which is why the work is all front-loaded. State it before the burn, to the organizer and to anyone visibly filming, and get the organizer's media policy in writing when you agree to the gig. The second thing worth knowing is that this is often where a different kind of leverage starts: somebody holding footage of you, and mentioning it. Footage held over a performer is coercion, it is not a grey area, and the response is the same as for any other documentation threat — tell one person now, in writing, so the footage stops being a secret that can be spent.",
 "move": "Set your policy before you are lit, in one sentence, to the organizer and the circle. Get the event's media terms in writing when you take the booking. Watermark or claim your own footage first so the canonical version is yours.",
 "say": "Happy to be filmed, not happy to be posted without a tag — credit me or don't put it up. Who's your media lead so I can send them that in writing?",
 "truth": "A performance is not a release. Saying so takes six seconds and it is the only part of this you control.",
},
{
 "section": "TOOLS",
 "hook": "THE THIRTY-SECOND PRE-BURN",
 "archetype": "The Check You Run Every Time, Out Loud",
 "clinical": "Safety Protocol / Pre-Performance Checklist",
 "who": "For every fire, aerial, and prop performer, at every skill level. The veterans who have been hurt are the most rigorous people in any circle, and that is not a coincidence — it is what the injury taught them.",
 "scene": "You are about to go. There is a circle waiting, a running order slipping, and a version of you that wants to skip this because everything looks fine and everything usually is. This page exists because “usually” is doing an enormous amount of work in that sentence.",
 "tells": [
  "Fuel: which fuel, how old, where is the depot, is it lidded and upwind",
  "Tools: wicks sound, no loose hardware, chains and leaders intact",
  "Body: hair tied, no synthetics, nothing loose, sober enough to be doing this",
  "Safety: who, do they have duvetyne, can they say what they would do",
  "Stop: what is the call, who can make it, does everyone know it",
  "Rig: anchor, rating, second inspection, and a spotter who is watching you",
 ],
 "happening": "Checklists work for the same reason in every high-consequence discipline: they take the decision out of the moment and out of the social context. Reading a list is not a judgment call and cannot be read as a comment on the people present, which is precisely what makes it survivable under an impatient circle. Saying it out loud does the second job — it makes the check public, which means the circle adjusts to it rather than you adjusting to the circle, and it quietly gives permission to the newer performer behind you who was not going to ask.",
 "check": "F.L.O.W. — “F” CHECK: “Did I run all six, this time, for this burn?” Last burn's check does not cover this one. Fuel moves, safeties change, hardware fails between sets.",
 "darkTitle": "The Check Is Also Social Cover",
 "dark": "There is a second reason to do it out loud and it is not about fire. A performer who visibly runs their own checks, asks technical questions, and is comfortable being briefly annoying in front of a circle is a conspicuously bad target for every pattern in this guide — the mentor with the private lesson, the rigger who does not like being asked, the person who wants the footage. Not because it makes you unpleasant, but because all of those depend on you being someone who will not make a small public fuss to avoid an awkward moment. The checklist trains exactly that muscle, thirty seconds at a time, on something where you already know you are right.",
 "move": "Run the six out loud, in the same order, every single time, until it is your known habit and the circle expects it. Teach it to the newest person there — that is how it becomes the culture rather than your quirk.",
 "say": "Fuel, tools, body, safety, stop call, rig. — Right, what's the stop call tonight?",
 "truth": "Every burned performer in this scene can tell you exactly which item they skipped. Run all six.",
},
{
 "section": "COMMUNITY",
 "hook": "WHOSE CIRCLE IS THIS",
 "archetype": "Real Jam Culture Versus A Circle With An Owner",
 "clinical": "Authentic Practice Space vs Gatekept Hierarchy",
 "who": "The good version has no owner, teaches sideways, and lets terrible beginners take up space. The other version has a centre, and the centre is a person, and everyone's position is measured by distance from him.",
 "scene": "Two circles at the same festival. In the first, a woman who has been spinning for twenty years spends eleven minutes helping somebody who picked up poi on Thursday, then goes back to her own practice and never mentions it again. In the second, everyone is subtly performing for one man at the edge, and when he leaves for ten minutes the energy of the whole circle changes, and everybody notices that it did.",
 "tells": [
  "Real: beginners get space and nobody is ranked",
  "Real: teaching flows in every direction, including upward",
  "Real: you can leave, be bad, or sit out with no cost",
  "Owned: one person's approval organizes the room",
  "Owned: access to gear, instruction, or gigs routes through him",
  "Owned: people describe the circle by his name",
 ],
 "happening": "A practice circle is one of the genuinely great things this scene produces — skill transmitted for free, across ages and levels, because somebody once did it for you. It is also a structure with an obvious failure mode: circles with a centre concentrate access, and concentrated access is what every pattern in this guide runs on. The test is identical to the one in every other guide here, which is not an accident: can you decline, be unimpressive, or leave without it costing you? In a real jam the answer is yes and nobody registers it. In an owned one, everybody registers everything.",
 "check": "F.L.O.W. — “W” CHECK: “If I sat out tonight and said nothing, would anything change for me here?” If sitting out has a price, this circle has an owner.",
 "darkTitle": "When The Circle Is The Supply Chain",
 "dark": "It gets serious when the circle is also where the gigs, the gear, and the instruction come from, because then leaving costs your practice and not just your evening. That is the configuration to watch for — not a charismatic person, which is normal and often lovely, but one person sitting across all of it at once. Everybody in that circle can feel it and nobody names it, because naming it is the thing that costs the most. If you are reading this and recognizing your own circle: the others already know, the conversation is easier than you think, and the fix is usually structural rather than confrontational. Two teachers. A second rigger. Somebody else who books.",
 "move": "Keep your practice plural on purpose — more than one circle, more than one teacher, more than one route to a gig. Then hand skill downward for free, because a circle where everybody teaches cannot develop a centre.",
 "say": "Come spin with us, we're rubbish and nobody cares. — Here, let me show you the grip, it took me a year to work out and it shouldn't have.",
 "truth": "A jam that needs a specific person to be good is not a jam. It is an audience with props.",
},
]
