# -*- coding: utf-8 -*-
"""H.E.A.L. scenarios — CAPTURE, CONDITION, CONTROL."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "I TRAINED WITH A LINEAGE",
 "archetype": "The Unverifiable Credential / Borrowed Authority",
 "clinical": "Credential Fabrication / Appeal to Unfalsifiable Lineage",
 "who": "Speaks with total calm certainty about where the work came from. Names a teacher, a region, a tradition, a number of years. Everything he says is structurally impossible to check, and he chose it for that reason.",
 "scene": "He says he trained for nine years with a lineage holder in a place you would have to fly to, whose name he gives softly, as though saying it too loudly would be disrespectful. Nobody in this tent is going to fact-check that. Nobody in this tent could. And you notice, as he says it, that the reverence in his voice is doing all the work that a certificate would otherwise have to do.",
 "tells": [
  "Credentials that cannot be verified by design — remote, oral, or a deceased teacher",
  "Reverence used to make questions feel rude",
  "No insurance, no professional body, no supervisor, no complaints route",
  "Scope that expands to whatever you need — trauma, grief, fertility, diagnosis",
  "Vague about the parts a trained person is precise about: contraindications, referral, limits",
  "Gets cooler toward anyone who asks a second question",
 ],
 "happening": "Every regulated healing profession is built on three things a false practitioner cannot supply: a checkable qualification, a body that can remove you, and a named limit to your scope. Unverifiable lineage is chosen precisely because it substitutes for all three at once — authority without accountability. It is the single most common structure in this scene's abuse cases, and the reason is not mysticism, it is architecture. The honest practitioners with real traditional training are usually the easiest people in the world to ask about it; they will tell you their teacher, their years, what they do not do, and who they refer to. Precision is the tell in both directions.",
 "check": "H.E.A.L. — “E” CHECK: “Can I name this person's training, their limits, and who they answer to?” Three blanks is not a lineage. It is a costume.",
 "darkTitle": "Unfalsifiable Is The Feature",
 "dark": "Pay attention to what the claim is built out of: every element is unfalsifiable on purpose. Far away, long ago, orally transmitted, teacher deceased, tradition that does not certify. A person inventing a credential does not pick a claim you could check, and the ones who pick unfalsifiable claims are not being humble about the ineffable — they are engineering a position where doubting them is a spiritual failing rather than due diligence. That inversion is the actual product, because it is what makes the later stuff survivable: once questioning him reads as your resistance, the room will help him. Ask the second question. His temperature when you do is more informative than the answer.",
 "move": "Ask three plain questions in a friendly voice: who trained you, what do you not do, and who would I talk to if I had a problem with a session. Ask them in front of other people. Write down what he says.",
 "say": "Love the sound of that — who did you train with, and what's outside your scope? And if I had a concern afterwards, who's the person I'd raise it with?",
 "truth": "Real practitioners answer credential questions with relief. Only a costume is insulted by them.",
},
{
 "section": "CONDITION",
 "hook": "JUST RELAX INTO IT",
 "archetype": "Scope Creep On The Table / The Session That Keeps Extending",
 "clinical": "Boundary Erosion / Progressive Scope Violation",
 "who": "Booked for one thing, doing a slightly different thing by minute twenty. Narrates it as responsiveness — the body asked for it, the energy moved there. Never quite announces the change, which is how you end up somewhere you did not agree to.",
 "scene": "You booked a shoulder session. Forty minutes in, his hands are on your ribs and then lower and he is saying something about where the grief is held, and you are running an internal calculation about whether objecting would make you the person who does not understand the work. He has not done anything you could name. He has moved four times, and each individual move was two inches.",
 "tells": [
  "Contact moves to new areas without being named beforehand",
  "Changes framed as the body's request rather than a practitioner's decision",
  "Draping, positioning, or clothing renegotiated mid-session",
  "Session runs long without being re-agreed",
  "Objecting is pre-framed as not understanding the modality",
  "Each step is small enough to be deniable; the sequence is not",
 ],
 "happening": "Progressive boundary erosion is the documented mechanism in the overwhelming majority of bodywork and therapeutic misconduct cases, and it works because a body on a table is passive, undressed, prone, and socially committed to trusting the person touching it. Each two-inch move is individually defensible, which is the design — the practitioner is not testing whether you consent, he is testing whether you will interrupt. That is why the professional standard in every legitimate manual therapy is spoken permission before each new region, every session, regardless of history. It removes the thing being exploited, which is your reluctance to be the one who makes it weird.",
 "check": "H.E.A.L. — “H” CHECK: “Did they say what they were about to do, before they did it?” Unannounced contact is the violation, whatever it turns out to be.",
 "darkTitle": "They Are Testing The Interrupt, Not The Consent",
 "dark": "Understanding this changes what you watch for. He is not building toward a moment where you agree — he is establishing that you do not interrupt, because a person who did not object at two inches is statistically less likely to object at four, and he knows it. That is also why the recovery from this is so hard afterwards: you will interrogate your own silence rather than his sequence. Put it down. The obligation was never on the person lying face-down and half-dressed to narrate the boundary. It was on the trained professional to announce the next move, and he chose not to, repeatedly, which is the finding.",
 "move": "Interrupt early and cheaply, because the first interruption is the whole thing — it costs almost nothing at minute five and everything at minute forty. Sit up. Sitting up ends the physical frame, and you can be polite from upright.",
 "say": "Stop there — I booked shoulders, I want to stay on shoulders. — I'm going to sit up for a minute.",
 "truth": "You do not owe a practitioner the benefit of the doubt while they are touching you. That is exactly the wrong moment for generosity.",
},
{
 "section": "CONTROL",
 "hook": "THE MEDICINE CHOSE THIS",
 "archetype": "Spiritual Framing As A Consent Override",
 "clinical": "Ceremonial Coercion / Consent Override in Altered States",
 "who": "Holds the container, poured the cup, and is the only person in the room who is not altered. Interprets what is happening for everyone, including for you, including about you. Is never wrong inside the frame he built.",
 "scene": "You are four hours into something and the room has stopped having edges. He sits down close and says the medicine has shown him that you and he are meant to work together more deeply, that your resistance is the thing the work is for, and that this is the part where people either open or run. You cannot currently construct a sentence. He knows that. That is the reason this conversation is happening now and not on Tuesday.",
 "tells": [
  "The pitch arrives while you are altered and not before",
  "Your hesitation is renamed as resistance, fear, or ego",
  "He is the sole interpreter of what the experience means",
  "Pre-ceremony agreements about touch are revised mid-ceremony",
  "Nobody sober is in the room who is not him",
  "Leaving is framed as spiritually dangerous or as abandoning the work",
 ],
 "happening": "This is the single most important line in this guide: a consent given before an altered state cannot cover what happens inside it, and a consent given during one is not consent, because capacity is the thing the substance removed. Every serious ceremonial ethic in the world states it — no romantic or sexual contact with participants, no revision of agreements mid-state, a sober second person present. The reason is not squeamishness, it is that the facilitator holds total interpretive authority over someone who cannot currently evaluate interpretations. Any framework where your objection is proof the framework is working is not a spiritual technology. It is a closed loop, and closed loops are what this book calls a cage.",
 "check": "H.E.A.L. — “A” CHECK: “Is this being asked of me now because now is when I cannot assess it?” Timing is the tell. A real invitation survives Tuesday.",
 "darkTitle": "The Loop Where Your No Is Evidence",
 "dark": "The structure to name is the unfalsifiable loop: agreement proves the medicine is working, and refusal proves you have more work to do. Once that loop is running there is no answer you can give that exits it, which means the conversation was never a request. It is the same architecture as the unverifiable lineage on the first page of this guide and it is built by the same person for the same reason. This is also where the room turns — other participants, sincerely, will help, because they are inside the frame too and your resistance genuinely looks to them like fear. That is why the protection has to be structural and installed beforehand: a sober ally physically present, an agreement in writing, and someone outside the ceremony expecting to hear from you.",
 "move": "Set it before you sit down, in writing, and give a copy to someone not in the room: no touch beyond what is named, no agreements revised during, and a sober person of your choosing present. If you are already in it — you are allowed to say nothing, stand up, and walk to the sober person. You do not have to win the argument.",
 "say": "Before we start: nothing gets renegotiated once I've drunk. Anything you want to propose, propose it on Tuesday. — [in the moment] I'm not discussing this now. I'm going to sit with Nadia.",
 "truth": "Anything that is only true while you are altered is not true. It is just unopposed.",
},
{
 "section": "CONTROL",
 "hook": "I'LL WALK YOU THROUGH INTEGRATION",
 "archetype": "The Integrator / Dependency After The Fact",
 "clinical": "Dual Relationship / Post-Session Dependency",
 "who": "The same person who facilitated, now offering to be the one who helps you make sense of it — for a fee, or for closeness, or both. Often kind. Almost always the wrong person for the job.",
 "scene": "The ceremony was enormous and you are not okay and he is the only person who was there and understands. He offers weekly calls. Then he offers to have you stay. Then there is a retreat he thinks you should be at, and a role in his organization, and at no point was there a moment where you decided any of this — there was a moment where you needed help and he was standing there.",
 "tells": [
  "The facilitator is also the integrator, the landlord, the employer, or the partner",
  "Your understanding of your own experience routes entirely through him",
  "Cost escalates — money, time, proximity, loyalty",
  "He discourages outside therapy, framed as it not understanding the work",
  "Leaving the relationship would mean losing your sense of what happened to you",
  "Nobody independent has ever spoken to you about that ceremony",
 ],
 "happening": "Dual relationships are prohibited in every clinical code for one reason: each additional role removes an exit. When your facilitator is also your integrator, you cannot process a bad experience of him with anyone but him, and a person's interpretation of their own most vulnerable hours becomes something another person authors. Post-ceremonial suggestibility is real and elevated for a meaningful period afterwards, which makes that window the highest-leverage one that exists. An honest practitioner treats it as the most dangerous part of their work and refers out. That referral is the single clearest marker of a real one.",
 "check": "H.E.A.L. — “L” CHECK: “How many roles does this person hold in my life?” One is a relationship. Three is an enclosure.",
 "darkTitle": "Who Authors What Happened To You",
 "dark": "The lasting damage here is not financial and it is not even always sexual — it is authorship. If the only person who can tell you what your ceremony meant is the person who ran it, then a harm that occurred inside it is uninterpretable to you without his help, and he will help. People come out of these arrangements years later describing the disorientation of realizing they had no independent memory of their own experience, only his account of it. The counter is boringly practical and it has to be arranged in advance, while you still think you will not need it: a separate integrator, booked before the ceremony, who has never met the facilitator.",
 "move": "Separate the roles before you go in — book your integration with someone unconnected, ideally a licensed therapist familiar with this territory. Keep one relationship outside the whole ecosystem. If you are already inside it, the first move is one outside conversation, not a confrontation.",
 "say": "I've got integration booked with someone separate — I keep those roles apart on principle. Can you send me your notes for them?",
 "truth": "Nobody should be both the person who took you in and the only person who can bring you back.",
},
{
 "section": "ACCOUNTABILITY",
 "hook": "WHEN THE PRACTITIONER IS YOU",
 "archetype": "The Page For Your Own Practice",
 "clinical": "Practitioner Accountability / Power Differential Awareness",
 "who": "You. Honest, well-trained, in this for the right reasons, and holding more power in every session than the frame of healing makes it easy to notice.",
 "scene": "A client tells you, three weeks later, that something in a session did not sit right. Your entire body wants to explain — what you actually did, what the modality is, what they may have misread. That impulse is normal, it is human, and it is the exact moment where good practitioners become bad ones. What you do in the next sixty seconds is your whole ethics, and it is not a feeling, it is a procedure.",
 "tells": [
  "You are the only one who could say what happened in that room",
  "Your client was undressed, prone, altered, or grieving — sometimes all four",
  "Attraction to a client has arisen and you have not told a supervisor",
  "You have extended a session, or a role, because it felt right in the moment",
  "You have no supervisor, no insurance, and no complaints route",
  "Your first instinct on hearing a concern is to explain rather than to hear",
 ],
 "happening": "The power differential in this work does not switch off because your intentions are good. You control the room, the interpretation, the duration, and the narrative afterwards, and your client is frequently in a state they cannot fully assess. That is why every regulated profession requires supervision, insurance, a scope statement, and a complaints route that does not run through you — not because practitioners are assumed to be predators, but because an unsupervised practitioner cannot self-detect drift. The false shaman this guide opens with relies on the entire field being unregulated. The way honest practitioners take that cover away is by visibly having the things he cannot have.",
 "check": "H.E.A.L. — “L” CHECK: “If a client wanted to complain about me, could they — to someone who is not me?” If not, you are running the same structure as the person you would never want to be.",
 "darkTitle": "Nobody Decides To Become That Person",
 "dark": "Read the misconduct literature and the pattern is remarkably consistent: almost nobody sets out to do it. It goes one session long, then one region unannounced, then one dual relationship, then a rationalization that the work required it — and each step was taken by somebody who believed themselves to be a good practitioner, because they were, right up until they were not. Supervision exists because that drift is invisible from inside. If you are reading this and one specific session came to mind: that is not proof you are a bad practitioner, it is the ordinary early warning this whole page is for. Take it to a supervisor this week. The ones who never take anything to anyone are the ones this ends badly for.",
 "move": "Build what the false ones cannot fake: insurance, a named supervisor you actually use, a written scope with limits, a spoken consent brief every session, and a complaints route that bypasses you — published. If a concern comes to you, the first response is thank you for telling me, and the second is a referral to that route. Not an explanation.",
 "say": "Thank you for telling me — that took something. I'm not going to defend myself at you. Here's the person you can take it to independently, and I'll cooperate with whatever they ask.",
 "truth": "The practitioner people can safely complain about is the one worth going to. Be the one with a route that does not run through you.",
},
]
