# -*- coding: utf-8 -*-
"""H.O.M.E. scenarios."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "WHAT YOU READ ABOUT THESE PLACES",
 "archetype": "The Fear You Were Sold / Why Accuracy Is On Your Side",
 "clinical": "Risk Miscalibration / Credibility Cost of Inaccuracy",
 "who": "You, at eleven at night, four articles deep, having typed a question into a search bar that only ever returns the worst weekend anybody ever had anywhere.",
 "scene": "You have read about the deaths. You have read the thread. You have a picture in your head assembled entirely from the events that were unusual enough to be written about, and you are about to have a conversation with somebody you love, using that picture as your evidence, and you cannot understand why they are getting defensive.",
 "tells": [
  "Everything you know came from coverage of things that went wrong",
  "You have not asked them a single question you did not already have an answer to",
  "Your sentences start with statistics you cannot source",
  "You are describing their friends, whom you have not met, as a risk",
  "The conversation always ends the same way, and it ends early",
  "You know less about this trip than you did about the last one",
 ],
 "happening": "News coverage selects for the rare and the terrible — that is what makes something news — so an hour of searching builds a picture in which the exception is the rule. The person you are talking to has been to four of these and had four ordinary, joyful weekends, so when you describe a place they do not recognize, the thing they learn is not that festivals are dangerous. It is that you do not know what you are talking about, and that everything else you say on the subject can be discounted. That is the actual cost, and it is not abstract: it is why they will not ring you.",
 "check": "H.O.M.E. — “M” CHECK: “Does what I am about to say match what they will actually see this weekend?” If not, you are spending credibility you will need later.",
 "darkTitle": "The Silence You Are Building",
 "dark": "Here is the thing nobody tells parents and partners. The research on this is consistent and it is the opposite of intuitive: young people decide who to tell about a bad situation almost entirely on their prediction of the reaction, not on the severity of what happened. Every exaggeration, every I-told-you-so, every conversation that ended in a lecture is data they are using to make that prediction. So an approach built on warning them can produce exactly the outcome it was designed to prevent — a person in real trouble at four in the morning, running down the list of people who will not make it worse, and not finding you on it. That is what is actually at stake in how you handle the week before.",
 "move": "Stop researching and start asking. Say plainly that you do not know much about this and would like to, and then let them tell you — people explain their world at length to anyone who is genuinely curious rather than building a case.",
 "say": "I've been reading stuff that's probably rubbish and I'd rather hear it from you. What's it actually like? What's the bit you look forward to?",
 "truth": "Accuracy is not approval. It is the only way to stay somebody whose opinion still counts for anything.",
},
{
 "section": "TOOLS",
 "hook": "THE CONVERSATION BEFORE THEY GO",
 "archetype": "Two Questions, One Sentence, Four Minutes",
 "clinical": "Protective Communication / Disclosure Enablement",
 "who": "For the parent, partner, sibling or friend who has one conversation available and wants to spend it well rather than spend it all.",
 "scene": "You have maybe four minutes of genuine attention before this becomes a thing you do every year that they endure. Four minutes is plenty. What follows is more protective than any amount of worrying, and it is almost entirely about what you do not say.",
 "tells": [
  "Ask who they are going with — names, not “mates”",
  "Ask where they are staying and how they are getting home",
  "Say the one sentence about calling you, and then stop talking",
  "Do not attach conditions, consequences, or a lecture to that sentence",
  "Do not ask about substances unless you can hear the answer without reacting",
  "End it early, warmly, and let them go and have a good time",
 ],
 "happening": "Two questions get you the information that actually matters — who is around them and how they get out — and both are answerable without anybody having to confess to anything. The one sentence is the load-bearing part, and its power comes entirely from being unconditional: the moment it has a clause attached, it stops being a promise and becomes a negotiation, and negotiations get remembered at four in the morning. Say it once, plainly, and do not garnish it. The restraint is the technique.",
 "check": "H.O.M.E. — “O” CHECK: “Have I asked two questions, or started listing things?” Two questions and a sentence. Then stop.",
 "darkTitle": "Say It Once, Exactly, With No Clause",
 "dark": "The sentence is: if anything goes wrong, at any hour, for any reason, ring me — and I will not be angry and I will not say I told you so, I will just come and get you. That is the whole sentence and every word of it is doing work. At any hour, because they will otherwise wait until morning. For any reason, because they will otherwise decide theirs does not qualify. I will not be angry, because that is the specific prediction they are running. And you have to mean it, because you will be tested on it once, probably over something small, and how you handle that one determines whether the sentence is real for the next ten years.",
 "move": "Ask the two questions. Say the sentence once, plainly, with nothing attached. Then change the subject and let them pack. Four minutes.",
 "say": "Who are you going with? And where are you staying — how are you getting back? — Right. Last thing: if anything goes wrong, any hour, any reason, ring me. I won't be angry and I won't say I told you so, I'll just come and get you. That's it. Have an amazing time.",
 "truth": "The most protective thing available to you is a promise with no conditions on it, said once and kept the first time it is used.",
},
{
 "section": "EMERGENCY",
 "hook": "IF THE CALL COMES",
 "archetype": "The First Ten Minutes",
 "clinical": "Crisis Response / Immediate Support Protocol",
 "who": "You, woken at four in the morning, hearing something in their voice before you have understood a single word.",
 "scene": "The call you hoped would not come has come. Everything you do in the next ten minutes either makes you someone they can use or someone they regret ringing, and you will be operating on no sleep and pure adrenaline. This is why it is written down.",
 "tells": [
  "First sentence: are you safe right now, and where exactly are you",
  "Second: is anyone with you, and can you get to welfare or medical",
  "No questions about what they took, what they were wearing, or whose fault it is",
  "Do not say you told them so, at any point, for any reason, ever",
  "Write down what they tell you — location, names, time — while they say it",
  "Stay on the line until they are with a person who can help",
 ],
 "happening": "In the first ten minutes there are exactly three useful things: establish safety, establish location, and get them to someone physically present who can help. Everything else — the explanation, the details, the feelings, the question of how this happened — belongs to a later conversation and will be available then. The reason to know this in advance is that your own fear will be enormous and will present itself as an urgent need for information, and answering that need is the single most common way these calls go wrong.",
 "check": "H.O.M.E. — “E” CHECK: “Am I getting them help, or getting myself information?” Both feel identical at four in the morning. Only one of them is useful.",
 "darkTitle": "What Not To Say, And The Thing To Know",
 "dark": "Never, in that call, ask what they took or what they were wearing or why they went off alone. Not because it is rude — because it tells them this was their fault, and that judgment will shut down the disclosure mid-sentence and quite possibly permanently. Two practical things worth knowing before you ever need them. Every festival has a welfare or medical tent that operates day and night, and it is staffed by people who do this constantly and without judgment; getting your person to that tent is more useful than any advice you can give down a phone. And if it was an assault: in most places a forensic examination can be done without making a police report, the window is measured in days not hours, and the decision about police can be made later. That single fact is one most people do not know, and knowing it removes the choice that stops people getting care.",
 "move": "Safety, location, get them to a human. Write down what they say as they say it. Then — and only then — ask what they need from you, and do that rather than what you think they need.",
 "say": "Are you safe right now? Where are you exactly? Is anyone with you? — Okay. I want you to walk to the welfare tent and stay on the phone with me while you do it. You've done the right thing ringing me. We'll sort everything else out after.",
 "truth": "They rang you. Whatever else happens tonight, that means you got the week before right. Do not spend it in the first ten minutes.",
},
{
 "section": "COMMUNITY",
 "hook": "WHAT THIS PLACE ACTUALLY IS",
 "archetype": "The Part The Coverage Never Gets To",
 "clinical": "Contextual Understanding / Accurate Risk Framing",
 "who": "For you, at the end, from people who have spent their lives in this world and have written an entire book about its dangers — which is exactly why this page is worth trusting.",
 "scene": "Everything else in this book is about what can go wrong, because that is what a safety guide is for. Read as a whole it gives a false impression, and it would be dishonest to hand you a hundred pages of predators and let you think that is the place your person is going to.",
 "tells": [
  "Strangers walk each other to medical tents at three in the morning, constantly",
  "People search fields all night for someone they have never met",
  "There are volunteers whose entire role is sitting with frightened people",
  "Someone will give your person water, sunscreen, a charger, a lift, for nothing",
  "The vast majority of people come home tired, sunburnt and happy",
  "They will talk about it for a year, and you will get bored of hearing about it",
 ],
 "happening": "The reason this scene is worth protecting is that it is genuinely unusual: a place where radical acceptance is the default, where people look after strangers as a matter of course, and where somebody can be more themselves for seventy-two hours than they manage anywhere else all year. The patterns in this book exist because predators seek out open-hearted places, and open-heartedness is the thing worth defending rather than the mistake. Your person is not naive for loving it. They are going somewhere that gives them something the default world does not, and the overwhelming likelihood is that they will come home with a sunburn and too many stories.",
 "check": "H.O.M.E. — “H” CHECK: “Am I treating this as a threat to survive, or as a thing they love?” They can tell which one you think it is, and it determines everything.",
 "darkTitle": "Why You Were Given This",
 "dark": "Somebody handed you this guide. That was not an accident and it was not an accusation — it means they want you inside this part of their life rather than outside it, and they were worried enough about your reaction to give you a manual first. That is worth sitting with. The single most protective thing in this entire book is not a tactic or a check or a script; it is a young person who is certain, without having to think about it, that there is somebody at home who will pick up at four in the morning and not make it worse. You can be that by Friday. Nothing else on this page matters as much.",
 "move": "Text them on the Saturday and ask what the best set was. Do not ask if they are okay — ask what was good. Then, when they get back, let them tell you about it at length and be genuinely interested, because that is what keeps the channel open until the year they need it.",
 "say": "What's been the best thing so far? — [when they're home] Right, tell me everything. Start with the music.",
 "truth": "They are going somewhere that makes them more themselves. Be the person they can come home and tell.",
},
]
