# -*- coding: utf-8 -*-
"""K.I.N. scenarios."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "HE'S SO GOOD WITH KIDS",
 "archetype": "The Beloved Camp Uncle / Access Through Trust",
 "clinical": "Child Grooming / Institutional Trust Exploitation",
 "who": "Genuinely great with children, which is the difficult part of this page. Everybody's favourite. Has been coming for years, runs the games, remembers the kids' names between festivals, and is the first person anyone would defend.",
 "scene": "Your daughter adores him. He does the face paint and the treasure hunt and he is the reason the family field is fun. He has started giving her small presents — a bracelet, a patch for her jacket — and asking for her specifically, and suggesting he take her to the workshop tent because you look tired, and the sentence forming in your head is that you would be insulting a good man to say no.",
 "tells": [
  "Seeks time alone with a specific child, always with a good reason",
  "Gives gifts or attention to one child rather than to all of them",
  "Establishes secrets — small, harmless ones, framed as a shared joke",
  "Prefers the company of children to that of adults at an adult event",
  "Pushes past a soft no with warmth rather than pressure",
  "Universally liked, which means raising anything has a social cost",
 ],
 "happening": "Child sexual abuse is overwhelmingly committed by somebody the child and the family already know and trust, and the grooming literature describes a consistent sequence: access, then a special relationship with one child, then small secrets, then isolation. Every step looks like kindness and most of them, performed by most people, are kindness. That is exactly why safeguarding policy in every organization that works with children is built on rules about situations rather than judgments about people — because judging individuals is precisely what the pattern defeats, and because the people who are wrongly suspected and the people who are correctly suspected look identical from outside.",
 "check": "K.I.N. — “N” CHECK: “Is an adult asking for time alone with my child?” The answer is no, every time, regardless of who is asking. The rule is the protection. Assessing the person is not.",
 "darkTitle": "The Rule Exists So You Never Have To Judge",
 "dark": "This is the hardest page in this book to write and to read, and the reason is that the overwhelming majority of beloved camp uncles are exactly what they appear to be — generous adults who like kids and make festivals magical. A blanket rule is not an accusation against any of them. It is a rule precisely because no parent can reliably tell, because the ones who cannot be told apart are the whole problem, and because a good man will not mind. That last part is the practical test: a genuinely safe adult hears “we don't do one-on-one” and says fine, of course, come along too. Only one kind of person argues with a safeguarding rule, and the argument is the finding.",
 "move": "Make it a policy rather than a judgment, and say it out loud to the whole camp at the start so it is never about one person: no one-on-one, activities happen with two adults or in view. Then say yes to everything that meets the rule — the face paint, the treasure hunt, all of it.",
 "say": "We do a two-adult rule for the kids, nothing personal to anyone — so yes to the workshop, and I'll walk over with you both.",
 "truth": "Good adults are not offended by safeguarding rules. The rule protects them too, and the person who argues has told you something.",
},
{
 "section": "CONDITION",
 "hook": "I THOUGHT HE WAS WITH YOU",
 "archetype": "Diffused Supervision / The Camp Everybody Assumed",
 "clinical": "Responsibility Diffusion / Supervision Gap",
 "who": "Not a person — a structure. Eleven adults, four children, a shared camp, an unspoken sense that somebody is always around, and no moment at which anybody specifically agreed to be watching.",
 "scene": "It is nine in the evening and somebody asks where Theo is and there is a pause, and in that pause four adults each realize they had assumed one of the others had him. He is almost certainly thirty metres away at the other fire. He almost certainly is. The forty seconds before you find him are the longest forty seconds of the year and nothing in the camp's arrangements was designed to prevent them.",
 "tells": [
  "Supervision described as “the camp” rather than a named adult",
  "No agreed handover — children move between adults without a word said",
  "Nobody knows how many adults are currently drinking or dosed",
  "No headcount, and no agreed time for one",
  "Older children tasked with younger ones without that being decided",
  "“Someone's always around” said as though it were a system",
 ],
 "happening": "Diffusion of responsibility is one of the most robust findings in social psychology: the more people who could act, the less likely any given person is to act, and the more each assumes somebody else has. Applied to child supervision in a camp it produces a specific failure — not neglect, but a group of attentive adults each accurately believing the child is covered. Festivals add the aggravating factors: no fences, thousands of strangers, darkness, noise that swallows a shout, and a proportion of the adults present with reduced capacity. The fix is not more vigilance. It is a named person and a spoken handover, which converts an assumption into an agreement.",
 "check": "K.I.N. — “K” CHECK: “Can I name the adult who has my child right now, and did they say yes out loud?” If the answer is a camp rather than a name, nobody has them.",
 "darkTitle": "The Other Half Is Your Own Capacity",
 "dark": "The part that is harder to say: the handover rule has to include you. A festival is one of the few places where a parent may be genuinely impaired — drinking, dosed, or simply forty hours short of sleep — and the moment where you most need to hand over is the moment you are least able to assess that you should. So the decision gets made in advance, sober, like a designated driver: who is on duty tonight, who is not drinking, and what the signal is for I am done, take over. Agreeing that on Thursday costs a five-minute conversation. Not agreeing it is how a child ends up nominally supervised by four adults, none of whom is currently able to drive.",
 "move": "Run a nightly rota decided in advance: a named on-duty adult each evening who stays under, and a spoken handover every time a child changes hands — “you have Theo until eight”, answered out loud. Headcount at every set change.",
 "say": "You've got Theo till eight — say it back to me. — I'm on duty tonight, so I'm not drinking; Mo's on tomorrow.",
 "truth": "“I thought he was with you” is what four attentive adults say. A name and a time out loud is the only thing that prevents it.",
},
{
 "section": "TOOLS",
 "hook": "THE LOST-KID KIT",
 "archetype": "Ten Minutes On Thursday That You Will Never Regret",
 "clinical": "Child Safety Preparation / Lost Child Protocol",
 "who": "For everyone in the family field, every year, including the veterans who have done twelve of these and especially the ones who think their kid is too sensible to get lost.",
 "scene": "The first ninety seconds of a missing child are the ones that matter, and they are ninety seconds in which you will be useless — heart rate through the roof, unable to remember what they were wearing, phone at four percent. Everything on this page exists so that a calm Thursday version of you has already done the thinking.",
 "tells": [
  "Wristband with your mobile number, written fresh each morning",
  "A photo of each child taken every morning, in that day's actual clothes",
  "A meeting point they can say back to you, chosen and physically visited",
  "The phrase: find a person with a radio, or a stall, or a mum with kids",
  "Ear defenders, sun hat, water — the boring three that prevent most of it",
  "Your phone charged, and a second adult's number on the band too",
 ],
 "happening": "Lost children at festivals are common and almost always resolve in minutes, and the reason they resolve is infrastructure: wristbands with numbers, a welfare tent that does this constantly, and staff who are trained for it. The daily photo is the single highest-value item and the one almost nobody does — a described child is hard to search for and a photographed child in today's clothes is easy. Teaching who to approach matters as much as teaching not to wander: children told only about stranger danger will avoid the very adults most likely to help them, so name the categories instead — radio, stall, parent with kids.",
 "check": "K.I.N. — “I” CHECK: “Wristband on, photo taken today, meeting point they can repeat?” Three things, every morning, before anything else.",
 "darkTitle": "Ninety Seconds, And What To Do In Them",
 "dark": "Have the protocol memorized because you will not be able to reason it out. One adult stays exactly where the child was last seen and does not move — children double back, and a moving parent and a moving child can search past each other for an hour. A second adult goes straight to welfare or the nearest radio and reports it immediately; there is no waiting period and nobody will think you are overreacting, because they do this several times a day. Show the photo. Give the wristband number so it can be called. Everyone else checks the last three places the child liked, not the whole site. Ninety seconds of the right actions beats twenty minutes of frantic ones.",
 "move": "Do the three every morning — band, photo, meeting point — and walk the child to the welfare tent on Thursday so they have physically seen where it is. Agree the stay-put rule with the other adults now, before it is needed.",
 "say": "If you can't find me: stay where you are and find someone with a radio, or a stall, or a mum with kids. Show them your wristband. Tell me the plan back?",
 "truth": "Ten minutes on Thursday buys you the only ninety seconds that will ever matter. Do the photo — it is the one everybody skips.",
},
{
 "section": "COMMUNITY",
 "hook": "IT TAKES A VILLAGE, NAMED",
 "archetype": "A Real Village Versus An Assumed One",
 "clinical": "Authentic Collective Care vs Diffused Assumption",
 "who": "The family field at its best, which is genuinely one of the great things this culture has built — kids running semi-feral in the safest possible way, raised for a weekend by twenty adults who all know them.",
 "scene": "The real version is unmistakable once you have seen it. Adults who know which kid belongs to whom. Somebody bringing your child back with a comment about the face paint. A camp where the rota is on the whiteboard and nobody thinks that is uptight. Kids who can name four adults they are allowed to go to, because somebody sat down and taught them the four.",
 "tells": [
  "Real: adults are named, rotas exist, handovers are spoken",
  "Real: children can name the adults they may go to",
  "Real: someone is always sober and everyone knows who",
  "Real: the two-adult rule is stated openly and nobody is offended",
  "Assumed: “someone's always around”, and no one is specifically",
  "Assumed: raising a safeguarding point would make you the awkward one",
 ],
 "happening": "The village is real and it works, and it works because of structure rather than in spite of it. The camps where children are genuinely safest are the ones that look, from outside, slightly over-organized: whiteboard, rota, named on-duty adult, an out-loud rule about one-on-one. That structure is what lets the freedom be real — kids roaming the family field all weekend, which is the thing you came for. The unstructured version produces the opposite: adults who feel responsible in general and therefore nobody responsible in particular, and a culture where the person who suggests a rota is the problem.",
 "check": "K.I.N. — “K” CHECK: “Can every adult here name tonight's on-duty person, and can every kid name four adults they can go to?” Two questions, asked on Thursday.",
 "darkTitle": "Be The One Who Says It First",
 "dark": "Somebody has to say the rules out loud, and in a warm camp of old friends that feels enormously awkward — like importing suspicion into a place built on trust. Say them anyway, and say them on day one, to everyone, before anything has happened, because a rule introduced as general policy costs nothing and a rule introduced after a specific worry is an accusation. You will find that most of the camp is relieved. Parents are usually all quietly thinking it and each assuming they would be the uptight one, which is the same diffusion problem as the supervision gap, applied to speaking up.",
 "move": "Call the five-minute family brief on Thursday: rota, on-duty adult, two-adult rule, meeting point, and the four adults each child may go to. Put it on a whiteboard. Then let them run.",
 "say": "Quick family-camp thing before we all settle in — rota's on the board, on-duty's not drinking, no one-on-one with the kids, and let's make sure every kid can name four grown-ups they can go to.",
 "truth": "The village is real, and it is made of names. A village where nobody is named is just a field with your child in it.",
},
]
