# -*- coding: utf-8 -*-
"""L.E.N.S. scenarios."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "I CAN GET YOU BACKSTAGE",
 "archetype": "The Camera As A Key / Access Offered In Trade",
 "clinical": "Access Exploitation / Quid Pro Quo Grooming",
 "who": "Has a laminate, a long lens, and an unusual amount of freedom of movement. Offers to shoot you, offers to get you in, offers to introduce you — and the offers arrive in a sequence that keeps having a next step.",
 "scene": "He says your look is incredible and he wants to shoot you properly, and he can get you into the artist area because he shoots for them. The first shoot is professional and the pictures are genuinely the best you have ever had of yourself. The second one he suggests somewhere private for the light, and mentions the festival he shoots in the spring, and asks whether you would want to be involved with that.",
 "tells": [
  "Access, introductions and opportunity all route through one person",
  "Shoots move from public to private across sessions",
  "Wardrobe or nudity is introduced gradually rather than agreed up front",
  "The next opportunity is always just ahead and is always in his gift",
  "No call sheet, no assistant, no third person, no written brief",
  "The work is good, which is what makes the arrangement hard to leave",
 ],
 "happening": "A camera is one of the most efficient access tools at a festival — it explains proximity, justifies attention, licenses photographing strangers, and moves through restricted space. Nearly everyone carrying one is doing the job. But the same properties make it attractive to someone who wants proximity for other reasons, and the pattern is the classic one from the modelling and music industries: real opportunity, real skill, real photographs, with each step requiring slightly more and each step justified by the last. The tell is not creepiness. It is the absence of the ordinary professional furniture — no brief, no third person, no rate, nothing in writing.",
 "check": "L.E.N.S. — “E” CHECK: “Is there a third person, a written brief, and a stated rate?” Professionals have all three. Their absence is not informality, it is the design.",
 "darkTitle": "The Photographs Are The Hold",
 "dark": "The photographs themselves become the leverage, and that is often the point rather than a side effect. Once someone holds images of you — especially anything you agreed to when you were tired, altered, flattered, or halfway through a shoot you did not want to ruin — they hold something that can be released, hinted at, or simply remembered out loud. Nothing has to be threatened. If you are in this: the files existing is not the end of your options, and the fastest way to defuse a hold is to stop it being a secret — tell one person now, in writing, before anything is asked. A secret with two keepers is worth far less to the person holding it.",
 "move": "Insist on the professional furniture: a written brief, a rate or a clear trade, a third person present, and no private locations for a first shoot. Bring somebody. Somebody wanting to shoot you properly will not mind an assistant; somebody wanting the room will mind a great deal, and that is your answer.",
 "say": "Sounds great — I'll bring a friend, and can you send me a quick brief and what the usage is? I keep it all written down, it's just how I work.",
 "truth": "A real photographer wants an assistant, a brief and a release. The ones who want the room empty are telling you what the shoot is for.",
},
{
 "section": "CONDITION",
 "hook": "SHE WON'T MIND, SHE'S HAVING A GREAT TIME",
 "archetype": "The Frame You Did Not Earn / Shooting The Incapacitated",
 "clinical": "Non-Consensual Capture / Exploitation of Impairment",
 "who": "You, on a good night, with a great frame in front of you and a legal right to take it and a rationalization already forming. This page is aimed at the photographer, not at the subject.",
 "scene": "It is four in the morning and she is beautiful and completely gone, sitting on the grass laughing at nothing with her top half off, and it is the best light of the entire weekend. Nobody would stop you. It is a public field. She is not in a position to object and will not remember either way, and you already know that is the reason the shot is available.",
 "tells": [
  "The subject could not consent right now if you asked",
  "You are relying on them not noticing rather than on them agreeing",
  "The frame's value comes from their state rather than from the moment",
  "Long lens, from distance, on someone who has not clocked you",
  "You are constructing a justification before you have taken it",
  "You would not show them the shot tomorrow and ask",
 ],
 "happening": "Legality and ethics part company here completely. In most jurisdictions you may photograph people in public and publish it, and that permission is exactly why the profession needs a standard above it — the law is not doing the work of deciding whether a frame should exist. A person who is incapacitated cannot consent to being photographed any more than they can consent to anything else, and a photographer relying on their impairment has made the same move as everybody else in this book who waits for capacity to drop. The test is simple and it is the one the whole trade runs on: could you show them tomorrow, and would they say yes.",
 "check": "L.E.N.S. — “L” CHECK: “Could this person consent right now if I asked?” If not, there is no frame here. The camera does not create a permission the situation does not contain.",
 "darkTitle": "You Are The Risk On This Page",
 "dark": "Most of this book is about somebody doing something to the reader. This page is the other way round, and it is in here because festival photography has a genuine, ongoing problem with it: the near-nude, the overwhelmed, the passed-out, the person in a crisis at the harm-reduction tent, shot at distance and posted as atmosphere. Those frames circulate for years. They cost people jobs, custody arrangements, and their sense of safety in a place they loved. The photographer is usually not malicious — they are a person who wanted a good shot and let the law answer an ethical question. Do not be that. Tomorrow-test every frame, and when a frame fails it, do not take it rather than not posting it, because files leak and drives get shared.",
 "move": "Apply the tomorrow test before the shutter, not before the upload. If someone is impaired, in distress, or in a medical or harm-reduction context, put the camera down entirely — and if you have already shot it, delete it now rather than filing it.",
 "say": "Not shooting that one. — [to a colleague] Mate, she's gone, leave it. Get the crowd instead.",
 "truth": "The law says you may. The law is not your ethics, and a photograph of somebody's worst night outlives both of you.",
},
{
 "section": "CONTROL",
 "hook": "IT'S GREAT EXPOSURE",
 "archetype": "The Rights Grab / Unpaid, Unlimited, Perpetual",
 "clinical": "IP Appropriation / Unconscionable Contract Terms",
 "who": "The media accreditation form nobody reads, and the production manager who genuinely believes a wristband is payment because everybody has always said it is.",
 "scene": "The accreditation form is four paragraphs and you are filling it in on your phone in a queue. One of those paragraphs assigns the festival a perpetual, worldwide, royalty-free, sublicensable license to everything you shoot, in all media, for any purpose including advertising, with no credit obligation. You tick it because the gate opens in ten minutes and because everyone ticks it.",
 "tells": [
  "“Perpetual”, “irrevocable”, “royalty-free”, “all media now known or hereafter devised”",
  "Sublicensable — meaning sponsors and brands get your work too",
  "No credit obligation, or credit at their discretion",
  "Payment described as exposure, access, or a wristband",
  "The form arrives at the gate, under time pressure, on a phone",
  "No usage window, no territory limit, no carve-out for your own portfolio",
 ],
 "happening": "Festival media terms are among the most aggressive rights grabs in working photography, and they are accepted almost universally because they are presented at the moment of least leverage — at the gate, in a queue, with the job about to start. The result is a marketing archive built for free out of freelancers' work, resold to sponsors, with no credit. This is the M.A.R.K.E.T. guide's exposure problem with a contract stapled to it, and the difference is that here you are signing away the asset itself rather than just working cheap. The good news is that these terms are usually negotiable, because the person holding the clipboard has never been asked.",
 "check": "L.E.N.S. — “S” CHECK: “What exactly am I licensing, to whom, for how long?” Three answers before you tick. If you cannot state them, do not sign at the gate.",
 "darkTitle": "You Signed Away The Archive, Not The Weekend",
 "dark": "The cost is not this festival, it is the decade afterwards. A perpetual sublicensable license means the frame you shot at twenty-three can be sold to a drinks brand at thirty-three without a call, a credit or a fee, and you have no standing to object because you ticked a box in a queue. Shooters discover this years later when their own image turns up on a billboard for something they would never endorse. Ask for the form in advance, by email, before you travel. That one request — the most junior-sounding thing on this page — is the whole defense, because a term you negotiate on Tuesday is a term, and a term you meet at the gate is an ultimatum.",
 "move": "Request the media terms by email before you commit to the trip. Propose a limited license: twelve months, editorial and social only, credit required, no sublicensing to sponsors, and you keep everything else. Most will accept, because almost nobody asks.",
 "say": "Can you send the accreditation terms over before I book travel? I usually license twelve months editorial with credit rather than perpetual all-media — happy to work to that.",
 "truth": "Exposure has never once paid an invoice. The license is the deal, and the gate is the worst place on earth to read one.",
},
{
 "section": "TOOLS",
 "hook": "THE CONSENT PRACTICE",
 "archetype": "How Working Photographers Actually Do This",
 "clinical": "Consent Protocol / Ethical Capture Practice",
 "who": "For every shooter, from the phone in the crowd to the one with the laminate. None of this slows you down after the first weekend, and all of it is what separates a photographer people trust from one they warn each other about.",
 "scene": "The whole practice is four habits and they take about three seconds each. The reason to build them now is that the moment you need them — somebody upset, somebody's partner asking, somebody who saw themselves on an account — is not a moment when you want to be inventing a policy.",
 "tells": [
  "Ask before, not after — a raised camera and a look is often enough",
  "Say where it is going: personal, editorial, client, socials, with credit or not",
  "If they are impaired, in distress, or with kids: no frame, no exceptions",
  "If a no arrives later, delete it while they watch and tell them you have",
  "Hand over a card or a handle so people can reach you",
  "Never post a stranger's face with a caption that mocks them",
 ],
 "happening": "Consent practice is what makes the difference between a photographer who gets access and one who gets asked to leave, and it compounds: people who have been treated well introduce you, tip you off, and let you shoot things nobody else gets to shoot. It is also the cheapest professional insurance available, because almost every media dispute at a festival starts with somebody who was photographed without being asked and had no way to reach the person who did it. Being findable is half the practice. Deleting on request is the other half, and it costs you one frame out of two thousand.",
 "check": "L.E.N.S. — “N” CHECK: “If they asked me to delete this right now, would I do it without arguing?” If the answer is no, you are treating the file as more important than the person, and you will eventually be the story.",
 "darkTitle": "The Delete Is The Whole Reputation",
 "dark": "Deleting in front of somebody, immediately and without negotiation, is the single most reputationally valuable thing a festival photographer can do, and it is also the one most of them get wrong. The instinct is to explain — that it is a great shot, that you would not post it, that you shoot for the festival. Every word of that reads as a negotiation over whether their no counts, and it is remembered that way. Delete first. Say you have. Explain nothing. People talk to each other, and the photographers who become trusted in a scene are trusted for exactly this, not for their portfolio.",
 "move": "Build the four habits until they are automatic, and put your handle on a sticker on your camera strap so anybody can find you afterwards. Practise the delete — do it once, cheerfully, and notice it costs you nothing.",
 "say": "Mind if I grab one? It's for my own stuff, I'd tag you. — [later] Course, deleting it now, look — gone. All good.",
 "truth": "One deleted frame costs you nothing. The reputation for deleting without arguing is worth more than any shot you will take this weekend.",
},
{
 "section": "ACCOUNTABILITY",
 "hook": "WHERE THAT PHOTO LANDS",
 "archetype": "What You Owe The People In Your Frames",
 "clinical": "Publication Ethics / Downstream Harm Awareness",
 "who": "You, at home on the Tuesday, with two thousand frames and a deadline and no one watching what you select.",
 "scene": "There is a frame in there of somebody mid-breakdown at the edge of a crowd, and it is the best photograph you took all weekend. It says something true about the whole event. Nobody would ever know who they are except everyone who knows them, which at a festival of this size is probably four hundred people.",
 "tells": [
  "Would this person be fine with their employer, family or ex seeing this",
  "Are they identifiable to people who know them, even if not to strangers",
  "Are they in a medical, harm-reduction, welfare or crisis context",
  "Is anybody in the frame a minor, and is anybody outed by it",
  "Would you be comfortable sending it to them before you post it",
  "Is this frame about the festival, or about them specifically",
 ],
 "happening": "Selection is where the ethics actually live — the shutter is a reflex, the edit is a decision made with time and without pressure, and that is the moment you are accountable for. Festival crowds contain people who are not out, people whose employers do not know they are here, people in custody disputes, people in recovery, people who are somewhere they told someone else they were not. None of that is visible in the frame and all of it is downstream of your upload. You cannot check for every case, which is exactly why the general rules exist: no crisis contexts, no minors without a parent's yes, no identifiable faces in compromising states, and send it to them first when you are unsure.",
 "check": "L.E.N.S. — “E” CHECK: “Am I willing to send this to the person in it before it goes up?” If not, that reluctance is the answer, and you already know what it means.",
 "darkTitle": "The Best Frame Is Usually The One To Kill",
 "dark": "The photographs that do the most damage are almost never the careless ones — they are the excellent ones, because those are the ones that travel. A brilliant frame of somebody at their worst gets shared precisely as far as it is good, and the person in it spends a year meeting it. If you shoot festivals for long enough you will take a frame that is genuinely the best work of your career and should never be published, and what you do with that frame is the whole of your professional character. Nobody will ever know you killed it. That is rather the point.",
 "move": "Make the edit a separate session with the rules in front of you, not a scroll at 1am. When a frame is strong and you are unsure, send it to the subject and let them decide — most say yes, and the ones who say no are the ones that would have been the problem.",
 "say": "Hey — took this of you on Saturday, think it's a great shot. Only posting it if you're happy, no hard feelings either way.",
 "truth": "Your best photograph is not automatically a photograph you are allowed to publish. The edit is where you find out what kind of photographer you are.",
},
]
