# -*- coding: utf-8 -*-
"""R.O.O.T.S. scenarios."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "I'VE ALWAYS WANTED TO",
 "archetype": "The Collector / Fetishization As An Approach",
 "clinical": "Racial Fetishization / Objectification as Opening Move",
 "who": "Intense, immediate, and full of enthusiasm about a version of you he assembled before you spoke. Compliments a category. Has a type and tells you so as though it were a gift he is handing over.",
 "scene": "He has been talking for four minutes and every single thing he has said has been about how you look, in language that keeps reaching for somewhere — a country, a continent, a word he clearly thinks is a compliment. He asks where you are really from. He tells you he has always wanted to be with someone like you. There is no point in this conversation where you have been a person with a name.",
 "tells": [
  "Compliments a category rather than anything you chose, said, or made",
  "“Where are you really from”, and a guess afterwards",
  "Announces a preference for people like you as though it flatters you",
  "Reaches for your hair, your skin, or a photo within minutes",
  "Knows nothing about you and is nonetheless certain about you",
  "Gets cold fast when you are ordinary rather than the thing he pictured",
 ],
 "happening": "Fetishization does the same work as any other idealization in this book: it replaces a person with a symbol, and symbols are not allowed boundaries. It is also unusually efficient as an opening move, because it arrives disguised as enthusiastic admiration, which makes declining it look like you are the one being difficult. The practical tell is not the subject matter, it is the direction of attention — someone interested in you asks questions and updates on the answers; someone interested in a category delivers conclusions and does not update at all, because your actual self is not the point and is in fact slightly in the way.",
 "check": "R.O.O.T.S. — “T” CHECK: “Has he asked me anything, or only told me things?” Interest asks. Collecting announces.",
 "darkTitle": "Being A Type Means Being Interchangeable",
 "dark": "The thing worth understanding early is what fetishization does to the aftermath. Somebody attracted to a category rather than a person has, by definition, no particular attachment to you — which means the ordinary brakes that come with actually knowing someone are not installed. It also gives him a ready explanation for anything that goes wrong: a misunderstanding, a cultural thing, you took it the wrong way. And if you raise it afterwards in a scene that prides itself on openness, you will frequently be met with the suggestion that he was just really into you and you have made it about race. That pre-built defense is part of why this approach gets used. None of it means you have to litigate it. You can simply leave a conversation that has never once been about you.",
 "move": "Test it once, cheaply: give him a real detail about yourself that has nothing to do with how you look, and watch whether he picks it up or steers back. Then leave, without a verdict and without a debate — you are not obliged to prove it to him or to anyone standing nearby.",
 "say": "I'm going to find my people — have a good one. — [if pressed] Not interested, mate. That's the whole answer.",
 "truth": "Someone who wanted you would ask you something. You are allowed to walk away from an audition you never entered.",
},
{
 "section": "CONDITION",
 "hook": "CAN I JUST TOUCH IT",
 "archetype": "The Reacher / Your Body As Public Property",
 "clinical": "Non-Consensual Contact / Bodily Autonomy Violation",
 "who": "Frequently a stranger, frequently delighted, frequently already reaching while asking — which means the question was decorative. Often drunk, often a woman, often genuinely baffled that this lands badly.",
 "scene": "Her hand is already in your hair. She is saying it is amazing and asking how you get it like that and whether it is all yours, and three people are watching and smiling, and the entire social weight of this moment is arranged so that the rude person in it would be you. You have about two seconds and the good options all cost something.",
 "tells": [
  "Asks while already reaching, or does not ask at all",
  "Treats your hair, skin, or features as a topic for public discussion",
  "Does it in front of people, so objecting has an audience cost",
  "“Is it real”, “how do you get it like that”, “I've never touched”",
  "Wants a photo with you rather than of the moment",
  "Reacts to a no as though you have been unkind to them",
 ],
 "happening": "Unsolicited touching is a boundary violation regardless of intent, and the specific version aimed at Black women's hair is documented well enough to have prompted its own body of workplace and school policy. The mechanism at a festival is the environment: everyone is close, warm, uninhibited and touching each other constantly, which supplies a ready-made explanation for the contact and makes objecting feel like importing outside-world rules into a space that is supposed to be free of them. That framing is the problem. A culture of physical affection is consent-based or it is not a culture of affection, it is just a culture where some people get touched.",
 "check": "R.O.O.T.S. — “O” CHECK: “Did the question stop the hand?” If the hand kept moving, it was not a question, and you owe it nothing.",
 "darkTitle": "The Cost Is The Accumulation",
 "dark": "Any one of these is small. The reason it belongs in a safety guide is what a weekend of them does: by Sunday you have absorbed forty small interactions in which your body was treated as a shared object and you were required to be gracious about each one, and that steady grinding down of your standing to say no is precisely the ground condition every predator in this book is looking for. Someone who has watched you accept unwanted contact all weekend, smiling, has learned something about you that they should not have been allowed to learn. Practising the flat no on the small stuff is not pettiness. It is keeping the muscle available for the night you need it.",
 "move": "Block with your body rather than your words — step back and put a hand up before you speak. Then a flat, short sentence with no apology and no explanation, and move on immediately so there is no space for a discussion.",
 "say": "No — don't touch my hair. — [flat, no smile, then turn away] Anyway. Have you seen where the water point is?",
 "truth": "You are not a texture. A space that needs you to be gracious about being handled is not actually free for you.",
},
{
 "section": "CONTROL",
 "hook": "THEY CALLED SECURITY ON YOU",
 "archetype": "When The Escalation Route Points At You",
 "clinical": "Differential Enforcement / Weaponized Reporting",
 "who": "Someone in a dispute with you who has correctly worked out that involving staff is a move that costs them nothing and costs you a great deal. Sometimes deliberate. Sometimes just a person who reached for the phone without thinking about who would be believed.",
 "scene": "There was an argument at your camp. It was nothing. Now there are two radios and a torch and the questions are coming at you rather than at the person who started it, and the specific thing you notice, standing there, is that everybody is being perfectly polite and the outcome has somehow already been decided before anybody asked you anything.",
 "tells": [
  "Security arrives asking you the questions rather than asking everyone",
  "The other party is treated as the reporter rather than as a participant",
  "Your tone becomes the subject rather than what happened",
  "Someone reaches for staff or police unusually fast over something small",
  "You are asked to leave to resolve it while the other party stays",
  "You are, or are close to, the only one of you in the immediate area",
 ],
 "happening": "This book's standard advice is to escalate — tell a ranger, tell security, involve staff. That advice assumes the escalation route is neutral, and for a lot of readers it is not: the same call produces different outcomes depending on who is standing where, and a police involvement that resolves one person's evening can be a materially dangerous event for another. Saying so is not cynicism about festival staff, most of whom are decent and trying. It is the difference between a safety plan built for an average reader and one built for you. A plan that ignores this is not neutral — it is a plan that works for other people.",
 "check": "R.O.O.T.S. — “O” CHECK: “If this escalates to staff, who does that help?” Ask it before the moment, because in the moment there is no time.",
 "darkTitle": "Build A Ladder That Stops Where You Need It To",
 "dark": "The practical version of this is not avoid all staff — it is have more rungs before that one, and know which specific humans they are. Camp leads, welfare, the harm-reduction tent, an artist liaison, a named accessibility or community lead: these are escalation routes that are generally safer and almost always more effective than a radio call, and they exist at nearly every festival. The other half is witnesses. The single biggest change in how one of these encounters goes is whether two other people are standing there, and the second biggest is whether somebody is recording. Neither requires a confrontation. Both require having thought about it before the torch is pointing at you, which is the entire reason this page exists.",
 "move": "On arrival, get two names that are not security — welfare and a camp or community lead. In any dispute, get a witness beside you before it escalates, stay still and boring, and write it down immediately afterwards with the time and the names. Do not resolve it alone in the dark.",
 "say": "I'm happy to talk about this with welfare present. — [to a friend] Stand here with me a minute, would you.",
 "truth": "Escalation is a tool, not a reflex. Know which rung is safe for you before you need to climb.",
},
{
 "section": "TOOLS",
 "hook": "THE LADDER AND THE ANCHOR",
 "archetype": "Building The Plan That Actually Fits You",
 "clinical": "Personal Risk Mapping / Escalation Planning",
 "who": "For anyone whose safety plan cannot be copied straight out of a generic guide — which, at some events, is most of the people reading this one.",
 "scene": "Thursday afternoon, before anything has happened, while the site is calm and the people you would need are all findable and not busy. Twenty minutes now buys you the thing that is impossible to assemble at two in the morning with a torch in your face, which is a set of names and a route you already trust.",
 "tells": [
  "Two named non-security contacts: welfare, and a camp or community lead",
  "Two people on site who will physically stand next to you on request",
  "One person off-site who expects a check-in and knows where you are",
  "Your own transport, or a lift that is not in anybody else's control",
  "A note app for time, place, names — written the same hour, not the next day",
  "The affinity camp or crew, found on day one rather than on the bad night",
 ],
 "happening": "Everything in this guide is cheaper to arrange in advance than to invent under pressure, and the reason is the same one that runs through this whole book: the moment is designed to be one where you cannot think. A prepared ladder converts a judgment call into a lookup. The witness rule does the most work of anything on that list — accounts of these encounters diverge sharply depending on whether anyone else was present, and a second person standing beside you changes both what happens and what can be said about it afterwards. None of this is about expecting trouble. It is the same logic as knowing where the medical tent is.",
 "check": "R.O.O.T.S. — “R” CHECK: “Can I name my two non-security contacts right now?” If not, that is the twenty minutes, and it is best spent on Thursday.",
 "darkTitle": "Write It The Same Hour",
 "dark": "Documentation is the part people skip and the part that matters most, because these situations are decided later by whose account is more specific. A dated note written within the hour — time, location, names, what was actually said, who else was there — outperforms any amount of remembered detail weeks on, and it does not require anyone to find you credible in the moment. Send it to someone off-site so it exists outside this weekend and outside your own phone. It takes ninety seconds. Do it even when you are fairly sure nothing will come of it, because the cases where something does come of it are exactly the ones where you did not expect it to.",
 "move": "Get your two non-security names in the first hour on site. Agree the stand-next-to-me signal with two friends. Write anything that happens down the same hour and send it off-site. Keep your own way home.",
 "say": "Who's the welfare lead this year, and how do I reach them directly? — If I text you a pin, just come stand next to me, you don't have to say anything.",
 "truth": "A plan built for the average reader is not built for you. Build yours on Thursday, out of real names.",
},
{
 "section": "COMMUNITY",
 "hook": "FINDING THE OTHERS",
 "archetype": "Affinity Space, And The Festivals That Get It Right",
 "clinical": "Affinity Community / Protective Social Infrastructure",
 "who": "The camp with the sound system and the good food that has been coming for eleven years. The crew who clocked you at the gate and nodded. The promoters and collectives who built something deliberately and did the work of making it real.",
 "scene": "Saturday, and you have spent two days being the only one in every frame, doing the low-level arithmetic that costs more energy than anyone who does not do it understands. Then you walk past a camp and three people look up and one of them says come and eat something, and you feel your shoulders drop about two inches, and you had not registered they were up.",
 "tells": [
  "Real: you are not explained, introduced as a demographic, or asked to represent",
  "Real: you can be ordinary, annoying, or quiet with no change in standing",
  "Real: people share practical information without ceremony — who is sound, who is not",
  "Performative: your presence gets mentioned to other people as a credit",
  "Performative: the event's diversity is discussed with you rather than built",
  "Performative: you are the only one there and nobody has ever asked why",
 ],
 "happening": "Affinity space is protective for reasons that are entirely practical rather than sentimental: it replaces hypervisibility with ordinariness, it supplies witnesses who do not need the situation explained to them, and it is where the informal warnings circulate — which promoter is sound, which crew to avoid, what happened last year. Every mechanism in this guide works better on someone isolated, and the fetishizer, the reacher and the weaponized report all operate most freely on a person with nobody standing near them. This is also the page where the scene deserves credit: there are collectives and festivals doing this properly, and they are findable.",
 "check": "R.O.O.T.S. — “S” CHECK: “Have I found my people here, or am I still doing this alone?” Day one. Not the night it goes wrong.",
 "darkTitle": "Shoulders Down Is Data",
 "dark": "Worth naming plainly: the constant low-level vigilance has a cost, and because it is continuous it becomes invisible to the person paying it. You will not notice you have been braced all weekend until you stop, and the stopping is what tells you. That fatigue is not fragility and it is not you being difficult — it is the predictable result of running a background process everyone around you has switched off. It also degrades judgment, the same way sensory load and sleep loss do elsewhere in this book, which means finding the people who let you put it down is not a comfort measure. It is a safety measure, and it belongs on day one alongside knowing where medical is.",
 "move": "Find the camp, the crew, or the collective on day one, before you need anything. Ask the regulars what they know — the informal information network is the best safety infrastructure at any festival. And go back to the events that actually built something, because they are the ones that respond to being supported.",
 "say": "First time at this one — who's sound round here, and is there anything I should know? — Come find us at the camp with the blue flag, we're cooking Saturday.",
 "truth": "You came for the music, not to be a subject of interest. Find the people who let you be ordinary, on day one.",
},
]
