# -*- coding: utf-8 -*-
"""S.O.B.E.R. scenarios."""

SCENARIOS = [
{
 "section": "CAPTURE",
 "hook": "ONE WON'T HURT YOU",
 "archetype": "The Convincer / Your Sobriety As Their Problem",
 "clinical": "Peer Coercion / Social Proof Pressure",
 "who": "Usually not malicious. Frequently drunk. Genuinely believes he is being welcoming, and is also, underneath it, uncomfortable that somebody nearby is not doing what he is doing. Persistent in a way he would not be about anything else.",
 "scene": "Fourth time tonight. He is holding it out again, doing the thing where he waggles it slightly, saying he is not trying to pressure you but it is a festival, and asking — warmly, in front of five people — what actually happened, like your sobriety is a story he is owed and the story will settle whether your no is reasonable.",
 "tells": [
  "Asks more than once after a clear answer",
  "Wants the reason, and frames your reason as the thing that would justify the no",
  "Does it in front of an audience, so declining has a social cost",
  "Reframes your boundary as a mood you could be talked out of",
  "“Just this once”, “it's a festival”, “you're no fun like this”",
  "Gets cold or wounded when the fourth no lands",
 ],
 "happening": "The pressure is usually about him rather than about you — a person drinking heavily next to someone who is not is being handed an unwelcome mirror, and the fastest way to put the mirror down is to get you to join. That does not make it harmless. Repeated asking is how boundaries get worn rather than broken, and the reason-demand is the actual move: once you are explaining, you are in a negotiation, and negotiations have outcomes. You are not in a negotiation. The most effective response is also the most boring one, which is the same three words, at the same volume, indefinitely, with no new information added.",
 "check": "S.O.B.E.R. — “S” CHECK: “Am I explaining?” The moment you start supplying reasons, you have accepted that your no needs approving. It does not.",
 "darkTitle": "Some Of Them Know Exactly What You Are",
 "dark": "Most of the people doing this are just drunk. A few are not, and the difference shows in what they do with the information once you give it. Someone who learns you are in recovery and keeps pushing is not being socially clumsy — they have been told there is a specific cost to you and have decided it is worth it, and a person who wants somebody impaired has just found the one person here whose impairment would come with built-in silence. This is why the reason is worth keeping to yourself in a crowd. Not shame — information discipline. Your recovery is not a secret; it is also not something to hand to a stranger who has already ignored three noes.",
 "move": "Repeat the same three words with no escalation and no new content, and move your body — turn a shoulder, go get water, join a different conversation. Broken-record plus physical exit ends it faster than any argument, because there is nothing to push against.",
 "say": "I'm good. — I'm good. — I'm good, mate. Anyway, has anyone seen Priya?",
 "truth": "Your no does not improve with an explanation attached. “I'm good” is already the strongest version of it.",
},
{
 "section": "CAPTURE",
 "hook": "I MADE YOU ONE",
 "archetype": "The Handed Drink / Why This Rule Is Not Paranoia",
 "clinical": "Drink Spiking / Non-Consensual Administration",
 "who": "Anyone holding a cup you did not watch being filled. Usually a friend being kind. Occasionally not — and the second category is why the rule has to apply to the first, because you cannot tell them apart by looking.",
 "scene": "Someone hands you a lemonade. They are being nice, they know you do not drink, they went and got it specially. Refusing it feels ungrateful and slightly insulting and like you are accusing a friend of something. It also costs nothing, and the alternative — a drink you cannot vouch for, in a body with no tolerance, in front of people who will later say you seemed fine — costs a great deal.",
 "tells": [
  "A drink arriving already poured, that you did not see made",
  "Insistence when you set it down or ask for a sealed one",
  "Attention to whether and how much you are drinking it",
  "“It's only soft” as an argument for skipping the rule",
  "Someone treating the rule as an accusation rather than a policy",
  "Any drink left unattended, including yours, including for a minute",
 ],
 "happening": "The most common drink adulterant is alcohol added to something someone believes is soft, which matters enormously here: for a sober or in-recovery person that is not a lesser version of spiking, it is the specific harm. Zero tolerance means a small dose lands hard, and the aftermath is not only physical — it can register internally as a relapse, with all the shame that carries, even though nothing about it was chosen. The rule is the same one this whole book gives everyone: you pour it, you watch it poured, or you carry it sealed. The difference is that for you the failure mode includes losing your sense of your own recovery.",
 "check": "S.O.B.E.R. — “O” CHECK: “Did I watch this being made, or open it myself?” If not, it is not a drink, it is an unknown.",
 "darkTitle": "When It Registers As A Relapse",
 "dark": "Here is the part worth having read in advance, because it matters in the hour it happens: if you are dosed without knowing, that is not a relapse. It is an assault. Your body may not distinguish, your recovery community's language may not distinguish, and at four in the morning you will absolutely not distinguish — which is exactly why a person who wanted you compliant and quiet would choose this method. The shame does the silencing for them. Decide now, while it is hypothetical: if it happens, the first call is to somebody in your recovery network and the second is to medical, and neither of those calls is a confession. Say it out loud once so the sober version of you has already made the ruling.",
 "move": "Carry your own, sealed, and open it yourself. Decline anything handed to you already poured, cheerfully and as a blanket policy rather than as a judgment of the person offering. If you set a drink down, it is finished.",
 "say": "Ah, cheers — I've got a weird rule where I only drink stuff I've opened myself, nothing personal. I'll grab one with you though.",
 "truth": "Being dosed is not drinking. Decide that now, in daylight, so you are not deciding it at four in the morning.",
},
{
 "section": "CONDITION",
 "hook": "YOU'RE THE ONE WHO REMEMBERS",
 "archetype": "The Designated Adult / Care Assigned Rather Than Chosen",
 "clinical": "Role Assignment / Caregiver Burden",
 "who": "The whole group, gradually and without a conversation. Because you are the one who is sober, you become the one with the keys, the map, the phone battery, the plan, the medical decisions, and everybody's emergency.",
 "scene": "It is two in the morning and you are walking a stranger to medical because you are the only one upright enough to do it. This is the third night running. You came here for the music and you have seen about forty minutes of it, and somebody said earlier, as a compliment, that it is so good having you around because you always know what to do.",
 "tells": [
  "You hold the keys, the cash, the phones, the plan — by default, never by agreement",
  "Your sobriety is described as a resource the group has",
  "You have not seen the sets you came for",
  "Other people's medical decisions keep landing on you",
  "Nobody has asked whether you want this role",
  "Resenting it makes you feel like a bad friend, so you do not mention it",
 ],
 "happening": "Care work assigned by default rather than agreement is a well-documented route to burnout, and the festival version is unusually total: you are the group's driver, medic, treasurer, and institutional memory simultaneously, at exactly the time of year you came to enjoy yourself. It matters more than it sounds. Resentment plus exhaustion plus not having had any of the thing you came for is a genuinely recognized relapse-risk combination, and it builds quietly because the role arrives as a compliment. Choosing to look after your people is one of the good things about being the sober one. Being silently conscripted is not the same act.",
 "check": "S.O.B.E.R. — “B” CHECK: “Did I agree to this role, or was it assigned to me because I'm the one who'll remember?” Those produce the same behaviour and completely different costs.",
 "darkTitle": "Resentment Is A Relapse Risk, Not A Character Flaw",
 "dark": "The dangerous sequence is specific and it is worth being able to see coming: you do the caretaking, you miss the festival, you start resenting people you love, you feel guilty about the resentment because they are your friends and you chose this, and the guilt stops you saying any of it out loud. Depleted, resentful, isolated inside a group, and unable to name it — that is the state, and in recovery terms it is a familiar and serious one. Nobody engineered it. It assembled itself out of everyone's good intentions and the fact that you are reliable. The fix is a conversation on Tuesday, not heroism on Saturday.",
 "move": "Rotate it explicitly before the event — a named driver, a named phone-holder, a named person on duty each night, sober or not. Then take the sets you came for and say so in advance so it is a plan rather than an abandonment.",
 "say": "I'm not on duty tonight — I'm watching the whole set, phone on if it's an emergency. Who's got the keys? Let's actually rota this.",
 "truth": "Being sober makes you capable of holding everyone. It does not make you responsible for it. Those are different sentences.",
},
{
 "section": "CONTROL",
 "hook": "NOBODY NEEDS TO KNOW ABOUT THIS",
 "archetype": "The Engineered Slip / Relapse As Leverage",
 "clinical": "Induced Relapse / Shame-Based Silencing",
 "who": "Someone who learned what your sobriety means to you and filed it. Manufactures the slip, or simply waits for one, and then becomes the only person who knows about it — which is the actual objective.",
 "scene": "It happened. However it happened, it happened, and he was there, and now he is being extraordinarily kind about it. He says it stays between you. He says he understands, no judgment, everyone slips. He says it about four times over the next two days, in a way that is comforting the first time and something else by the fourth.",
 "tells": [
  "Present for the slip, and unusually relaxed about it",
  "Immediately frames it as a secret the two of you now share",
  "Repeats the reassurance more often than reassurance requires",
  "Discourages you from telling your sponsor, your partner, your people",
  "Your recovery network is described as judgmental or as not understanding festivals",
  "Small asks start arriving, and declining them feels newly complicated",
 ],
 "happening": "A secret held by one other person is leverage whether or not anyone ever names it, and shame is the most reliable silencer there is because the person being controlled does the work themselves. This is why isolation from your recovery network is the tell to watch rather than any explicit threat — the threat is never made, it does not need to be. Coercive control research finds this shape consistently: cut the person off from the relationships that would give them a competing account of themselves, then be the only one who knows the worst thing. What makes recovery a target is simply that the worst thing is already pre-loaded and everyone knows how much it costs you.",
 "check": "S.O.B.E.R. — “R” CHECK: “Is there something about me only one person here knows?” That is not intimacy. That is a holding.",
 "darkTitle": "Disclosure Is How You Disarm It",
 "dark": "The single move that ends this is the one that feels impossible: tell someone else. The leverage exists only while the information is scarce, and it evaporates the moment a second person knows — not because the slip stops mattering, but because he is no longer the only one holding it. Recovery communities are unusually good at exactly this; a slip disclosed is an ordinary event with a known next step, and everyone in your network has either had one or sat with somebody who did. The person telling you they will keep it between you is not protecting you from judgment. They are protecting the scarcity. Call your sponsor tonight, not when you feel ready — feeling ready is the thing the shame is preventing.",
 "move": "Break the exclusivity immediately: tell one person in your recovery network today, before the story gets any older. Then treat the slip as a practical event with a next step — that is all it is — and put distance between you and whoever wanted to hold it.",
 "say": "I'm telling my sponsor, so it's not staying between us — that's not how I do this. — [to your person] It happened Saturday. I'm okay. I wanted you to know before it got old.",
 "truth": "A secret with one keeper is a lever. Hand it to a second person and it stops being one.",
},
{
 "section": "TOOLS",
 "hook": "YOUR FESTIVAL SOBER PLAN",
 "archetype": "Twenty Minutes That Hold All Weekend",
 "clinical": "Relapse Prevention Planning / Preventive Structure",
 "who": "For anyone sober, in recovery, California sober, taking a break, or just not drinking this weekend. Made in advance, in a calm room, by a version of you who is not tired, lonely, or three days into a field.",
 "scene": "Tuesday, twenty minutes, a notes app. Everything that will be hard on Saturday night is currently something you can solve in one line. On Saturday night it will not be, because the whole difficulty of Saturday night is that it takes away the part of you that makes plans.",
 "tells": [
  "Your line, decided now: what you drink, what you never accept, what ends the night",
  "The hour you leave — an actual time, set before you arrive",
  "Two people on site who know you are sober and will not make it a thing",
  "One person off-site who picks up at any hour, tested before you travel",
  "The sober meetings on site, located Thursday — the Rats, the Phellowship, the sober camp",
  "What you do if you slip: who you call, in what order. Written down.",
 ],
 "happening": "Relapse prevention planning is the most evidence-backed piece of self-management in recovery, and its whole logic is pre-commitment — a decision made in a regulated state, handed to a depleted one, so the hard moment only requires following rather than deciding. A festival concentrates every known risk factor into seventy-two hours: sleep loss, crowds, availability, loneliness inside a group, and the specific ache of watching people you love have an experience you have chosen not to have. None of that means you should not go. It means you go with a plan, the way you would go anywhere else that mattered.",
 "check": "S.O.B.E.R. — “E” CHECK: “Do I know what time I'm leaving tonight, and who I call if it gets hard?” Two answers, decided before you arrive.",
 "darkTitle": "Write The Slip Plan While You Are Fine",
 "dark": "Write the what-if-I-slip page now, while it is theoretical and slightly embarrassing to be writing. The reason is simple and it is the thing that kills people: after a slip, shame closes the exact channels you need, and the plan you did not write is not a plan you will invent at four in the morning while believing you are a fraud. Two names and an order of calls, written down on a Tuesday by someone who was fine, is a message from a version of you that your Saturday self will not be able to argue with. Nobody who writes that page is planning to use it. Everyone who needed it was glad it existed.",
 "move": "Write the six lines. Send the off-site person a message before you travel so they know they are on. Find the sober meeting on Thursday, before you need it — walking in on Saturday when it is hard is a much bigger ask than walking in on Thursday when it is not.",
 "say": "I'm out by one tonight, that's fixed. — You're my call this weekend if it gets hard, is that alright? I probably won't need it, I just want it arranged.",
 "truth": "The plan is not a prediction. It is Tuesday-you leaving instructions for Saturday-you, who will not be able to work it out alone.",
},
{
 "section": "COMMUNITY",
 "hook": "THERE ARE MORE OF US THAN YOU THINK",
 "archetype": "The Sober Scene Inside The Scene",
 "clinical": "Recovery Community / Peer Support Access",
 "who": "The Wharf Rats with the yellow balloons. The Phellowship. The sober camp with the coffee urn. The Zendo volunteers. The ones who have been coming for thirty years and have not had a drink for twenty-five of them.",
 "scene": "You assume you are the only one. You are not remotely the only one — there is a meeting on this site, probably daily, probably signposted with a yellow balloon or a hand-lettered board, and the people at it have been navigating exactly this weekend for longer than you have been alive. Most of them found it the same way, which is late, having assumed the same thing you are assuming.",
 "tells": [
  "Yellow balloons at the back of the crowd — that is the Wharf Rats, and it is an invitation",
  "A meeting board, a sober camp, a coffee urn where a bar would be",
  "Harm reduction volunteers, a lot of whom are sober themselves",
  "People who clock your soda and say nothing, which is the good sign",
  "Real: nobody asks for your story as the price of entry",
  "Real: you can go, say nothing, drink the coffee, and leave",
 ],
 "happening": "Sober infrastructure inside festival culture is decades old and largely invisible unless you are looking for it — the Wharf Rats go back to the early eighties, the Phellowship not much later, and most large festivals now have something. The reason it matters more than any individual tactic in this guide is that isolation is the common factor underneath every pattern here: the convincer works on someone with no one to turn to, the assigned care role works on someone who does not know other sober people are around, and the engineered slip works on someone cut off from their network. Finding these people on Thursday removes the precondition for all three at once.",
 "check": "S.O.B.E.R. — “B” CHECK: “Do I know where the sober meeting is on this site — today, not hypothetically?” Find it before you need it. That is the whole page.",
 "darkTitle": "Isolation Is The Shared Precondition",
 "dark": "Go back through this guide and the same thing is underneath every page. The convincer is only effective on somebody standing alone. The care role only becomes total when nobody else here is sober. The slip becomes leverage only when one person is the only one who knows. Every single mechanism requires you to be the exception in the room — which is exactly the belief you arrived with, and exactly the belief that a hand-lettered board at the back of the field disproves in about ninety seconds. Find them Thursday. Not because you are fragile, but because being findable is what makes the rest of this book mostly theoretical for you.",
 "move": "Locate the meeting, the sober camp, or the balloons in your first few hours on site, and go once when things are fine. Tell two people in your group you are sober so it is ordinary rather than a revelation at a bad moment. Then have the weekend you came for.",
 "say": "Any sober meeting on site this year? — Just so you know, I don't drink, it's not a whole thing, I'm just easier to find at the coffee than the bar.",
 "truth": "You are not the only sober person at this festival. You are the only one who has not found the others yet, and that takes about ten minutes.",
},
]
