#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the Festie Bible's reusable per-guide video assets: a cover, an
acronym badge, and two content-card templates (tells / check), for all 21
guides. Same pipeline as scripts/covers/compose-guide-jacket.py -- Pillow,
the repo's own self-hosted fonts and the real trimmed logo, nothing fetched
or generated by an external image model (which mangles exact text like an
acronym or a URL; this needs both to be exact).

Source of truth for text/color: content/festie-bible-data.json (acronym,
role, edition) and each guide's live accent color, pulled from the rendered
page the same way scripts/festie-teleprompter-scenes-build.py does, not
invented.

Outputs, per guide, into content/festie-teleprompter/images/<slug>/:
  cover.png       1080x1920  video cover -- logo, acronym, role, URL, with
                              the bottom third left genuinely empty for the
                              scenario title to be added per video
  badge.png       1080x1080  standalone acronym mark for mid-video inserts
  tells-card.png  1080x1920  "watch for these signs" template, blank body
  check-card.png  1080x1920  "run the check" template, blank body

Re-run after any accent-color or guide-roster change so the assets stay in
sync with the live book.
"""
import json
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "content/festie-bible-data.json"
PAGE = ROOT / "library/festival/index.html"
LOGO = ROOT / "design/brand/logo-noble-father.png"
FONTS = ROOT / "tools/fonts"
OUT = ROOT / "content/festie-teleprompter/images"
SITE_URL = "www.noblefathercreations.com/festival"

INK = (20, 16, 25)          # --ink, the house ground
BONE = (236, 228, 214)      # --bone
BRASS = (201, 163, 91)      # --brass
BRASS_BRIGHT = (232, 200, 121)
MUTED = (138, 128, 113)     # --muted

FRAUNCES = FONTS / "fraunces/Fraunces[SOFT,WONK,opsz,wght].ttf"
HANKEN = FONTS / "hankengrotesk/HankenGrotesk[wght].ttf"
MONO_B = FONTS / "spacemono/SpaceMono-Bold.ttf"
MONO_R = FONTS / "spacemono/SpaceMono-Regular.ttf"


def font(path, size, variation=None):
    f = ImageFont.truetype(str(path), size)
    if variation:
        f.set_variation_by_name(variation)
    return f


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def text_w(draw, text, f, tracking=0):
    if tracking == 0:
        return draw.textlength(text, font=f)
    return sum(draw.textlength(c, font=f) + tracking for c in text) - tracking


def draw_tracked(draw, xy, text, f, fill, tracking=0, anchor_center=None):
    """Space out letters by `tracking` px, optionally centered at
    anchor_center (an x coordinate) rather than starting at xy[0]."""
    x, y = xy
    if anchor_center is not None:
        x = anchor_center - text_w(draw, text, f, tracking) / 2
    for ch in text:
        draw.text((x, y), ch, font=f, fill=fill)
        x += draw.textlength(ch, font=f) + tracking


def fit_font(draw, text, path, variation, start, max_width, min_size=40):
    size = start
    while size > min_size:
        f = font(path, size, variation)
        if draw.textlength(text, font=f) <= max_width:
            return f, size
        size -= 4
    return font(path, min_size, variation), min_size


def wrap_to_fit(draw, text, path, variation, start, max_width, max_lines, min_size=48):
    """Try shrinking first; if it still doesn't fit on one line at a
    readable size, wrap on spaces/periods up to max_lines."""
    f, size = fit_font(draw, text, path, variation, start, max_width, min_size=start // 2)
    if draw.textlength(text, font=f) <= max_width or max_lines == 1:
        return [text], f, size
    # wrap at internal spaces (acronyms like "G.R.O.V.E." have none, so this
    # mainly helps multi-word roles if ever used at this size)
    words = text.split(" ")
    lines, cur = [], ""
    for w in words:
        trial = (cur + " " + w).strip()
        if draw.textlength(trial, font=font(path, size, variation)) <= max_width:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    lines = lines[:max_lines]
    return lines, font(path, size, variation), size


def load_guides():
    d = json.loads(DATA.read_text(encoding="utf-8"))
    page = PAGE.read_text(encoding="utf-8")
    accents = dict(re.findall(r"\.(fb-g-[a-z]+)\{ --acc:(#[0-9A-Fa-f]{6});", page))
    out = []
    for g in d["guides"]:
        out.append({
            "slug": g["slug"], "acronym": g["acronym"], "role": g["role"],
            "edition": g["edition"], "accent": hex_to_rgb(accents[g["acronymClass"]]),
        })
    return out


def logo_layer(height):
    logo = Image.open(LOGO).convert("RGBA")
    w = int(height * logo.width / logo.height)
    return logo.resize((w, height), Image.LANCZOS)


def paste_center(base, layer, cx, y):
    base.alpha_composite(layer, (int(cx - layer.width / 2), int(y)))


def base_canvas(w, h, accent, border=0):
    img = Image.new("RGBA", (w, h), (*INK, 255))
    if border:
        d = ImageDraw.Draw(img)
        d.rectangle([border // 2, border // 2, w - border // 2 - 1, h - border // 2 - 1],
                    outline=(*accent, 255), width=border)
    return img


def label_row(draw, text, cx, y, size=30, color=BRASS, tracking=6):
    f = font(MONO_B, size)
    draw_tracked(draw, (0, y), text, f, (*color, 255), tracking=tracking, anchor_center=cx)


def url_row(draw, cx, y, size=26, color=MUTED):
    f = font(MONO_R, size)
    w = draw.textlength(SITE_URL, font=f)
    draw.text((cx - w / 2, y), SITE_URL, font=f, fill=(*color, 255))


def build_cover(g):
    W, H = 1080, 1920
    img = base_canvas(W, H, g["accent"])
    d = ImageDraw.Draw(img)
    cx = W // 2

    label_row(d, "THE FESTIE BIBLE", cx, 118)

    mark = logo_layer(300)
    paste_center(img, mark, cx, 210)

    y = 560
    d.line([(cx - 90, y), (cx + 90, y)], fill=(*g["accent"], 255), width=3)

    lines, f, size = wrap_to_fit(d, g["acronym"], FRAUNCES, "Black", 172, W - 140, 2)
    y = 660
    for line in lines:
        w = d.textlength(line, font=f)
        d.text((cx - w / 2, y), line, font=f, fill=(*g["accent"], 255))
        y += int(size * 1.05)

    y += 30
    rf, rsize = fit_font(d, g["role"], HANKEN, "SemiBold", 46, W - 160, min_size=28)
    draw_tracked(d, (0, y), g["role"], rf, (*BONE, 255), tracking=3, anchor_center=cx)

    y += int(rsize * 1.9)
    url_row(d, cx, y)

    # 1460-1920 stays untouched -- the scenario title goes here per video,
    # and it's the platform-UI safe zone on Reels/TikTok/Shorts either way
    return img.convert("RGB")


def build_badge(g):
    W = H = 1080
    img = base_canvas(W, H, g["accent"], border=10)
    d = ImageDraw.Draw(img)
    cx = W // 2

    lines, f, size = wrap_to_fit(d, g["acronym"], FRAUNCES, "Black", 176, W - 160, 2)
    total_h = int(size * 1.05) * len(lines)
    y = (H - total_h) // 2 - 40
    for line in lines:
        w = d.textlength(line, font=f)
        d.text((cx - w / 2, y), line, font=f, fill=(*g["accent"], 255))
        y += int(size * 1.05)

    y += 26
    rf, rsize = fit_font(d, g["role"], HANKEN, "SemiBold", 34, W - 200, min_size=22)
    draw_tracked(d, (0, y), g["role"], rf, (*BONE, 255), tracking=3, anchor_center=cx)

    mark = logo_layer(120)
    paste_center(img, mark, cx, H - 230)
    url_row(d, cx, H - 96, size=22)

    return img.convert("RGB")


def build_content_card(g, kind):
    """kind: 'tells' or 'check' -- same frame, different header and body
    treatment. Body area is left genuinely blank (faint guide lines only)
    for that specific scenario's text, added per video -- the frame itself
    is what's reusable across every scenario in this guide."""
    W, H = 1080, 1920
    img = base_canvas(W, H, g["accent"], border=8)
    d = ImageDraw.Draw(img)
    cx = W // 2

    header = "WATCH FOR THESE SIGNS" if kind == "tells" else "RUN THE CHECK"
    sub = f"{g['acronym']} · {g['role']}"

    # header band
    d.rectangle([0, 0, W, 250], fill=(*g["accent"], 255))
    hf, hsize = fit_font(d, header, FRAUNCES, "Bold", 72, W - 160, min_size=40)
    hw = d.textlength(header, font=hf)
    d.text((cx - hw / 2, 96), header, font=hf, fill=(*INK, 255))

    sf = font(MONO_B, 26)
    draw_tracked(d, (0, 182), sub, sf, (*INK, 230), tracking=3, anchor_center=cx)

    # blank body -- faint horizontal rules as a "type here" cue, no baked text.
    # Body zone runs from just under the header to just above the logo/URL
    # footer (logo center ~H-230=1690, so 1600 leaves genuine breathing room).
    body_top, body_bottom = 380, 1600
    if kind == "tells":
        n_lines = 6
        step = (body_bottom - body_top) / n_lines
        y = body_top + step / 2 - 10
        for _ in range(n_lines):
            d.line([(90, y), (W - 90, y)], fill=(*g["accent"], 60), width=2)
            d.ellipse([90, y - 10, 110, y + 10], outline=(*g["accent"], 140), width=2)
            y += step
    else:
        # one large open frame for a single check question, plus a small
        # empty roundel where the specific letter for this scenario goes --
        # frame fills most of the body zone, roundel sits in the remainder
        frame_bottom = body_top + int((body_bottom - body_top) * 0.68)
        d.rounded_rectangle([90, body_top, W - 90, frame_bottom], radius=28,
                             outline=(*g["accent"], 130), width=3)
        roundel_cy = frame_bottom + (body_bottom - frame_bottom) // 2 + 20
        d.ellipse([cx - 70, roundel_cy - 70, cx + 70, roundel_cy + 70],
                  outline=(*g["accent"], 200), width=4)
        lf = font(MONO_R, 30)
        lw = d.textlength("?", font=lf)
        d.text((cx - lw / 2, roundel_cy - 18), "?", font=lf, fill=(*g["accent"], 200))

    mark = logo_layer(96)
    paste_center(img, mark, cx, H - 230)
    url_row(d, cx, H - 96, size=24)

    return img.convert("RGB")


def main():
    only = sys.argv[1:] or None
    guides = load_guides()
    if only:
        guides = [g for g in guides if g["slug"] in only]
        if not guides:
            raise SystemExit(f"no guide matches {only}")

    for g in guides:
        gdir = OUT / g["slug"]
        gdir.mkdir(parents=True, exist_ok=True)
        build_cover(g).save(gdir / "cover.png", "PNG", optimize=True)
        build_badge(g).save(gdir / "badge.png", "PNG", optimize=True)
        build_content_card(g, "tells").save(gdir / "tells-card.png", "PNG", optimize=True)
        build_content_card(g, "check").save(gdir / "check-card.png", "PNG", optimize=True)
        print(f"  {g['acronym']:14} -> {gdir}/")

    print(f"\n{len(guides)} guide(s), {len(guides) * 4} images written to {OUT}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
