# -*- coding: utf-8 -*-
"""G.R.O.V.E. gap scenarios — logistics-based leverage the guide did not cover.

The existing 17 cards are strong on interpersonal manipulation and thin on the
physical logistics that a weekend actually runs on: the lift, the walk back,
the charger, where you sleep, and the predator who is already inside your
friendship group rather than approaching from outside it.
"""

ADD = [
("grove", {
 "section": "CONTROL",
 "hook": "I'M YOUR RIDE",
 "archetype": "The Driver / Transport As A Hold",
 "clinical": "Transport Control / Isolation by Logistics",
 "who": "Whoever owns the vehicle, the ticket, or the only spare seat. Often perfectly nice for three days. Becomes something else at the exact moment your plans and his stop matching.",
 "scene": "He drove. It is four hours each way and you are ninety miles from the nearest station with no signal in the car park. On Saturday you want to stay with the people from the neighbouring camp and he says that's fine, a bit flatly, and then mentions that he was thinking of heading off early tomorrow, and you feel the whole weekend quietly reorganize itself around not annoying him.",
 "tells": [
  "One person controls the only realistic way home",
  "Departure time shifts in response to your choices rather than to logistics",
  "Your ticket, wristband, or bag is in his vehicle",
  "“I could just go without you” floated as a joke",
  "You are editing what you ask for to keep the lift viable",
  "No independent route exists and you have not checked whether one does",
 ],
 "happening": "Transport is the cleanest leverage at a festival because it is invisible — nobody has threatened anything, there is nothing to report, and the pressure is purely structural. It works the same way as medication or accommodation control: whoever holds the thing you cannot do without sets the terms of every other conversation. Most people who hold it never use it. The ones who do rarely say anything explicit, because they do not have to; you will do the arithmetic yourself and adjust, and that adjustment is the entire mechanism.",
 "check": "G.R.O.V.E. — “E” CHECK: “If I had to leave this festival in the next two hours without him, could I?” If there is no answer, your exit is somebody else's property.",
 "darkTitle": "The Car Park Is The Trap",
 "dark": "The dangerous shape is not the weekend, it is the journey. A car with one other person in it, four hours of road, no signal, and no way out at seventy miles an hour is a genuinely enclosed space, and people who want an enclosed space know that. This is why the lift home is where a lot of these situations actually turn — the festival was populated and watched, and the drive is neither. Decide the return arrangements before you travel, tell somebody off-site who you are travelling with and when you are due back, and make it entirely normal for them to be expecting a message when you land.",
 "move": "Arrange a second way home before you go — a coach time, a rail replacement, a friend in the next county, sixty pounds set aside for a taxi to a station. Keep your ticket, ID, phone and keys on your body, not in his boot. Text your arrival to an off-site person both ways.",
 "say": "I've got a coach booked back as a backup either way, so don't wait on me if you want to head off — go when you like.",
 "truth": "An exit that depends on somebody else's mood is not an exit. Buy the backup ticket; it costs less than the weekend does.",
}),
("grove", {
 "section": "CONTROL",
 "hook": "I'LL WALK YOU BACK",
 "archetype": "The Escort Home / The Last Two Hundred Metres",
 "clinical": "Opportunistic Isolation / Terminal Isolation Point",
 "who": "Someone who has been around all night, pleasant, unremarkable, and is now offering the single most normal thing at a festival — which is also the thing that ends with him knowing exactly which tent is yours.",
 "scene": "It is late, the site is enormous and dark, and walking back alone genuinely is the thing everybody tells you not to do. He offers. The offer is correct. And somewhere between the last stage and the campsite the crowd thins out and it is just the two of you on a path, and the thing you were avoiding by not walking alone is now walking next to you.",
 "tells": [
  "Insists on walking you specifically rather than the group",
  "Discourages you from texting anyone that you are heading back",
  "Wants to come in “just for a minute”, or to see your camp",
  "Now knows your tent's exact location and that you sleep there alone",
  "Times the offer for when everybody else has already gone",
  "Waves off the alternative — a camp mate, a friend, walking with a group",
 ],
 "happening": "The walk back is the last unwitnessed stretch of the night and it is where a disproportionate amount of festival harm occurs, precisely because the safety advice — do not walk alone — creates a socially compulsory role that anybody can volunteer for. The escort is not a bad idea; being escorted by whoever happened to be standing there at 3am is. The other half of the cost is durable: after tonight, one more person knows which tent is yours, and tent location is the single most useful piece of information anyone can hold about you at a festival.",
 "check": "G.R.O.V.E. — “O” CHECK: “Am I about to be alone with this person somewhere nobody is watching?” The walk counts. That is the whole point of the walk.",
 "darkTitle": "Who Knows Where You Sleep",
 "dark": "Two separate things end here and it is worth keeping them apart. The first is tonight, which is about being alone on a dark path with somebody you have known for six hours. The second is every night after, which is about tent location — information that cannot be withdrawn once given, and that turns up again in the small hours later in the weekend when you had forgotten the conversation entirely. Handle both with the same move: walk back with people you arrived with, and if a stranger walks you, be walked to a landmark near your camp rather than to your door. It is not rude. It is the same reason you would not give a stranger your home address.",
 "move": "Pre-arrange the walk before you need it — leave when your camp leaves, or text a camp mate to meet you at a landmark. If someone unexpected is escorting you, stop at the food stall or the water point, thank them, and let them leave first.",
 "say": "Cheers — Mel's meeting me at the big oak, so I'm good from there. — This is me, thanks, night!",
 "truth": "Not walking alone is good advice. Walking with whoever volunteers at three in the morning is a different piece of advice entirely.",
}),
("grove", {
 "section": "CONDITION",
 "hook": "YOU CAN CHARGE IT AT MINE",
 "archetype": "The Power Bank / Your Phone As The Lever",
 "clinical": "Communication Control / Resource Dependency",
 "who": "The person with the generator, the solar rig, the van with a cigarette lighter, or simply three power banks and a lot of generosity about them.",
 "scene": "You are on eight percent by Friday afternoon, which is the ordinary condition of every phone at every festival. He has power. Charging means leaving it in his van for a couple of hours, or sitting in his camp while it charges, and both of those are completely normal and both of them mean that for two hours the thing that connects you to everyone you know is in somebody else's hands.",
 "tells": [
  "Offers to take your phone away to charge rather than to charge it beside you",
  "Your phone is repeatedly in his possession, briefly, with good reasons",
  "Notices and comments on who is messaging you",
  "Power access is framed as a favour that accrues",
  "Discourages you from getting a power bank of your own",
  "You have found yourself uncontactable for stretches and did not choose that",
 ],
 "happening": "A dead phone removes your map, your torch, your group chat, your ability to call anyone, your record of the weekend, and your capacity to prove where you were. At a festival it is the single most consequential piece of equipment you carry, and the site is designed — unintentionally — to drain it. Whoever solves that problem for you has a hold, and the hold does not require any intent at all to be dangerous: an unreliable friend with your phone produces the same eight hours of unreachability that a deliberate one does. The physical access is the second issue, and the more serious one, since a few unattended minutes is enough to install something or to read everything.",
 "check": "G.R.O.V.E. — “V” CHECK: “Is my phone in my own possession, charged enough to call someone?” If it lives somewhere else for hours at a time, so does your ability to get help.",
 "darkTitle": "Uncontactable Is A Condition Somebody Can Arrange",
 "dark": "Think about what an eight-hour gap in your reachability enables: nobody at home expects to hear from you at a festival, your friends assume you are at a stage, and you cannot be located by anyone who would come looking. Every isolation pattern in this book works better against a woman with a dead phone, which is why the offer to solve it is worth noticing rather than just accepting. The stalking guides make the same point from the other side — physical access to a handset, even briefly, is how location sharing gets quietly switched on. Charge it yourself, in your own hands, and set a PIN that is not your birthday.",
 "move": "Carry two power banks and charge them before you travel — it is the cheapest safety equipment at any festival. If you must use somebody else's power, stay with the phone. Keep a paper note of two numbers and your camp location in your pocket for when it dies anyway.",
 "say": "I'll sit with it while it charges if that's alright — I'm paranoid about losing it. — Got my own bank, thanks though.",
 "truth": "Your phone is your exit, your map and your witness. It does not go in anybody else's van.",
}),
("grove", {
 "section": "CAPTURE",
 "hook": "HE'S BEEN IN OUR GROUP FOR YEARS",
 "archetype": "The Insider / The Predator Who Is Already Vouched For",
 "clinical": "In-Group Perpetrator / Pre-Established Trust Exploitation",
 "who": "Not a stranger. Your friend's partner, the camp regular, the one who has been coming since before you did. Vouched for by people you trust, which is the entire advantage, and which is why he does not have to run any of the approaches in the earlier pages of this guide.",
 "scene": "It is not a stranger at the rail. It is the guy who has been in this group for six years, who everyone loves, who your best friend introduced you to — and who was in your tent doorway at four in the morning saying he just wanted to check you got back okay, standing slightly too close, for slightly too long, in a way you will spend the next three weeks trying to describe to yourself.",
 "tells": [
  "Contact happens at the edges — late, in transit, in the tent, when you are alone",
  "Individually deniable each time, and there is always a reason",
  "He is closer to your friends than you are, and you both know it",
  "Other women in the group have gone slightly quiet about him",
  "Your account would cost the group more than his would",
  "Nothing he has done would sound like anything if you said it out loud",
 ],
 "happening": "Most sexual harm is committed by somebody the person already knows, and festival crews are exactly the trust structure that makes it work — years of shared history, a group identity, and a strong collective incentive not to have this be true. The insider does not need charm or a technique, because vouching has already done the work that an approach would otherwise have to do. What he has instead is the thing a stranger never gets: repeated, unremarkable proximity, and a group that will find it easier to reinterpret your discomfort than to lose him.",
 "check": "G.R.O.V.E. — “G” CHECK: “Am I explaining away something I would flag instantly in a stranger?” Do the substitution deliberately. If a man you met yesterday had done it, you would already know.",
 "darkTitle": "The Group Is The Reason It Keeps Working",
 "dark": "Here is the part that makes this the hardest page in the guide. When someone finally says something, groups usually do not split over whether it happened — they split over what it costs, and the person who spoke is generally the one who pays. Everybody can feel that in advance, which is why it takes years, and why when it finally comes out three other women say quietly that he did the same to them. If you are at the start of that: you do not have to accuse anybody of anything. Say the specific thing, once, to one woman in the group, factually. The overwhelming likelihood is that she has been waiting for somebody else to speak first, and two accounts change everything that one account cannot.",
 "move": "Write it down with the date while it is fresh, in plain factual language with no adjectives. Then tell one woman in the group, privately, as a fact rather than a verdict. Stop being alone with him — no lifts, no late walks, no tent doorways — without announcing a policy.",
 "say": "I want to tell you something and I'm not asking you to do anything with it. On Saturday at about four, Callum did [the specific thing]. I'm writing it down. Has anything like that come up for you?",
 "truth": "Vouched for is not the same as safe. It only means nobody has said it yet.",
}),
]
