# -*- coding: utf-8 -*-
"""P.R.I.D.E. gap scenarios — trans-specific practicalities and closeted leverage."""

ADD = [
("pride", {
 "section": "TOOLS",
 "hook": "SEARCHES, TOILETS AND YOUR MEDS",
 "archetype": "The Trans Festivalgoer's Practical Page",
 "clinical": "Institutional Friction / Access and Continuity Planning",
 "who": "Not a predator — the infrastructure. The pat-down at the gate, the toilet block, the medical tent, and four days away from a bathroom cabinet.",
 "scene": "The security queue splits into two lines by gender and you are doing the calculation you always do. Then there is the question of the toilets for four days, and the fact that your HRT is in a bag that may be searched by someone who will say something, and the medical tent where you may at some point have to explain your body to a stranger with a clipboard while not at your best.",
 "tells": [
  "Gendered search lines with no stated alternative",
  "No gender-neutral toilets, or one block at the far end of the site",
  "Medication in original packaging you would rather nobody read",
  "No plan for a medical interaction where you have to disclose",
  "Binding for multiple days in heat, which is a genuine physical risk",
  "You have not checked whether this event has an LGBTQ+ or welfare lead",
 ],
 "happening": "Most of what makes a festival hard for trans attendees is friction rather than malice, and friction is plannable. Every large event has a welfare team and most now have a named inclusion or access lead; searches can almost always be done by an officer of your choosing or in a private area if you ask, and that request is routine for staff even when it feels enormous to make. The health items are the ones that actually hurt people: binding for four days in heat restricts breathing and causes injury, and interrupted HRT is a medical issue rather than a cosmetic one.",
 "check": "P.R.I.D.E. — “D” CHECK: “Have I found this event's welfare or inclusion lead, and do I know where the gender-neutral facilities are?” Ask at the gate, not on Saturday.",
 "darkTitle": "Binding And Heat Is The Actual Danger",
 "dark": "The genuinely dangerous item on this page is not a person. Binding for consecutive long days in summer heat, while dehydrated, while dancing, is how people end up with bruised ribs, restricted breathing and serious respiratory trouble, and the festival environment removes every natural break you would normally get. Eight hours maximum, never sleep in it, bring a spare and something looser for the hot part of the day, and take the rest breaks in the tent where nobody is watching. Carry your HRT in original labelled packaging with a copy of the prescription — it makes a search conversation short and factual, and it protects you if a bag goes missing.",
 "move": "Email the event before you travel and ask three things: gender-neutral facilities, search policy, and the welfare or inclusion lead's name. Bring HRT in labelled packaging with a prescription copy and a spare stash in a second bag. Plan binding hours like you would plan hydration.",
 "say": "Could I have the search done by a female officer, or somewhere private? — Hi, who's the welfare or inclusion lead this weekend, and where are the gender-neutral toilets?",
 "truth": "Most of this is logistics, and logistics can be arranged in advance. Your ribs cannot be un-bruised afterwards.",
}),
("pride", {
 "section": "CONTROL",
 "hook": "KEEP THIS BETWEEN US",
 "archetype": "The Discretion Demand / Being Somebody's Secret",
 "clinical": "Asymmetric Disclosure Risk / Closeted Partner Dynamics",
 "who": "Someone not out — sometimes genuinely and understandably so, sometimes married, sometimes simply unwilling. The secrecy may be entirely legitimate. What is not legitimate is that all of the risk in it has ended up on you.",
 "scene": "He is warm and interested and has made it clear from the outset that this cannot be seen. So you meet at his tent rather than yours, you do not speak to him near his mates, and on Saturday when somebody asks if you two are a thing he laughs and says no, in a tone that is louder than it needed to be, and you stand there being nobody in public for the second time this weekend.",
 "tells": [
  "Contact only ever happens in private and on their schedule",
  "You are denied, dismissed, or ignored in front of their group",
  "Your discretion is required; theirs is not offered",
  "You would be the one exposed if this came out, and you both know it",
  "They get cold when you are visible near them",
  "Any complaint from you can be reframed as threatening to out them",
 ],
 "happening": "A closeted partner is not doing something wrong by being closeted. The pattern here is narrower: an arrangement where one person carries all the exposure, all the invisibility and all the flexibility, and the other carries none. It is structurally the same as any other asymmetric arrangement in this book — the imbalance is what does the damage, not the secrecy. In a small festival scene it also compounds, because you cannot discuss it with anyone without disclosing them, which means you have been isolated from advice by the terms of the arrangement itself.",
 "check": "P.R.I.D.E. — “I” CHECK: “Whose safety does this secret protect, and whose costs does it ignore?” If the answer is one-way, it is not discretion, it is an arrangement.",
 "darkTitle": "The Accusation That Silences You",
 "dark": "The thing to watch for is the inversion, and it arrives reliably: the moment you raise how the arrangement feels, you are recast as a threat to out them. Now your ordinary complaint about being denied in public is repositioned as potential violence against their safety, and there is no available reply — arguing looks like proving the point. That move is what turns an unequal arrangement into a controlling one, and it is worth recognizing the first time it happens rather than the fifth. You can hold both things at once: their need to be closeted is real and legitimate, and you are allowed to decline to be the person who absorbs the entire cost of it.",
 "move": "Name the asymmetry rather than the secrecy — you are not asking them to come out, you are declining to be denied. Keep one person outside this festival who knows, in general terms, so you are not isolated with it. And decide what you will and will not absorb before the next event, not during it.",
 "say": "I'm not asking you to be out, and I'd never do that to you. I am saying I'm not doing the version where I get laughed off in front of your mates. That's a different thing.",
 "truth": "Protecting someone's privacy is fair. Being nobody in public so that somebody else is comfortable is a cost, and you are allowed to decline it.",
}),
]
