# -*- coding: utf-8 -*-
"""A.C.C.E.S.S. gap scenarios — service animals, being moved, and Deaf/HoH access."""

ADD = [
("access", {
 "section": "CONDITION",
 "hook": "CAN I SAY HELLO TO YOUR DOG",
 "archetype": "The Distractor / Interference With A Working Animal",
 "clinical": "Assistance Animal Interference / Functional Disruption",
 "who": "Mostly delighted, drunk, well-meaning people, arriving at a rate of roughly one every four minutes all weekend. Occasionally somebody who has worked out that distracting the dog is a way to get at you.",
 "scene": "She is in her vest and she is working and a man crouches down in front of her going hey, hey gorgeous, clicking his fingers, and behind him two other people are also crouching, and one of them is offering her a chip. Your dog's whole job is to notice things about you and she has just spent forty seconds noticing him instead.",
 "tells": [
  "Approaching, touching, feeding or calling a dog in a working vest",
  "Continuing after being told she is working",
  "Treating your no as unfriendliness rather than as a medical instruction",
  "Using the dog as an opening to keep talking to you",
  "Letting their own off-lead dog approach yours",
  "Photographing her, or you, without asking",
 ],
 "happening": "A distracted assistance dog is a disabled piece of equipment. An alert dog that misses a signal, a guide dog that loses the line, a mobility dog that breaks position — these are functional failures with real consequences, and a festival supplies distraction at a density found almost nowhere else. Feeding is the most dangerous version because it can make a working animal ill for the rest of the weekend, which removes your support entirely. The legal position in most places is clear that interference is not permitted; the practical position is that fifty people a day will do it anyway.",
 "check": "A.C.C.E.S.S. — “C” CHECK: “Is my equipment currently able to do its job?” A dog is equipment while the vest is on, and this is the one piece of equipment strangers will touch without asking.",
 "darkTitle": "The Dog As An Approach",
 "dark": "There is a version of this that is not about the dog at all. An assistance animal is a guaranteed conversation starter with a person who cannot easily leave, and somebody who wants sustained access to you has an unlimited, socially approved reason to keep returning — asking after her, bringing her water, wanting a photo. It is the inspiration approach from earlier in this guide with a better cover story, and it is harder to refuse because refusing looks like you are being precious about a dog everybody can see is lovely. Watch for the person who comes back. Once is a stranger; the fourth time is a pattern.",
 "move": "Put a bright DO NOT DISTRACT patch on the vest so the sentence is pre-said, and use a flat one-liner without a smile so it does not open a conversation. Keep her water and her food entirely under your control, and do not accept treats from anyone.",
 "say": "She's working, please don't — and please don't feed her, it makes her ill. — [flat, turning away] Thanks.",
 "truth": "She is not a pet this weekend. She is the reason you can be here, and a stranger's forty seconds of fun costs you her attention.",
}),
("access", {
 "section": "CONTROL",
 "hook": "WE'LL JUST LIFT YOU OVER",
 "archetype": "Being Moved Without Consent / Terrain As A Trap",
 "clinical": "Non-Consensual Physical Handling / Mobility Deprivation",
 "who": "Helpful, strong, and already reaching for your chair's handles or your arms. Genuinely trying to solve a problem — the mud, the step, the gap — that the event should have solved and did not.",
 "scene": "The path has turned to mud and you are stuck, which was entirely predictable in October. Three men decide to help. Nobody asks how your chair lifts. Somebody takes the armrest, which is not a lifting point and now bends, and you are briefly airborne and entirely at the mercy of people who mean well and have no idea what they are doing, and your footplate is being used as a handle.",
 "tells": [
  "Hands on you or your equipment before anyone asked",
  "Lifting by armrests, footplates or wheels rather than the frame",
  "“We've got you” said while you are trying to explain how it works",
  "Being carried somewhere you did not agree to go",
  "Terrain the event never made passable, treated as your problem",
  "The offer of help proceeds regardless of your answer",
 ],
 "happening": "Two failures stack here. The event's, which is that accessible routes are an obligation and mud is foreseeable; and the crowd's, which is that helping a disabled person is treated as something that does not require permission. Being lifted incorrectly causes real injuries to both people and to expensive, hard-to-replace equipment, and a chair damaged on Saturday cannot be repaired before Monday, which turns a bad moment into the end of your weekend and possibly your independence for weeks.",
 "check": "A.C.C.E.S.S. — “E” CHECK: “Did I plan a route I can actually use, in this weather?” And in the moment: “Did anybody ask me before touching me?”",
 "darkTitle": "Moved Is Not The Same As Helped",
 "dark": "Underneath the practical risk is the one that matters more. A person who can be picked up and relocated by strangers without agreement has had their ability to leave taken away, and being carried somewhere you did not choose is the single most efficient way to isolate a disabled person — no coercion needed, no conversation, just a friendly group and a mud patch. Most of the time it is exactly what it looks like. The habit worth building is the one that holds in both cases: nobody moves you or your equipment without your instruction, and the instruction includes where you are going.",
 "move": "Say stop first and instruct second — people follow clear instructions and freeze at arguments. Know your chair's actual lift points and say them out loud. Pre-plan hard-standing routes and ask the accessibility team about wet-weather alternatives on arrival, before the mud exists.",
 "say": "Stop — hands off, please. If I want lifting I'll tell you where to hold. It's the frame here and here, and we're going to the hard path, not the tent.",
 "truth": "Help you did not agree to is just being moved. You decide whether, how, and to where.",
}),
("access", {
 "section": "TOOLS",
 "hook": "IF YOU CANNOT HEAR THE ANNOUNCEMENT",
 "archetype": "Deaf And Hard-Of-Hearing At A Music Festival",
 "clinical": "Communication Access / Emergency Information Exclusion",
 "who": "For Deaf and hard-of-hearing attendees, and for anyone whose hearing aids or implants have to survive four days of dust, rain and a hundred and ten decibels.",
 "scene": "Every piece of safety information at a festival is delivered by tannoy: the weather warning, the stage closure, the evacuation route, the missing child, the thing that has just happened at the other end of the site. All of it is audio, all of it is over a distorted PA, and none of it reaches you. You will find out what happened when the crowd starts moving.",
 "tells": [
  "Emergency and safety announcements are audio-only with no visual equivalent",
  "No interpreter listed, and no text alert or app notification option",
  "Staff default to talking louder rather than to writing it down",
  "Your aids or processor have no dry storage, spare batteries, or backup",
  "Nobody in your group has agreed a visual signal for we are leaving",
  "You have not told welfare that you will not hear a tannoy",
 ],
 "happening": "Deaf attendees are systematically excluded from the emergency information layer of an event, and that is a safety issue rather than an inclusion one — evacuation instructions, severe weather warnings and stage cancellations are all broadcast in the one modality you cannot receive. Most events will provide interpreters, text alerts or a welfare contact if asked in advance, and almost none provide them by default. The equipment problem is separate and severe: rain, dust and a dead battery are all far more likely here than at home, and a processor lost at a festival is a five-figure object in a field.",
 "check": "A.C.C.E.S.S. — “A” CHECK: “How will I find out if something goes wrong on this site?” If the only answer is the tannoy, you have no route to emergency information.",
 "darkTitle": "Evacuations Are Announced Out Loud",
 "dark": "The scenario that matters is the rare one. A crowd evacuation, a severe weather call, a stage closure that redirects forty thousand people — these are announced by PA, once, urgently, and then everyone around you starts moving in a direction you do not understand for a reason you have not been told. Moving in a dense crowd without knowing why is how people get hurt. Arrange the alternative in advance, in writing: ask the event for text alerts, register with welfare so they know to find you, and agree a physical signal with your group that means leave now, follow me, no questions.",
 "move": "Email the event before you travel about interpreters and text alerts. Register at welfare on arrival so somebody knows you will not hear a tannoy. Bring a dry box, spare batteries and a backup, and agree a visual emergency signal with your group.",
 "say": "I'm Deaf and I won't hear announcements — can you register that at welfare and tell me how safety info gets out here? — [to your group] If we need to go, this signal. Don't explain, just do it and I'll follow.",
 "truth": "The safety information at a festival is audio-only. Arrange your own channel before you need it, because there will be no time afterwards.",
}),
]
