# -*- coding: utf-8 -*-
"""R.O.O.T.S. gap scenarios — appropriation, misidentification, status risk."""

ADD = [
("roots", {
 "section": "CONDITION",
 "hook": "IT'S JUST A COSTUME",
 "archetype": "Your Culture Worn Around You / Appropriation As Ambience",
 "clinical": "Cultural Appropriation / Environmental Othering",
 "who": "Not a predator. Hundreds of people, none of whom thought about it, wearing your grandmother's dress, a headdress, a bindi, a keffiyeh, a sacred pattern, as festival wear — and one person who will argue with you about it if you say anything.",
 "scene": "You are walking to the second stage and you pass a war bonnet, two bindis and somebody's idea of a kimono, and you are doing the thing you always do, which is deciding forty separate times an hour whether to spend energy on it. Then somebody in your own camp asks you — warmly, as the resident expert — whether her outfit is okay, and now it is your job.",
 "tells": [
  "Sacred or ceremonial items worn as decoration",
  "You are asked to adjudicate, because you are the nearest person of colour",
  "Objecting is treated as policing rather than as information",
  "“It's appreciation” offered as though it settles the question",
  "The energy cost is continuous and invisible to everyone around you",
  "Somebody wants absolution more than they want an answer",
 ],
 "happening": "This belongs in a safety guide for one reason: the cumulative cost. Any single instance is minor and arguable. Forty a day, every day, while also being asked to educate people about it, is a continuous background tax on the same attention you need for everything else in this guide, and depleted attention is the precondition every other pattern relies on. There is also a specific trap in being made the arbiter — once you are the person who rules on this, every conversation about it becomes work you did not agree to do, performed for an audience that wants reassurance rather than information.",
 "check": "R.O.O.T.S. — “T” CHECK: “Am I being asked for information, or for permission?” Information is a conversation. Permission is a job, and you can decline it.",
 "darkTitle": "You Are Not The Ethics Department",
 "dark": "The sharpest version is the person who will not let it go until you approve. They are not asking what you think; they are looking for a member of the group to sign it off so that the discomfort goes away, and your reluctance reads to them as you being difficult rather than as you being tired. That is the moment to notice that a request for education has become an obligation to perform it, in public, for free, about your own culture, at a festival you paid to attend. You are allowed to hand it back. Declining to be the arbiter is not conceding the argument; it is refusing an unpaid role.",
 "move": "Decide your own policy in advance and apply it without deliberating each time — most people pick one thing they will always say something about and let the rest go, and that is a legitimate and sustainable choice. Hand the adjudication back with a resource rather than a ruling.",
 "say": "I'm not the person to green-light that, and I'd rather not be. Have a look up why it's a thing — there's loads written by people who actually want to explain it.",
 "truth": "Deciding forty times a day whether to say something is the cost nobody else can see. Spend it on purpose, not by default.",
}),
("roots", {
 "section": "CONDITION",
 "hook": "SO WHAT HAVE YOU GOT",
 "archetype": "Assumed To Be The Dealer, The Staff, Or The Security",
 "clinical": "Racialized Misidentification / Role Assumption",
 "who": "Strangers, all weekend, who have decided what you are doing here before speaking to you. Sometimes it is a drinks order. Sometimes it is a bin bag handed to you. Sometimes it is somebody asking, very directly, what you are holding.",
 "scene": "You are standing near the edge of a crowd, doing nothing, and a man comes up close and asks quietly what you have got. Then later somebody hands you an empty cup as though you were staff. Then somebody asks where the toilets are in the tone people use with stewards, and you are wearing exactly what everybody else is wearing.",
 "tells": [
  "Approached about substances by strangers who have no reason to",
  "Mistaken for staff, security or crew while in ordinary clothes",
  "Spoken to in an instructional register by people who want service",
  "Security attention that does not match what you are doing",
  "It happens repeatedly, to you and not to the people you came with",
  "Correcting it makes the other person embarrassed, and then annoyed",
 ],
 "happening": "Each instance is small and the pattern is not, and there is a specific risk hiding inside the most common version. Being repeatedly approached about substances by strangers puts you in conversations about drugs, in public, that you did not initiate and did not want — and undercover officers work festivals. A person who is approached fifteen times a weekend has fifteen chances to be observed having exactly the wrong conversation, and the observation does not come with the context that you were approached rather than approaching.",
 "check": "R.O.O.T.S. — “R” CHECK: “Am I in a conversation I did not start, about something I am not doing?” End it flatly and physically, not with an explanation.",
 "darkTitle": "The Conversation You Did Not Start",
 "dark": "This is where the misidentification stops being an indignity and becomes a legal exposure. The differential-enforcement problem from the security page applies directly: if a conversation about substances goes wrong, whose account gets believed is not a neutral question, and being the person who was standing there is a worse position than being the person who walked off. So the move is not wit and it is not a lecture about assumptions. It is ending the exchange in under three seconds and physically relocating, every time, no matter how tedious that becomes by Sunday — and having witnesses who can say you walked away.",
 "move": "Two flat words and a step away. Do not engage, do not joke, do not correct at length. Stay near the people you came with, because the approaches drop off sharply when you are visibly in a group.",
 "say": "Nothing, mate. — [stepping away] Not staff, sorry. — [to your group] That's the fourth one today, I'm sticking with you lot.",
 "truth": "You did not start that conversation and you do not owe it a reply. Walking off is the whole technique.",
}),
("roots", {
 "section": "TOOLS",
 "hook": "IF YOUR STATUS IS THE RISK",
 "archetype": "Immigration Status, Visas, And Why The Advice Changes",
 "clinical": "Immigration Exposure / Differential Consequence",
 "who": "For anyone whose worst-case outcome from any encounter with authority is not a fine or a night in a cell but a removal from the country, a visa consequence, or a family separation.",
 "scene": "Everything else in this book says get help, tell security, make a report. For you, every one of those sentences has a second half nobody wrote down, and you have been quietly translating the whole guide as you read it. This page does the translating out loud.",
 "tells": [
  "Any police contact carries a consequence unrelated to what happened",
  "You avoid medical and welfare because you are unsure who they report to",
  "You do not carry ID, or you carry documents you cannot afford to lose",
  "Someone knows your status and has mentioned it more than once",
  "A dispute would end with you being asked questions the other party will not be asked",
  "No one at home knows exactly where you are this weekend",
 ],
 "happening": "A safety guide that assumes a neutral escalation route is giving some readers a plan that raises their risk. Medical and welfare at festivals are generally not immigration functions and treating people is their job, but the calculation is legitimately different, and pretending otherwise is not kindness. The practical answer is the same as the escalation-ladder page, with more rungs: welfare, harm reduction, camp and community leads, artist liaison — all of which resolve most situations and none of which is a police interaction.",
 "check": "R.O.O.T.S. — “O” CHECK: “What is my worst-case outcome from this escalation — not the average person's?” Plan from your answer, not from the generic one.",
 "darkTitle": "Status As Leverage",
 "dark": "The thing to watch for is somebody who knows and mentions it. Status is among the most effective coercive levers that exists — it needs no threat, it silences reporting completely, and it is why people in precarious immigration positions are targeted deliberately for unpaid work, for sexual coercion, and for keeping quiet about both. If somebody has brought up your status in a conversation that was about something else, that is not conversation, and you are not the first person they have done it to. Get advice from an immigration charity rather than from anyone in the situation, and get it before you need it.",
 "move": "Know the non-police rungs by name before you need them. Carry a copy rather than an original document, and leave the original somewhere safe. Have one person off-site who knows where you are and who to call. Find an immigration advice line now and save the number, while nothing is happening.",
 "say": "I'd rather handle this with welfare than with anyone else — can you get them? — [if your status is raised] We're not talking about that. What's actually the issue here?",
 "truth": "The standard advice was written for somebody whose worst case is a fine. Build the version whose worst case is yours.",
}),
]
