# -*- coding: utf-8 -*-
"""S.O.B.E.R. gap scenarios — accidental exposure, the rotation, meds policing."""

ADD = [
("sober", {
 "section": "CONDITION",
 "hook": "THERE WAS SOMETHING IN THAT",
 "archetype": "Accidental Exposure / The Brownie, The Vape, The Shared Bottle",
 "clinical": "Unintentional Ingestion / Involuntary Exposure",
 "who": "Nobody hostile. A camp full of people who forgot, or who genuinely did not consider that the tray of brownies needed a label, or that the vape going round has more in it than nicotine.",
 "scene": "You ate one thing from the communal table because you were starving and it was food. Forty minutes later you know. You are sitting in a camp chair doing arithmetic about whether this counts, whether you have to tell anyone, whether your sponsor will think you engineered it, and whether your sobriety date has just moved — and none of that arithmetic is helping with the part where you are currently high and did not agree to be.",
 "tells": [
  "Unlabelled food on a communal table",
  "A vape, joint or bottle passed round with no statement of contents",
  "Nobody in the camp thinks to mention it because everybody else knows",
  "A drink topped up rather than handed over",
  "You are the only sober person and the camp has not adjusted anything",
  "The first you hear of it is somebody laughing about it afterwards",
 ],
 "happening": "Accidental ingestion at festivals is common and it is a labelling failure rather than an attack — which does not make it less serious for you. Edibles are the usual route because they are food-shaped and the onset is delayed enough that you have eaten it before anyone could have told you. The practical harm is real — being involuntarily altered removes your capacity in an environment where you are frequently the person others are relying on — and the internal harm can be larger, because it lands as a relapse in a body that cannot tell the difference.",
 "check": "S.O.B.E.R. — “O” CHECK: “Do I know what is in this, from the person who made it?” Communal food counts. This is the rule the book gives everybody, applied to a plate.",
 "darkTitle": "It Is Not A Relapse, And Decide That Now",
 "dark": "Settle this in advance, in daylight, because at the time you will not be able to. Being dosed without agreeing to it is an exposure, not a use — there was no decision, so there is nothing to have relapsed from. Recovery frameworks vary in language but not in substance on this, and every sponsor you could call has fielded it. The danger is not the substance, it is the forty-eight hours afterwards, when shame says you are a fraud, that you must have known, that you cannot tell anyone — and that is the state that turns an accident into an actual return to use. Ring your person that night, not when you feel ready.",
 "move": "Eat from your own supply at camp and ask about anything communal before it reaches your hand. Ask the camp once, openly, on Thursday to label things. If it happens: get somewhere safe with a person, hydrate, ride it out, and call your recovery contact the same day.",
 "say": "Quick one before we settle in — I'm sober, so can we label anything with stuff in it? Doesn't have to be a whole thing, just a note on the tray.",
 "truth": "You did not decide, so you did not relapse. Call your person the same night, before shame writes a different version.",
}),
("sober", {
 "section": "CONDITION",
 "hook": "IT'S COMING ROUND AGAIN",
 "archetype": "The Rotation / Declining The Same Thing Forty Times",
 "clinical": "Repeated Refusal Fatigue / Social Ritual Pressure",
 "who": "The circle itself. The joint, the bottle, the balloon, the vape — a physical object moving clockwise, arriving at you every few minutes, requiring a small public decision each time, for six hours.",
 "scene": "It is not one refusal, it is the fortieth, and by the fortieth you have stopped saying anything and started doing the small hand movement, and somebody has noticed and said something kind about it which made it worse, and you are now thinking about leaving a fire you were enjoying because the geometry of the circle has made your sobriety the most visible thing about you all night.",
 "tells": [
  "The object physically arrives at you on a loop",
  "Each pass is a small public moment you have to handle",
  "Somebody kindly announces your sobriety on your behalf",
  "The circle re-forms around you in a way that makes leaving obvious",
  "You are exhausted by evening and cannot say why",
  "You have started avoiding fires you actually like",
 ],
 "happening": "Refusal fatigue is real and underrated: the cost of any single no is negligible and the cost of forty is significant, particularly when each one happens in front of people and requires a micro-decision about tone. It is also the mechanism by which sober people quietly stop going to the parts of a festival they enjoy most, which produces exactly the isolation that everything else in this guide warns about. The circle is not doing anything to you. The geometry is doing it, and geometry can be changed.",
 "check": "S.O.B.E.R. — “B” CHECK: “Am I avoiding somewhere I like because of the effort of being there?” That is the cost showing up, and it is fixable without leaving.",
 "darkTitle": "Do Not Let It Push You Out",
 "dark": "The outcome to prevent is not any single awkward pass, it is the slow withdrawal — skipping the fire, skipping the camp, spending the weekend at the edges, and ending up alone at a festival, which is the precondition for every pattern in this guide. That withdrawal is invisible while it happens because each individual decision is reasonable. If you find yourself three nights in and mostly on your own, that is not you being antisocial; it is forty small refusals adding up. Fix the mechanics rather than removing yourself: sit at the end of the arc, hold your own cup, and let one friend know to pass it over you.",
 "move": "Change the geometry — sit at the end of the rotation rather than mid-circle, keep both hands busy with your own drink, and ask one friend to skip you so the object never arrives. Pre-empt once, lightly, at the start of the night, so nobody announces it for you later.",
 "say": "Pass it over me all night, saves us both forty conversations. — [holding up your cup] I'm sorted, cheers.",
 "truth": "Forty small refusals cost more than one big one. Move your chair rather than leaving the fire.",
}),
("sober", {
 "section": "CONTROL",
 "hook": "ISN'T THAT STILL A DRUG",
 "archetype": "The Medication Auditor / Policing Your Prescription",
 "clinical": "Recovery Purity Policing / Medication Stigma",
 "who": "Somebody in your own corner — a recovery acquaintance, a camp mate who is proud of you, occasionally someone with a strong opinion about a programme — who has appointed themselves the judge of whether your sobriety counts.",
 "scene": "You take your prescribed medication in front of the camp, as you do every day, and somebody asks what it is. Then asks whether that is allowed. Then says, not unkindly, that they thought you were clean, and you find yourself standing in a field defending a prescription to a person with no medical training and considerable confidence.",
 "tells": [
  "Being asked to justify a prescription socially",
  "Talk of being properly clean, or real sobriety",
  "Your psychiatric or substitution medication discussed as a loophole",
  "Pressure to reduce or stop, from someone who is not your prescriber",
  "You have started taking your meds privately to avoid the conversation",
  "The same person is relaxed about their own caffeine, nicotine or painkillers",
 ],
 "happening": "Medication-assisted treatment and psychiatric prescriptions are medicine, and the evidence for them is strong — but purity narratives inside some recovery cultures treat them as a compromised form of sobriety, and the result is people quietly skipping doses to stay socially legitimate. That is the actual harm here and it is a serious one: interrupted psychiatric medication at a festival, with no sleep and heavy sensory load, is a genuine risk of crisis, and interrupted substitution treatment carries a risk of return to use with reduced tolerance.",
 "check": "S.O.B.E.R. — “R” CHECK: “Has my prescriber said this is fine?” That is the only opinion in this conversation that has any standing.",
 "darkTitle": "Hiding Doses Is How This Hurts You",
 "dark": "Watch for the behavioural tell rather than the argument: the moment you start taking your medication where nobody can see, you have accepted that it is shameful, and skipping becomes easy from there. That is the sequence that lands people in a medical tent on Sunday or in a crisis three weeks later, and it starts with one well-meaning question in a field. Your prescriber knows your history, knows what you are taking and knows why. Nobody in that circle does. If somebody keeps pushing after a flat answer, that is not concern about your recovery, it is a person who needs your compliance to feel right about their own framework.",
 "move": "Answer once, flatly, and do not debate. Take your meds on schedule, in the open, on the same routine you use at home. Tell one person in your camp what they are and what to do if you are unwell, so the information exists somewhere useful.",
 "say": "It's prescribed, my doctor's across it, and I'm not discussing the dose. — Setting an alarm for it, same as at home.",
 "truth": "The only person qualified to audit your prescription is the one who wrote it. Take it in the open and on time.",
}),
]
