# -*- coding: utf-8 -*-
"""K.I.N. gap scenarios — teenagers, substances around children, hearing."""

ADD = [
("kin", {
 "section": "CONDITION",
 "hook": "THE TRAY ON THE TABLE",
 "archetype": "Substances Within Reach Of A Child",
 "clinical": "Pediatric Ingestion Risk / Environmental Safeguarding",
 "who": "Your camp, and the eleven adults in it who are all lovely and none of whom is thinking about a four-year-old's sight lines.",
 "scene": "There is a tin on the low table with something in it, and a half-drunk cider at child height, and a bag on a chair. Your daughter is four and everything at that height is, to her, food. She has been putting things in her mouth for four years and nobody in this camp has had to think about that for a decade.",
 "tells": [
  "Edibles, powders or pills at or below adult-knee height",
  "Unlabelled food on a shared table in a camp with kids in it",
  "Half-finished drinks left within reach",
  "Bags left open on chairs and in tent doorways",
  "The camp has never explicitly discussed having children present",
  "“She won't touch it” offered as the safety measure",
 ],
 "happening": "Pediatric cannabis ingestion has risen sharply everywhere edibles have become common, and the reason is entirely mechanical: edibles look like sweets, a child's dose is a fraction of an adult's, and onset is delayed so the first sign is a small child who is unexpectedly unwell an hour later. At a festival the risk multiplies — more substances, more adults, more surfaces, and a medical tent rather than an emergency department. This is not a page about whether adults in your camp should use anything. It is a page about height.",
 "check": "K.I.N. — “K” CHECK: “If I crouch to my child's eye level right now, what can I reach?” Do it literally. It is a different camp from down there.",
 "darkTitle": "Tell The Medics What They Might Have Taken",
 "dark": "The failure that turns this serious is not the ingestion, it is the hour afterwards. A small child who has eaten an edible presents as unusually drowsy and unsteady, and a parent who does not know what happened reports a child who seems sleepy — which is a completely different clinical picture from a possible ingestion, and gets a completely different response. So the instruction is blunt: if there is any possibility, say so immediately and say exactly what it might have been. Nobody at that medical tent is interested in getting anybody in trouble and they will tell you so, and the treatment depends entirely on knowing. Guessing wrong costs hours, and hours matter at that body weight.",
 "move": "Run a waist-height rule as camp policy on day one — nothing above the ground and below the waist, everything in a closed bag in a tent. Label communal food. Do the crouch test yourself each morning, because camps drift by Saturday.",
 "say": "Kids in camp this year, so can we keep everything above waist height and label the food? Not a judgement thing, just height. — [at medical] She may have eaten an edible, about an hour ago, I don't know how much.",
 "truth": "Your camp is safe at adult eye level. Crouch down to three feet and look again.",
}),
("kin", {
 "section": "CONDITION",
 "hook": "THEY'RE FIFTEEN, NOT FIVE",
 "archetype": "The Teenager At A Festival / A Completely Different Job",
 "clinical": "Adolescent Supervision / Autonomy and Risk Calibration",
 "who": "Your fourteen-to-seventeen-year-old, who is too old for the kids' field, too young for everything else, and now navigating a site full of adults, substances and sexual attention with a child's experience and an adult's height.",
 "scene": "They want to go and watch a band with the two kids from the next camp and be back later, and that is a completely reasonable thing for a fifteen-year-old to want. It is also a fifteen-year-old, at night, in a crowd of adults, where nobody checks anybody's age for anything, and where a nineteen-year-old and a twenty-six-year-old will both read them as older than they are.",
 "tells": [
  "Adults who take an unusual interest in your teenager specifically",
  "An older new friend who appears and is vague about their age",
  "Substances offered to them because they read as older",
  "They have no meeting point, no charged phone and no agreed check-in",
  "They will not tell you if something goes wrong, because of what they were doing",
  "You have not said the one sentence that makes telling you possible",
 ],
 "happening": "A teenager needs a different regime from both a child and an adult — real independence, because refusing it produces a teenager who lies, and real structure, because the environment contains things they have no experience of. The single highest-value item is not a rule, it is a disclosure guarantee. Adolescents decide whether to tell a parent about a bad situation almost entirely on their prediction of the reaction, so a teenager who believes they will be punished for being where they were will handle it alone, at night, at a festival. That is the outcome to prevent.",
 "check": "K.I.N. — “K” CHECK: “Do they have a check-in time, a meeting point, and a promise from me that ringing costs them nothing?” Three things, agreed before they go anywhere.",
 "darkTitle": "The Sentence That Actually Protects Them",
 "dark": "Say this to them plainly, once, before the weekend: if anything goes wrong, whatever you were doing, ring me and I will not be angry and we will sort it out afterwards. Then keep it the first time it is used, over something small, because that is the test and they will run it. The alternative is a fifteen-year-old who has taken something, or is with somebody who will not let them leave, running the calculation about how much trouble they are in, and deciding to manage it themselves. Every safeguarding professional will tell you the same thing: the child who tells you is the one who thinks telling you is survivable.",
 "move": "Give real autonomy with real structure — agreed zones, an hourly-ish check-in, a charged phone and a power bank, a meeting point, and the names of the friends they are with. Say the unconditional sentence and mean it. Tell them the two adult-world things nobody else will: watch your own drink, and an adult being very interested in you is a reason to leave.",
 "say": "Here's the deal: go, have a great time, text me at ten and midnight. And whatever happens, whatever you were doing, ring me — I won't be angry, I'll just come. That's a promise, not a trap.",
 "truth": "You cannot supervise a fifteen-year-old at a festival. You can be the person they are not afraid to ring, and that is worth more.",
}),
("kin", {
 "section": "TOOLS",
 "hook": "EARS, SUN AND THE LONG DAY",
 "archetype": "The Three Physical Things That Actually Hurt Children Here",
 "clinical": "Pediatric Environmental Protection / Noise-Induced Hearing Loss",
 "who": "For every adult with a child at a festival. Nothing on this page involves another person. All of it is the environment, and all of it is preventable with items that cost less than a round of drinks.",
 "scene": "The three things that send children to a festival medical tent are almost never dramatic: overheating, exhaustion, and the slow damage of a hundred decibels going into ears that are much more vulnerable than yours. None of it looks like an emergency while it is happening, which is precisely the problem.",
 "tells": [
  "Ear defenders: not optional, and not just at the main stage",
  "Shade, hat, high-factor sun cream reapplied — they will not ask",
  "Water pushed on a schedule, because children under-report thirst",
  "A real nap or quiet hour every day, in shade, with defenders off",
  "Their own bag: snack, water, defenders, hat, a photo of you",
  "Watch for the quiet child — that is the sign, not the crying one",
 ],
 "happening": "Children's hearing is more vulnerable than adults' and noise damage is cumulative, permanent, and completely painless at the time, which is why nobody acts on it. Festival sound levels routinely sit where hearing protection is required in an occupational setting, and a child does not have to be at the rail to be exposed — a campsite within earshot of a stage is enough over three days. Heat and exhaustion are the other two, and both present quietly: a child who is overheating or depleted goes still and compliant rather than loud, which reads to a busy adult as a child who is finally settling down.",
 "check": "K.I.N. — “I” CHECK: “Defenders on, hat on, water in the last hour, and when was the last quiet hour?” Four things, on a loop, all weekend.",
 "darkTitle": "The Quiet Child Is The Warning",
 "dark": "Know the direction this goes, because it is the opposite of what instinct says. A distressed child makes noise. A child who is overheating, dehydrated or severely depleted becomes quiet, floppy and easy — and in a loud, exhausting, overstimulating environment that reads as a child who has finally calmed down, so the adults relax at exactly the wrong moment. If a child who has been lively all day goes unusually still, stops complaining, or is hard to rouse, that is a medical tent visit now rather than a nap. This is also why the quiet hour is scheduled rather than offered: children will not opt out of a festival on their own, and they do not know when they have had enough.",
 "move": "Defenders from the moment you are on site, not just for the headliner. Shade and water on a timer rather than on request. A scheduled quiet hour every afternoon in the tent with the defenders off. Their own small bag with your number and a photo of you in it.",
 "say": "Defenders on before we go anywhere near a stage — every time, that's the rule. — Quiet hour, back to the tent, we'll come out again at four.",
 "truth": "Hearing damage does not hurt while it happens and it does not come back. Defenders cost fifteen pounds and last their whole life.",
}),
]
