# -*- coding: utf-8 -*-
"""F.L.O.W. gap scenarios — basing consent, crowd contact, unpaid gigs."""

ADD = [
("flow", {
 "section": "CONDITION",
 "hook": "TRUST ME, I'VE GOT YOU",
 "archetype": "The Base / Partner Acro And The Hands That Are Already On You",
 "clinical": "Consent in Physical-Contact Disciplines / Positional Vulnerability",
 "who": "Your base, your flyer, or the person spotting. The discipline requires hands on your ribs, hips and inner thighs, so the contact is legitimate, constant and unremarkable — which is the whole difficulty.",
 "scene": "You are inverted with your entire weight on his hands and he adjusts his grip, and the adjustment goes somewhere that was not necessary for the position, and you are upside down four feet off the ground and the only thing keeping you there is the person who just did that. You come down. Neither of you says anything. He books you for the next jam.",
 "tells": [
  "Grip adjustments that are not required by the position",
  "New moves introduced without describing the contact first",
  "Contact continues after you have landed and are stable",
  "Objecting is framed as not trusting your base, which is a safety word here",
  "Sessions move from open practice to private space",
  "You come out of a wash feeling odd and cannot point to a single thing",
 ],
 "happening": "Partner acro, aerial and any spotting discipline share a structural problem: consent to hold has to be given in advance and continuously, while the person giving it is frequently inverted, load-bearing, or in a position where objecting is physically unsafe. Every acro community that has addressed this has landed on the same protocol — name the contact before the move, no new contact mid-position, and trust means trusting the hold rather than trusting the person's intentions. The word trust is the thing to watch, because it is doing safety work and social work simultaneously and somebody can lean on the second to get the first.",
 "check": "F.L.O.W. — “W” CHECK: “Was this contact named before the move started?” Unnamed contact is the finding, regardless of where it landed.",
 "darkTitle": "You Cannot Object At Four Feet",
 "dark": "The reason this is not like other unwanted contact is the physics. You cannot step back, you cannot pull away, and reacting sharply while inverted risks a genuine injury to both of you — so your body overrides the objection to keep you both safe, and afterwards you will read your own stillness as consent. It was not; it was self-preservation. This is exactly why the protocol lives before the move rather than during it, and why the right move afterwards is not to relitigate what happened in the air but to change the practice: named contact, open space, and a different base. You do not owe anybody an accusation to be allowed to stop flying with them.",
 "move": "Agree the contact map before any new move, out loud, every time — where hands go, and where they do not. Practise in open space. Change base without explaining yourself; you never owe a reason for who holds your body.",
 "say": "Before we try it — where are your hands going? Ribs and hips, nothing else, and tell me if that changes. — I'm going to work with Sam on this one, cheers.",
 "truth": "Trust in acro means trusting the hold. It has never meant losing the right to say where the hands go.",
}),
("flow", {
 "section": "CONDITION",
 "hook": "THEY GRABBED ME MID-SET",
 "archetype": "The Crowd / Performing Is Not Consent To Be Touched",
 "clinical": "Performance Boundary Violation / Audience Contact",
 "who": "The crowd, at about one in the morning, drunk and delighted and not thinking — grabbing a hoop, stepping into a fire circle for a photograph, putting hands on a stilt-walker's legs, reaching for an aerialist's foot.",
 "scene": "You are three minutes into a fire set and a man steps inside the circle to film himself next to you. He is about a metre from a lit wick moving at speed and he has no idea, and you now have to decide, mid-spin, whether to stop the set or keep going while somebody stands in the burn radius filming.",
 "tells": [
  "People entering the performance space for photographs",
  "Props grabbed, touched or stepped on mid-set",
  "Costume, wings, stilts or rigging treated as public property",
  "No safety perimeter, no marshal, and no marked boundary",
  "Contact that would be obviously unacceptable if you were not performing",
  "The venue treats crowd management as your problem",
 ],
 "happening": "Performing in public gets read as an open invitation, and for fire and aerial that misreading is a physical danger to the audience as well as to you — a person inside a fire circle is inside a burn radius, and a grabbed hoop or a knocked stilt takes a performer down onto hard ground. The professional answer is that crowd management is the event's job and a perimeter is a condition of the booking, not a nicety. The individual answer is that you are allowed to stop, and stopping is safer than performing around an obstacle.",
 "check": "F.L.O.W. — “O” CHECK: “Is there a real perimeter and somebody holding it?” If not, that is a condition to fix before you light, not a thing to absorb during.",
 "darkTitle": "Stopping Is The Professional Response",
 "dark": "The trained instinct is to keep going, because performers are conditioned that stopping is failure. Unlearn that one. A set continued around a member of the public standing in the burn radius ends, when it ends badly, with a burned stranger, an insurance claim, and a performer explaining why they did not stop — and the explanation will be that it would have been awkward. The second half of this belongs to the event: a perimeter and a marshal are a condition of booking for fire, and if a promoter will not provide them the correct answer is that you do not perform, not that you perform more carefully.",
 "move": "Make the perimeter and a named marshal part of accepting the booking. Stop the set the moment the boundary is broken — kill it, say why, restart when it is clear. Agree a stop signal with your safety before you start.",
 "say": "I need a marshal and a three-metre perimeter or I can't light — that's not negotiable for fire. — [stopping] Set's paused, mate, you're standing in the burn circle. Back behind the line and we'll go again.",
 "truth": "You are working, not on display. A set that has to be performed around an obstacle is a set that should have stopped.",
}),
("flow", {
 "section": "CONTROL",
 "hook": "IT'S A GREAT LOOK FOR YOUR REEL",
 "archetype": "The Unpaid Booking / Spectacle For Exposure",
 "clinical": "Labor Exploitation / Exposure as Substitute Payment",
 "who": "A promoter with a budget for sound, lights, security and bar staff, and a line about community for the people doing the dangerous thing in the middle of the field.",
 "scene": "He wants three fire performers for the Saturday headline changeover. There is no fee. There are wristbands, and he says it in a way that makes the wristbands sound generous. He also mentions that a lot of people get seen at this one, and that the photographer is really good, and every single other trade at this event is being paid.",
 "tells": [
  "Wristbands offered as the fee for skilled, insured, dangerous work",
  "Every other supplier at the event is on a rate",
  "No contract, no call time in writing, no fuel or travel budget",
  "No mention of insurance, or an assumption that you carry it",
  "“Exposure”, “the community”, “great for your reel”",
  "The photographer is paid and you are not",
 ],
 "happening": "Fire and aerial performance is skilled, insured, equipment-heavy, physically dangerous labour, and it is the single most reliably unpaid element of a festival's programme because performers love doing it and promoters know that. The comparison that settles it is on-site: the sound engineer, the bar staff, the security and the photographer are all on rates. If a budget exists for everyone who touches the event except the people doing the thing with fire in it, that is a decision rather than a constraint.",
 "check": "F.L.O.W. — “L” CHECK: “Who else working this event is unpaid?” If the answer is only the performers, the budget is not the problem.",
 "darkTitle": "The Insurance Question Is The Real One",
 "dark": "The part that outlives the argument about money is liability. Unpaid, uncontracted, uninsured fire performance means that when somebody is burned — you, a colleague, or a member of the public who walked into the circle — there is no contract establishing who was responsible for the perimeter, no employer, and frequently no cover. Promoters who do not pay performers also, reliably, have not thought about any of that, and the person standing in the footage holding the lit tool is the one who will be answering for it. Ask about public liability in the first conversation. The answer tells you everything about the event's professionalism, before money is even discussed.",
 "move": "Quote a rate like any other supplier and ask two questions early: what is the fee, and who carries public liability for this performance. Get the call time, perimeter and marshal in writing. Decline cheerfully and early rather than resentfully and late.",
 "say": "My rate's [x] per performer plus fuel and travel. Also — who's carrying public liability for the fire, you or us? I need that confirmed before I commit.",
 "truth": "Everyone else at this event is being paid. Your work is more dangerous than most of theirs, and a wristband is not a fee.",
}),
]
