# -*- coding: utf-8 -*-
"""H.E.A.L. gap scenarios — the client who targets the practitioner, crisis in
session, and barter."""

ADD = [
("heal", {
 "section": "CONDITION",
 "hook": "THE CLIENT WHO BOOKS YOU EVERY DAY",
 "archetype": "When You Are The One Being Targeted",
 "clinical": "Practitioner Victimization / Therapeutic Frame Exploitation",
 "who": "Books repeatedly, discloses heavily and fast, and treats the session as a relationship rather than an appointment. Sometimes genuinely in distress. Sometimes using the one structure on site where a stranger will touch you alone in a tent for an hour.",
 "scene": "Third booking in two days. He has started arriving early and staying after, and the disclosures have moved from his shoulder to his marriage to the fact that you are the only person who has ever really understood him, and today he asked whether you would have dinner, and when you said no he apologized so thoroughly that you ended up reassuring him.",
 "tells": [
  "Books far more often than the presenting issue warrants",
  "Rapid, heavy personal disclosure aimed at building intimacy",
  "Arrives early, stays late, wants to be in your space outside the session",
  "Gifts, or paying over the rate",
  "Tests small boundaries and apologizes elaborately when they hold",
  "You have started dreading the booking and have not told anyone",
 ],
 "happening": "The therapeutic frame is unusually exploitable in this direction: a practitioner is alone, often in a soft-walled space, professionally committed to warmth and non-judgement, and financially motivated to keep a repeat client. All four of those work against you. This is a known pattern in massage, bodywork and complementary practice, and the festival version is worse because there is no reception, no colleague next door, no booking system, and no employer — just you, a tent and somebody who booked an hour of unobserved access.",
 "check": "H.E.A.L. — “L” CHECK: “Is this a client, or is somebody building a relationship inside an appointment?” Frequency, disclosure and after-time are the three that tell you.",
 "darkTitle": "Your Training Is Being Used Against You",
 "dark": "Notice which of your professional instincts are working for him. Non-judgement stops you naming it. Holding space keeps you in the tent. Not wanting to shame a client stops you saying no plainly. Needing the booking stops you cancelling. Every one of those is a good quality and all four are load-bearing for him, which is why practitioners are so slow to act on this and why by the time they do it has usually escalated. Break it with structure rather than with a judgement about him: somebody else on site knows your schedule, the tent flap stays open, and the booking pattern is capped. You do not have to decide he is dangerous to stop being alone with him.",
 "move": "Cap repeat bookings and say the cap is policy. Tell one person your schedule and have them walk past at the end of each session. Keep the space semi-open. End the after-time at the door rather than inside, and write down what happened the same day.",
 "say": "I keep it to one session a day per person so everyone gets a slot — book you in Sunday. — I'm going to wrap it there, I've got Mira coming in. [walking out with him]",
 "truth": "Warmth is your professional tool. It is not an obligation to be alone with somebody who is using it.",
}),
("heal", {
 "section": "EMERGENCY",
 "hook": "SOMETHING BIGGER JUST OPENED UP",
 "archetype": "A Crisis Arrives On Your Table / Knowing Your Own Edge",
 "clinical": "Scope of Practice / Crisis Recognition and Referral",
 "who": "A client who came in for tension and is now in the middle of something much larger — a flashback, a panic attack, a disclosure of abuse, or a psychiatric emergency — in your tent, on your table, with you.",
 "scene": "Bodywork opened something and she is not in the room any more. She is shaking, breathing badly, somewhere in her own history, and telling you something she has clearly never said out loud. You are a massage therapist. You have ninety seconds to decide what you are and are not going to try to do, and every instinct you have is pulling you toward staying with it.",
 "tells": [
  "Dissociation, flashback, or panic on the table",
  "A disclosure of abuse, self-harm or suicidal thinking",
  "Signs of a psychiatric emergency rather than emotional release",
  "You are considering doing something you were never trained to do",
  "The session has run long because stopping feels like abandonment",
  "You have no referral route and did not find one before the event",
 ],
 "happening": "Bodywork and altered-state contexts surface trauma routinely, and the single most consequential skill a practitioner has is knowing where their own edge is. Attempting to process trauma without that training can deepen it, and the moment where it feels most compassionate to continue is the moment it is most likely to do harm. The competent response is small and unglamorous: stabilize, ground, do not excavate, and hand over to someone whose job it is. Every large festival has welfare, and most have psychedelic support services staffed by people trained for precisely this.",
 "check": "H.E.A.L. — “E” CHECK: “Am I still inside what I was trained to do?” The honest answer arrives fast, and it is usually no, and no is the correct place to stop.",
 "darkTitle": "Staying Is Not Always The Kind Thing",
 "dark": "The mistake almost never looks like negligence — it looks like a caring practitioner who did not want to abandon somebody mid-crisis, and who therefore attempted trauma work they had no training for, in a tent, on a stranger, at a festival. That is how people are left more destabilized than they arrived, and it is committed by good practitioners with good intentions every season. Handing over is not abandonment, and it is worth saying out loud to the client that it is not, because they will experience it that way if you do not. Walk them there. Do not send them.",
 "move": "Stop the bodywork. Ground them — upright, feet on the floor, breathing, orient to the room and the day. Do not ask for more detail and do not interpret. Then walk them to welfare or the psychedelic support tent yourself, and debrief afterwards with your own person.",
 "say": "I'm going to stop the massage. Feet on the floor, sit up with me, look at the doorway. You're at a festival, it's Saturday afternoon, you're safe. — This is bigger than what I'm trained for, and that's not me leaving you. I'm going to walk over to welfare with you and stay while you get someone who does this properly.",
 "truth": "Knowing where your training stops is your training. Walking somebody to the right person is competence, not failure.",
}),
("heal", {
 "section": "CONTROL",
 "hook": "WE CAN JUST TRADE",
 "archetype": "Barter, And The Deal That Stops Being A Deal",
 "clinical": "Undefined Exchange / Boundary Ambiguity in Barter",
 "who": "Everyone, at every festival, because the gift economy is real and beautiful and almost entirely undocumented — which means every trade has terms nobody said out loud.",
 "scene": "You will do a session and he will sort you out for the weekend. It is a fair trade and you both meant it kindly. Then it is unclear whether one session covered it or three, and he keeps appearing, and on Saturday when you say you are done for the day there is a silence, and you realize that neither of you ever said what the deal was and he has been keeping a different tally.",
 "tells": [
  "A trade agreed in a sentence, with no scope and no end point",
  "Value on both sides assumed rather than stated",
  "The other party's side arrives first, creating an open obligation",
  "Being traded substances, which ties your work to a supply",
  "The deal is renegotiated afterwards, upward",
  "You are doing sessions you do not want to do and cannot say why",
 ],
 "happening": "Barter is not the problem — vagueness is. An undefined trade creates exactly the open-ended obligation that the reciprocity pages elsewhere in this book describe, with the additional feature that professional work is now entangled with a personal relationship and nobody can point to the terms. Trading for substances is the version worth refusing outright: it makes your practice dependent on a supply and a supplier, it is the clearest route to a dual relationship, and it converts a professional service into something you can be leaned on for.",
 "check": "H.E.A.L. — “L” CHECK: “Does this trade have a stated scope and an end?” If not, it is not a trade, it is an account somebody else is keeping.",
 "darkTitle": "An Open Account Is A Hold",
 "dark": "The damage is not the specific trade, it is the self-editing that starts once you believe you owe somebody something you cannot quantify. You do the extra session. You do not raise the thing that annoyed you. You keep the appointment you wanted to cancel. That is the same quiet accommodation the gift-with-a-ledger pages describe, and in a practitioner it is worse, because the currency you are paying in is unobserved physical access to your own time and body. Close the account explicitly, even at the cost of seeming transactional in a scene that prizes not being.",
 "move": "Say the terms out loud and keep them small and closed — one session for one named thing, done, settled. Never trade for substances. Write the trade in a message so it exists. If an account has already opened, close it deliberately rather than letting it run.",
 "say": "Happy to trade — one session for the [x], and then we're square, yeah? Just so neither of us is keeping score. — I don't trade for anything you consume, but I'll do you a mate's rate.",
 "truth": "A trade with no end point is not generosity, it is an open account. Say the number, even when it feels unspiritual.",
}),
]
