# -*- coding: utf-8 -*-
"""L.E.N.S. gap scenarios — the photographer's own exposure, minors, and the
subject who turns."""

ADD = [
("lens", {
 "section": "CONDITION",
 "hook": "ALONE, AT NIGHT, WITH FOUR GRAND OF GEAR",
 "archetype": "The Photographer As The Target",
 "clinical": "Occupational Exposure / High-Value Equipment Risk",
 "who": "Whoever has been watching the person with the obvious camera bag walk back to the media tent alone at three in the morning for the third night running, on the same route, at roughly the same time.",
 "scene": "You shot the headliner, you are carrying two bodies and three lenses, and the walk back to the car park goes through the dark bit behind the production compound because it is quicker. You do this every night. You have never thought about it, because you are thinking about the edit.",
 "tells": [
  "The same route, the same time, alone, every night",
  "Visible high-value equipment and no discreet bag",
  "Working at the crowd's edges and in unlit areas by the nature of the job",
  "Head in the camera — the one posture that removes your situational awareness",
  "Nobody knows your route or when you are due back",
  "Somebody has been unusually interested in what you are carrying",
 ],
 "happening": "Photographers occupy the highest-risk position at a festival and almost never think of themselves as at risk: they carry the most valuable and most portable items on site, they work alone at night by necessity, they are in the unlit margins rather than in the crowd, and the job itself requires them to spend long stretches with one eye in a viewfinder and no awareness of what is behind them. The equipment loss is the visible risk. Being followed to a vehicle in an unlit car park at three in the morning is the one that matters more.",
 "check": "L.E.N.S. — “E” CHECK: “Does anybody know my route and my ETA tonight?” If the answer is no, and it is the same route as last night, that is two problems rather than one.",
 "darkTitle": "Vary The Route, Tell Somebody The Time",
 "dark": "The pattern is what does it. Somebody who wants your gear does not need to find you; they need to watch you once and then wait in the right place the following night, and a photographer is the most predictable person on a festival site — same stages, same pits, same exit, same hour. Two changes remove almost all of it, and neither costs anything: alter the route and the timing, and have a named person expecting you with a time. The gear is insured. Being alone in an unlit car park at three in the morning with somebody who has been planning it since Friday is not.",
 "move": "Vary your route and your times. Use an unbranded bag. Walk out with someone — another shooter, crew, security — and agree an ETA with a named person each night. Insure the kit properly and keep serial numbers and photographs.",
 "say": "Walking out at half two — anyone going the same way? — [message] Heading to the car park now, back at the hotel by three, I'll text when I'm in.",
 "truth": "You are the most predictable, most valuable and least accompanied person on this site. Change two of those three tonight.",
}),
("lens", {
 "section": "ACCOUNTABILITY",
 "hook": "THERE ARE KIDS IN THAT FRAME",
 "archetype": "Photographing Children At A Public Event",
 "clinical": "Child Safeguarding / Image Consent for Minors",
 "who": "You, in the family field, where the light is good and the pictures are genuinely lovely and every single one of them has a safeguarding dimension you are responsible for.",
 "scene": "A child on someone's shoulders at golden hour with her hands in the air is one of the great festival photographs and you have a clear shot of it. You do not know her, you have not spoken to her parents, and in about four hours you will be deciding whether to put a recognizable image of somebody else's child on a public account.",
 "tells": [
  "A recognizable minor, no parent asked",
  "The frame would identify them to anyone who knows them",
  "You are relying on the setting being public as your permission",
  "A child in distress, undressed, or in a medical context",
  "You have no written consent and are about to publish commercially",
  "You would not be comfortable if a stranger did this to your own child",
 ],
 "happening": "Photographing children is the one area of event photography where the legal position and the professional standard diverge most sharply. In most public settings it is not unlawful, and every festival's media policy, every safeguarding lead, and every reputable agency nevertheless requires parental consent for identifiable minors — because the risk is not to you, it is to a child whose image you are putting into circulation without anyone who is responsible for them having agreed. Custody arrangements, safeguarding orders and families who are not findable are all invisible from behind a lens.",
 "check": "L.E.N.S. — “L” CHECK: “Has a parent said yes, by name, to this specific use?” Public setting is not permission where a child is concerned.",
 "darkTitle": "You Cannot See The Reason It Matters",
 "dark": "The specific families this hurts are the ones you cannot identify from where you are standing: a child in a custody dispute whose location must not be public, a family with a safeguarding order, a parent who has moved away from someone. A photograph of a child geotagged at a named festival on a public account can undo arrangements that took years to build, and the photographer will never learn that they did it. That is the whole argument for asking, and it is why the standard is consent rather than judgement — you are not in a position to assess the risk, so you do not get to decide it is low.",
 "move": "Ask the parent before you shoot, and get a name and a contact if you intend to publish. Default to backs of heads, crowd-scale, or unidentifiable framing in family areas. Never shoot a child in distress or in a medical context. If in doubt, send it to the parent and let them decide.",
 "say": "Lovely moment — do you mind if I take it? I'd only post it if you're happy, and I'll send it to you either way. Can I grab your number?",
 "truth": "A public field is not consent for somebody else's child. Ask the parent, or shoot the back of the head.",
}),
("lens", {
 "section": "CONTROL",
 "hook": "TAKE IT DOWN OR I'LL MAKE IT A THING",
 "archetype": "The Subject Who Turns / Demands, Threats And Pile-Ons",
 "clinical": "Post-Publication Conflict / Reputational Coercion",
 "who": "Someone in a frame you published — sometimes with an entirely legitimate grievance you should act on immediately, sometimes escalating to demands for money, and occasionally mobilizing a pile-on that arrives before you have read the first message.",
 "scene": "The message says take it down. You took it at a public stage, you asked at the time, and you have the reply. The second message says you owe them money for using their image. The third says they have screenshotted your account and people are going to hear about this, and by the morning there are forty comments on a photograph of somebody else entirely.",
 "tells": [
  "A takedown request — which you should simply honour, immediately",
  "A demand for payment attached to the takedown",
  "Threats about your reputation rather than about the image",
  "Claims that shift each time you answer them",
  "Public escalation before any private conversation",
  "You have no record of the consent you actually obtained",
 ],
 "happening": "Two different things arrive in the same inbox and telling them apart is the whole skill. A person asking for their image to come down is exercising something you should grant without argument, whatever the law says and whatever you paid to be there — that is the profession's own standard and it is also the cheapest possible resolution. A demand for money, or a threat about your reputation, is a different transaction, and the correct response to that one is not negotiation but documentation.",
 "check": "L.E.N.S. — “N” CHECK: “Is this a request to remove, or a demand for something else?” Remove instantly for the first. Do not pay the second.",
 "darkTitle": "Delete First, Document Everything",
 "dark": "The sequence that keeps photographers out of trouble is counterintuitive: comply completely and immediately on the takedown, and only then deal with the rest. Arguing about whether you were entitled to publish is the thing that converts a two-minute fix into a public campaign, because to everyone watching you are the person with the camera refusing to delete a picture. Take it down, say you have, apologize for the distress without conceding any claim, and keep every message. And build the thing that makes all of this short next time: a consent log, with a name, a date and what was agreed, which turns a he-said-she-said into a record.",
 "move": "Remove it immediately and say so. Do not pay, do not argue the law, do not respond publicly. Screenshot everything with timestamps. Keep a consent log from now on so the next one is a thirty-second conversation.",
 "say": "It's down — removed as soon as I saw your message, and I'm sorry it upset you. I'm not able to pay anything, but the image is gone and it won't be used again.",
 "truth": "Take it down first and sort out who was right afterwards. The photograph was never worth the week.",
}),
]
