# -*- coding: utf-8 -*-
"""C.R.E.A.T.E. gap scenarios — AI style theft, solvent safety, the brief you object to."""

ADD = [
("create", {
 "section": "CONTROL",
 "hook": "WE RAN YOUR STUFF THROUGH A MODEL",
 "archetype": "Your Style, Regenerated Without You",
 "clinical": "Generative Appropriation / Style Replication",
 "who": "A promoter, a brand, or a former client who has discovered they can get something that looks like your work without booking you — and who genuinely does not understand why you would object, because no file of yours was copied.",
 "scene": "The poster for this year's event is unmistakably yours. The palette, the linework, the way you do figures. You did not make it. When you ask, they say they made it in-house, and then, cheerfully, that they used your last three pieces as references, and they say it as though that were a compliment rather than a description of what they did.",
 "tells": [
  "Work that reproduces your recognizable style without your involvement",
  "“In the style of”, or your name used as a prompt reference",
  "A former client who stopped booking you and whose visuals did not change",
  "Your live-painting footage or process shots used as training references",
  "A contract clause licensing your work for “any purpose including machine learning”",
  "They are baffled by your objection and cite that nothing was copied",
 ],
 "happening": "Style is not protected the way a specific work is, which makes this legally murky and commercially devastating — a festival that can generate something close enough to your look does not need to book you, and the thing that made you employable becomes the thing that replaces you. The practical defence is therefore contractual and evidential rather than legal after the fact: what you license, to whom, for how long, and whether machine learning uses are excluded. Most artists have never read that clause and most event contracts now contain one.",
 "check": "C.R.E.A.T.E. — “A” CHECK: “What exactly did I license, and does it exclude training and generation?” If you have never checked, assume it does not.",
 "darkTitle": "The Clause You Signed In A Queue",
 "dark": "Look at the media and artist agreements you have already signed, because the grabbing happens there rather than later. Perpetual, worldwide, sublicensable, all media now known or hereafter devised, for any purpose — that language predates all of this and covers it completely, and the artists most exposed are the ones who signed it years ago and never looked again. Add an exclusion in writing to every future agreement, register the significant pieces where registration exists in your country, and document your process with dated footage. Provenance is what you will have instead of a remedy.",
 "move": "Add an explicit exclusion to every contract — no training, no generative reuse, no style derivation — and get it in the email even when you cannot get it in the document. Watermark and register key work. Keep dated process footage. Raise it once, in writing, with the actual decision-maker rather than publicly.",
 "say": "My licence excludes any machine-learning or generative use, including style references — can you confirm that in writing before I invoice? — That poster is derived from my work. I'd like to talk about a fee or its removal.",
 "truth": "They did not copy a file, they copied the decade. Put the exclusion in the contract, because there is no remedy afterwards.",
}),
("create", {
 "section": "CONDITION",
 "hook": "IT'S FINE, THE TENT'S OPEN AT ONE END",
 "archetype": "Solvents, Aerosols And Four Days In A Marquee",
 "clinical": "Occupational Chemical Exposure / Inadequate Ventilation",
 "who": "The environment, plus a schedule that wants eight hours of live painting a day inside a structure designed to keep rain off rather than to move air.",
 "scene": "You are spraying in a marquee with the sides down because it is raining. There are three other painters doing the same thing and a crowd standing in it watching, and by the fourth hour you have the headache you always get and have stopped noticing the smell, which is the part that should worry you most.",
 "tells": [
  "Aerosols or solvents used in an enclosed or half-closed structure",
  "You have stopped smelling it, which means saturation rather than safety",
  "Headache, dizziness, nausea, or a sore throat by mid-afternoon",
  "No respirator, or a dust mask being used as though it filtered vapour",
  "The public standing in the same air with no ventilation plan",
  "Consecutive long days, because the exposure is cumulative",
 ],
 "happening": "Solvent and aerosol exposure is a genuine occupational hazard with cumulative effects on the nervous system and the airways, and live painting at festivals reproduces almost every condition that makes it worse: enclosed space, long consecutive days, no extraction, and no employer carrying a duty of care. The critical detail is that a dust mask does nothing against organic vapour — it is the wrong class of protection entirely, and it produces a false sense of safety that leads people to work longer in worse air.",
 "check": "C.R.E.A.T.E. — “E” CHECK: “Can I smell it, and is air actually moving through here?” If you have stopped smelling it and nothing is moving, leave now rather than at the end of the piece.",
 "darkTitle": "Acclimatization Is Not Tolerance",
 "dark": "The dangerous signal is the one that feels like good news. When the smell fades you have not adapted, your olfactory receptors have saturated — and you are now breathing the same concentration with the warning system switched off, which is why people work through it and why the worst exposures happen to the most experienced painters on the longest days. Cumulative solvent exposure over years of festivals is a known occupational pattern and it does not announce itself. Buy the right cartridge respirator, insist on open sides, and take the piece outside when the rain stops.",
 "move": "Carry an organic-vapour cartridge respirator, not a dust mask, and know when the cartridges expire. Insist on cross-ventilation as a condition of the pitch. Break outside every hour. Use water-based paint where the piece allows it, and keep the public out of the immediate air.",
 "say": "I need the sides up on at least two walls or I can't spray in here — it's a vapour thing, not a preference. — Taking twenty outside, back at four.",
 "truth": "When you stop smelling it, your warning system has failed, not the fumes. That is the moment to go outside.",
}),
("create", {
 "section": "TOOLS",
 "hook": "I DON'T WANT TO PAINT THAT",
 "archetype": "The Brief You Object To / Declining Without Burning The Circuit",
 "clinical": "Creative Autonomy / Reputational Risk in Refusal",
 "who": "A promoter, a brand or a camp with a brief that conflicts with something you actually hold — imagery you find appropriative, a sponsor you object to, a message you do not want your name on.",
 "scene": "The brief lands and it is a good fee and there is a piece of it you cannot do: a symbol that is not yours to paint, or a brand you have publicly criticized, or a theme you think is straightforwardly bad. And the circuit is small, and saying no to this promoter means something for next season, and you are already assembling a version where you do it and put it in a different corner of your portfolio.",
 "tells": [
  "The brief conflicts with something you would defend in public",
  "You are negotiating with yourself rather than with them",
  "The fee is doing the arguing",
  "Nobody has offered a route to modify the brief",
  "You are planning to leave it off your portfolio, which is the tell",
  "You expect refusal to cost you future bookings",
 ],
 "happening": "This is a live-painting problem more than a studio one, because you make the work in public, with your name on the pitch, in front of the audience whose opinion is your actual asset. A piece you are uncomfortable with is not a private compromise; it is a public statement made in your hand, photographed, and attributed to you for years. The practical question is rarely whether to refuse outright — most briefs have a component that can be changed — and the useful move is to separate the part you object to from the job and offer an alternative.",
 "check": "C.R.E.A.T.E. — “T” CHECK: “Would I be happy for this to be the piece people associate with me?” Planning to leave it out of your portfolio is the answer arriving early.",
 "darkTitle": "Refusing Well Is A Skill Worth Having",
 "dark": "The real risk is not refusing, it is refusing badly — late, publicly, or with a moral framing that makes the promoter the villain in a small circuit where everybody talks. That is what costs bookings, and it is avoidable. Decline early, privately, warmly, with an alternative attached and no lecture, and you will usually keep the relationship and occasionally get the brief changed. Nobody is owed your explanation for why, and delivering one is what turns a professional no into an argument. The artists who last on a circuit are the ones who can say no in a single friendly sentence and still be booked the following year.",
 "move": "Decline early and privately, name only the specific element, and offer a concrete alternative. Do not explain your ethics at length and do not go public. If the fee is genuinely tempting, ask for the brief to change rather than negotiating with yourself.",
 "say": "Love the rest of it and I'm keen — the one thing I can't paint is [element], it's not mine to use. If you're happy with [alternative] in that space I'm in, and if not, no hard feelings, I'd still love to do next season.",
 "truth": "You make your work in public with your name on it. A piece you would hide is a piece you should have declined.",
}),
]
