# -*- coding: utf-8 -*-
"""S.O.U.N.D. gap scenarios — hearing, gear on the road, promoter-supplied substances."""

ADD = [
("sound", {
 "section": "CONDITION",
 "hook": "THE RINGING STOPS EVENTUALLY",
 "archetype": "Hearing Damage / The Injury That Ends The Career Quietly",
 "clinical": "Noise-Induced Hearing Loss / Tinnitus",
 "who": "The job itself. Monitors, the pit, load-in, the bus, three hundred nights a year, and a culture where asking for in-ears or wearing plugs still occasionally reads as not being committed.",
 "scene": "The ringing after a show used to last an hour and now it lasts until the afternoon. You have started asking people to repeat themselves in bars. You mix your own tracks slightly brighter than you used to, which is your ears telling you something you are choosing to hear as a preference.",
 "tells": [
  "Tinnitus that persists longer after each run",
  "Struggling with speech in noisy rooms",
  "Turning monitors up across a tour rather than down",
  "No custom moulded plugs, or a pair you have stopped using",
  "Ear fatigue changing the mixing decisions you make",
  "The idea that plugs would ruin the experience, which is the belief that costs the most",
 ],
 "happening": "Noise-induced hearing loss and tinnitus are the defining occupational injuries of this trade, they are cumulative, and they are permanent — there is no treatment that restores what is gone. The specific cruelty for musicians is that the damaged faculty is the instrument: the loss is not merely a disability, it degrades your ability to do the work, and it does so gradually enough that you will adjust to it rather than notice it. Custom moulded musicians' plugs attenuate evenly rather than muffling, which is the objection most people have and the one that is not true.",
 "check": "S.O.U.N.D. — “D” CHECK: “How long does the ringing last now compared with a year ago?” Write it down. Trend is the measurement that matters.",
 "darkTitle": "It Does Not Come Back",
 "dark": "There is no recovery arc here and that is the whole point of the page. Hair cells do not regenerate, tinnitus that becomes permanent is permanent, and the endpoint for a significant number of people in this industry is a career ended by an injury that was completely preventable with a piece of equipment costing less than a single flight case. It is also the injury least likely to be taken seriously in the moment, because it does not hurt and there is nothing to see. Get a baseline audiogram now, get moulded plugs, use them at load-in and in the pit as well as on stage, and treat the trend as data rather than as ageing.",
 "move": "Get custom moulded musicians' plugs with interchangeable filters, and a baseline audiogram you repeat annually. Wear protection at load-in, soundcheck and in the crowd, not just on stage. Push for in-ears in your rider. Give your ears two quiet days after a run.",
 "say": "In-ears are on my rider and they're not a nice-to-have — I'm protecting the thing I work with. — I've got moulded plugs in, I can hear you fine, they're flat.",
 "truth": "Your ears are the instrument and they do not heal. The plugs cost less than one flight case.",
}),
("sound", {
 "section": "CONTROL",
 "hook": "THE VAN GOT DONE",
 "archetype": "Gear Theft On The Road / The Night The Tour Ends",
 "clinical": "Equipment Theft / Operational Continuity Failure",
 "who": "Organized and specific. People who know what a band's van looks like, which hotels touring acts use, and that a vehicle packed after a show and parked overnight contains everything the act owns.",
 "scene": "You loaded out at two, drove forty minutes, parked outside the travel lodge like always, and in the morning the side door is open and the van is empty. Instruments, laptops with the stems, merch, the lot. You have a show tomorrow, the insurance certificate is in a folder somewhere, and nobody wrote down a single serial number.",
 "tells": [
  "A packed vehicle left overnight in an unsecured car park",
  "Band or crew branding on the van, which advertises the contents",
  "No serial numbers, no photographs, no itemized inventory",
  "Insurance that does not cover unattended vehicles overnight — most do not",
  "Backups of session files kept only on the stolen laptops",
  "Predictable routine: same venues, same hotels, same parking",
 ],
 "happening": "Van theft is a specialist activity aimed at touring musicians precisely because the value density is extraordinary and the routine is predictable. The part most bands get wrong is the insurance: a great many policies exclude theft from an unattended vehicle overnight, which means the cover people believe they have does not apply to the single most likely way they will lose everything. The second thing is documentation — without serials and photographs a claim is slow and a police recovery is effectively impossible even when the gear surfaces.",
 "check": "S.O.U.N.D. — “D” CHECK: “Could I list every serial number and produce a photograph of each item today?” If not, you do not have a claim, you have a list of regrets.",
 "darkTitle": "Read The Overnight Exclusion Before The Tour",
 "dark": "Do this one thing this week: find the clause about unattended vehicles. Bands discover it at the worst possible moment — after the theft, mid-tour, with dates they cannot play and a claim that will be declined. Alongside it, keep the session files somewhere that is not in the van: a cloud backup of stems and masters costs almost nothing and is the only part of the loss that is genuinely irreplaceable, because instruments can be re-bought and a year of unreleased recordings cannot. Everything else on this page is inconvenience; that part is the career.",
 "move": "Photograph and serial-number everything into a shared document before you leave. Unload the critical items into the accommodation every night — tedious, and it is the whole prevention. Use an unbranded van, vary parking, fit a secondary lock and a tracker. Check the overnight exclusion and back up your files off the vehicle.",
 "say": "Small gear and laptops come in with us every night, no exceptions — it's twenty minutes and it's the difference between a bad night and no tour. — Can you send me the policy wording for unattended vehicles?",
 "truth": "Twenty minutes of carrying flight cases into a hotel is the cheapest insurance on the road, and the only one with no exclusions.",
}),
("sound", {
 "section": "CAPTURE",
 "hook": "WHATEVER YOU NEED, IT'S SORTED",
 "archetype": "The Promoter Who Supplies / Hospitality As A Hook",
 "clinical": "Substance Provision as Leverage / Dependency Cultivation",
 "who": "The promoter, the tour manager, or the local fixer whose hospitality is unusually comprehensive and who never seems to want paying for that part of it.",
 "scene": "The rider is fine and there is something else on the table that was not on it, and he says it is sorted, and this happens at every one of his shows. By the fourth booking you are aware that you look forward to his shows for a reason that is not the audience, and that the conversation about the fee has become a conversation you are less inclined to have.",
 "tells": [
  "Substances provided as hospitality, routinely and unasked",
  "Never itemized, never charged, never discussed",
  "Availability increases around contract or payment conversations",
  "Supply is tied to continuing to work with this person specifically",
  "Your consumption has escalated in a way that tracks the touring schedule",
  "You have stopped pushing on money and cannot say exactly when that started",
 ],
 "happening": "Supply is one of the oldest forms of leverage in this industry and it works without a single explicit exchange being proposed. It creates reciprocal debt, it degrades judgement during exactly the conversations where your judgement matters commercially, and it establishes a dependency that is tied to one relationship. It also builds an accumulating hold: somebody who has supplied you for two years knows things about your consumption that they can allude to, and that hold does not require any intention at the time to be usable later.",
 "check": "S.O.U.N.D. — “N” CHECK: “Would I push as hard on this contract if the hospitality stopped?” If the answer is yes, the hospitality is doing business.",
 "darkTitle": "The Supply Is A Record Of You",
 "dark": "The part that arrives years later is the knowledge. A person who has supplied you routinely has a detailed, private account of your use, and at the point where you want to leave, renegotiate, or raise something about their conduct, that account exists and both of you know it. Nothing has to be said explicitly; the industry is full of artists who simply found it easier not to push. Keep your own supply if you use, decline provided substances as a flat policy rather than a judgement, and keep the money conversation in writing and in daylight where the hospitality cannot reach it.",
 "move": "Make it a standing policy and say it early so it is not about anyone: your rider is your rider, and you do not take anything else from promoters. Do contract and money conversations by email, sober, before the show rather than after it.",
 "say": "Appreciate it, I keep it to what's on the rider — blanket rule for me, nothing personal. — Let's do the fee by email in the morning rather than tonight.",
 "truth": "Hospitality that is never itemized is not hospitality. It is an account being opened in your name.",
}),
]
