# -*- coding: utf-8 -*-
"""M.A.R.K.E.T. gap scenarios — payment fraud, weather loss, the physical toll."""

ADD = [
("market", {
 "section": "CONTROL",
 "hook": "THE PAYMENT SAYS IT WENT THROUGH",
 "archetype": "Card Fraud, Fake Transfers And Counterfeit Notes",
 "clinical": "Payment Fraud / Transaction Deception",
 "who": "Somebody who has worked out that a vendor at hour nine, in bad light, with a queue forming and no signal, cannot verify anything and will not hold up the line to try.",
 "scene": "He shows you the screen. It says sent, with your name on it and a tick. It is half past eleven, the signal has been dropping all day, your banking app will not load, and there are four people waiting behind him holding things they want to buy. You hand over the piece.",
 "tells": [
  "A screenshot of a transfer rather than money in your account",
  "Payment claimed at the exact moment your signal is worst",
  "A card that declines and is retried on a different reader",
  "Large notes for small items, late at night, in poor light",
  "Hurrying you, with a queue behind, and a reason it must be now",
  "Refunds requested in cash for a card transaction",
 ],
 "happening": "Every one of these relies on the same three conditions a festival supplies reliably: bad connectivity, bad light and social pressure from a queue. A transfer screenshot proves nothing and is trivial to fake; a pending or unsettled card payment is not a payment; and counterfeit notes at a market stall late at night are an old trade that persists because nobody wants to be the vendor who holds up the line over a twenty. The cash-refund version is the cleanest fraud of the lot, and the answer to it is that a refund goes back the way the money came, always.",
 "check": "M.A.R.K.E.T. — “M” CHECK: “Has the money arrived in my account, or have I been shown a picture of money?” Those are not the same event.",
 "darkTitle": "The Queue Is The Weapon",
 "dark": "Notice what is actually being used against you, because it is not technology. It is your reluctance to make four other paying customers wait while you check. That pressure is manufactured, it is often manufactured deliberately, and it is the reason this works at eleven at night and never at eleven in the morning. Decide the policy in advance so there is no decision to make in the moment: no goods leave the stall until the money is confirmed in your account or the terminal says approved, and if the signal is down you take cash or you take a name and hold the item. Losing one sale is not a cost. Losing four pieces across a weekend is.",
 "move": "Set the rule before the event and put it on a small card on the stall. Keep a UV pen and check large notes. Never refund cash on a card payment. Take a deposit and hold the item if you cannot verify. Reconcile takings nightly rather than on Monday.",
 "say": "I'll hold it for you — I just can't let it go until it lands my end, signal's awful. Two minutes and it'll come through. — Refunds go back to the card, not in cash, sorry.",
 "truth": "A screenshot is not a payment. The queue behind him is the pressure, and it is doing exactly what it was arranged to do.",
}),
("market", {
 "section": "CONDITION",
 "hook": "THE WIND TOOK THE GAZEBO",
 "archetype": "Weather, Loss And The Insurance Nobody Bought",
 "clinical": "Uninsured Business Loss / Environmental Risk",
 "who": "The forecast, and a pitch fee that bought you a square of grass and no guarantees whatsoever.",
 "scene": "It went at four in the morning. The frame is in three pieces, half the stock is in a puddle, the rest blew toward the fence, and the event is running as normal at ten. Nobody is going to reimburse you, your pitch fee is not coming back, and you have just discovered that your policy covers theft but not weather.",
 "tells": [
  "Gazebo weights instead of ground anchors, on a forecast you did not check",
  "Stock stored at ground level in a field",
  "No stock insurance, or a policy that excludes weather and unattended loss",
  "No written terms about cancellation or refund with the organizer",
  "No contingency float to survive a wiped weekend",
  "Everything you own on the circuit is in this one gazebo",
 ],
 "happening": "Vendors carry all the risk at an outdoor event and almost none of the protection. Pitch fees are near-universally non-refundable, organizers rarely take liability for weather, and the standard trader policy people buy often excludes exactly the two things most likely to happen in a field — storm damage and loss from an unattended stall overnight. The result is a business that can lose a season's stock in one night with no route to recovery, sitting next to an event that continues around it.",
 "check": "M.A.R.K.E.T. — “R” CHECK: “If my stall was destroyed tonight, what would I actually recover?” Read the policy now, not at four in the morning.",
 "darkTitle": "Concentration Is The Real Exposure",
 "dark": "The structural danger is concentration rather than weather. Most makers put their entire inventory into one vehicle, one gazebo, one weekend, and a single night removes the business rather than a weekend's takings. Split the stock: keep a reserve in the van, and a reserve at home that never travels, so the worst night costs you an event instead of a livelihood. Then read the policy wording for storm and unattended exclusions, ask the organizer in writing what happens to the pitch fee if the event is cancelled or a trading day is lost, and keep a float that covers one wiped weekend. None of this is pessimism; it is the difference between a bad weekend and starting again.",
 "move": "Ground-anchor properly and check the forecast daily. Stock off the ground, in lidded boxes. Split inventory across stall, van and home. Get a policy that covers storm and unattended stock, and get the organizer's cancellation terms in writing before you pay the pitch fee.",
 "say": "Before I pay the pitch — what are the terms if the event's cancelled or we lose a trading day to weather? Can you put that in the email? — Half the stock stays in the van, always.",
 "truth": "The pitch fee buys you grass. Everything that happens on it is yours, so split the stock and read the exclusions.",
}),
("market", {
 "section": "TOOLS",
 "hook": "FOURTEEN HOURS ON YOUR FEET",
 "archetype": "The Physical Cost Nobody Budgets For",
 "clinical": "Occupational Physical Strain / Vendor Fatigue",
 "who": "The schedule. Four days, fourteen-hour trading days, a build at either end, no chair because standing sells better, and no break because a break is a closed stall.",
 "scene": "Day three. You have not sat down since seven, you have eaten one thing, you cannot leave because there is nobody to cover you, and you have started making decisions — about pricing, about a wholesale enquiry, about whether that transfer really went through — with a brain that has been standing up in the sun since dawn.",
 "tells": [
  "No cover, so no breaks, so no meals and no toilet trips",
  "Standing all day on hard ground with no anti-fatigue matting",
  "Dehydration because drinking means needing the toilet you cannot go to",
  "Business decisions being made at hour twelve",
  "Lifting the whole build alone, twice per event",
  "Recovery time between events that is shorter each season",
 ],
 "happening": "Vendor fatigue is an economic problem before it is a health one. Every transaction on this page's neighbours — the fake transfer, the renegotiated deal, the wholesale offer that is worse than it sounds, the pressure to drop a price — arrives at the end of a long day and lands on a depleted person, and depleted people concede. The physical toll is real and cumulative too, but the immediate cost is commercial: you are making your most consequential decisions in your worst condition, by design, several times a weekend.",
 "check": "M.A.R.K.E.T. — “E” CHECK: “Am I about to make a real decision at hour twelve?” Defer it to the morning. Everything that is genuinely good will still be there.",
 "darkTitle": "They Come At You At Closing Time",
 "dark": "Notice the timing of the difficult conversations across a weekend. The wholesale enquiry, the request for a discount, the organizer wanting to change your pitch, the payment that cannot quite be verified — these cluster late, and not entirely by accident. Some of it is simply when people wander past, and some of it is people who have learned that a vendor at closing on day three will agree to things they would refuse on Friday morning. So make the policy, not the judgement: no deal over a set value, no contract, no wholesale terms and no price change is agreed after a certain hour. You will never regret the sentence, and the good ones come back in the morning.",
 "move": "Rota real breaks with a neighbour — mutual stall cover is the most valuable trade on any circuit. Anti-fatigue mat, a stool, water on a schedule. Set a cut-off hour after which no significant decision is made, and say so cheerfully.",
 "say": "Can we cover each other? Twenty minutes each, twice a day — I'll do yours first. — That sounds great and I don't do deals after seven — come back at ten tomorrow and we'll sort it properly.",
 "truth": "Your worst decisions happen at hour twelve, and the people asking know it. Defer anything that matters to the morning.",
}),
]
