# -*- coding: utf-8 -*-
"""H.O.L.D. gap scenarios — the dual role, after-shift pressure, physical handling."""

ADD = [
("hold", {
 "section": "CONDITION",
 "hook": "YOU'RE OFF SHIFT BUT YOU'RE STILL STAFF",
 "archetype": "The Dual Role / Volunteer By Day, Attendee By Night",
 "clinical": "Role Ambiguity / Boundary Collapse",
 "who": "Everyone on a volunteer-for-a-ticket arrangement, which is most of the workforce at most festivals — you are staff for eight hours and a punter for sixteen, wearing the same wristband and known to the same people.",
 "scene": "You finished at six. At eleven, in the crowd, somebody recognizes you from the welfare tent and starts telling you about their night, and then somebody else asks you where the medical tent is, and then an actual incident happens four feet away and everyone nearby turns to look at you, and you have had three drinks.",
 "tells": [
  "People bring you work problems when you are off shift",
  "You are identifiable as staff even out of hi-vis",
  "You have intervened in something while off duty and impaired",
  "Your camp is staff camping, so there is no off-site to go to",
  "Management treats you as available for the whole event",
  "You cannot say where the shift ended and the weekend started",
 ],
 "happening": "The volunteer-for-a-ticket model produces a genuinely ambiguous role and almost no organizations address it. Two specific risks follow. First, liability: intervening while off duty and impaired is not covered by any briefing or insurance, and it is where volunteers get hurt or get someone else hurt. Second, depletion: a person who is never fully off shift does not recover, and the compassion-fatigue pages elsewhere in this guide describe what that turns into by day three. Neither is your fault; both are yours to manage, because the event almost certainly has not.",
 "check": "H.O.L.D. — “H” CHECK: “Am I on duty right now — and does everyone around me know the answer?” If it is ambiguous to you, it is ambiguous to them.",
 "darkTitle": "Impaired And Intervening Is The Worst Combination",
 "dark": "Picture the incident report. A volunteer, off shift, three drinks in, restrained somebody or made a medical call or walked an attendee somewhere — and it went wrong. There is no briefing that covers it, no insurance that applies, and the organization's position afterwards will be that you were not working. This is also the exact scenario where genuinely well-meaning volunteers cause harm, because the instinct to help does not switch off with the shift and the judgement does switch off with the drinks. Make it visible instead: wristband off, lanyard away, and one sentence that hands it to whoever is actually on duty.",
 "move": "Make off-duty physically visible — lanyard off, hi-vis away, and say it out loud when asked. Hand every off-shift request to the on-duty team by radio or in person rather than handling it. Leave staff camping for part of each day if you can, because being permanently among colleagues is what makes the role never end.",
 "say": "I'm off shift and I've had a drink, so I'm not the right person — but I'll walk you to the welfare tent right now and hand you to whoever's on.",
 "truth": "A wristband that never comes off is a shift that never ends. Being off duty only counts if the people around you can tell.",
}),
("hold", {
 "section": "CONTROL",
 "hook": "COME BACK TO OURS AFTER, EVERYONE DOES",
 "archetype": "The After-Shift Party And The Person Who Signs Your Hours",
 "clinical": "Hierarchical Social Pressure / Post-Shift Coercion",
 "who": "A supervisor, a team lead, or a long-standing crew member with informal authority — who is not asking you for anything explicit, and who also decides your shifts, your reference, and whether you are asked back.",
 "scene": "The crew party is a real thing and it is where the bonding happens and where next season's roles get informally decided, and the person suggesting you come is the person who writes your hours. Going means drinking with somebody who has power over you, in their camp, at three in the morning. Not going means being the one who does not join in, and both of you know which one is easier.",
 "tells": [
  "Social attendance is where progression and rota decisions actually happen",
  "The invitation comes from someone in your reporting line",
  "Declining is noticed and mentioned later",
  "Alcohol, staff camping, and no HR of any kind",
  "Other volunteers have had a bad experience nobody wrote down",
  "There is no reporting route that does not run through this person",
 ],
 "happening": "Festival crews have workplace power structures and almost none of the workplace protections — no HR, no written complaints route, no contracts for volunteers, and a supervisor who controls access to next season. The after-shift party is where that power operates informally, and the risk is not the party itself, which is often genuinely one of the best parts of the job. It is that declining has a cost and attending has a different one, and that there is nobody to report to if something happens, because the person you would report is the person you would report to.",
 "check": "H.O.L.D. — “O” CHECK: “Who could I report this person to, by name?” Ask on day one. If there is no second name, the hierarchy has no floor.",
 "darkTitle": "Find The Second Name Before You Need It",
 "dark": "The structural fix is one question asked in your first hour, when it is completely neutral: who handles a concern about a supervisor. Ask it of the volunteer coordinator as a routine induction question and write the answer down. Almost every event has a safeguarding or welfare lead outside the line hierarchy, and almost nobody tells volunteers who they are — which means the information exists and simply is not distributed. Asking on Thursday costs nothing and is forgettable. Asking on Sunday, after something, is an accusation before you have even described it.",
 "move": "Get the out-of-line reporting name on day one. Go to the party if you want to and take a crew mate, or decline warmly and without a reason and let the relationship prove itself. Keep your own notes of shifts and any incident, dated, on your own phone.",
 "say": "Who handles it if someone's got a concern about a supervisor — is there someone outside the team? Just like to know where things go. — I'm knackered, I'll catch you tomorrow — have a good one.",
 "truth": "Ask who the complaint goes to while nothing has happened. On Thursday it is admin; on Sunday it is an accusation.",
}),
("hold", {
 "section": "TOOLS",
 "hook": "WHEN YOU HAVE TO PUT HANDS ON SOMEONE",
 "archetype": "Physical Intervention Without The Training For It",
 "clinical": "Untrained Restraint / Positional Asphyxia Risk",
 "who": "Every volunteer who has ever had to stop somebody walking into a road, hold a stretcher, move somebody who is unconscious, or get between two people who are fighting — with a two-hour briefing and no qualification whatsoever.",
 "scene": "He is unconscious and needs moving out of the crowd, or he is trying to climb something, or two people are going at it and you are the nearest person in hi-vis and everybody has turned to look at you. You have never been trained in any of this and you are about to do it anyway because nobody else is going to.",
 "tells": [
  "No restraint or manual-handling training, and no licence",
  "You are the nearest hi-vis and that has become an instruction",
  "Someone unconscious being moved by well-meaning bystanders",
  "Face-down or compressed positioning, which is the lethal one",
  "No radio call made before hands went on",
  "Nobody has told you what you are and are not permitted to do",
 ],
 "happening": "Untrained physical intervention is the highest-consequence thing an unqualified volunteer can do, and it happens constantly because the hi-vis creates an expectation the training never met. Two specifics are worth knowing above everything else. Positional asphyxia — holding or leaving someone face-down or folded, especially if they are intoxicated, large, or struggling — kills people, and it is the single most documented cause of restraint-related death. And an unconscious person who is breathing goes into the recovery position on their side, not face-up and not face-down, because the airway is the whole problem.",
 "check": "H.O.L.D. — “H” CHECK: “Am I trained for what I am about to do?” If not, the intervention is a radio call and a presence, not a hold.",
 "darkTitle": "Face Down Is The One That Kills",
 "dark": "If you remember one line from this guide, make it this. Never hold or leave anybody face-down, and never fold somebody forward while restraining them, and never sit or kneel on a back or a chest. Positional asphyxia gives almost no warning: the person stops struggling, and everyone present reads that as calming down when it is the opposite. If someone is unconscious and breathing, they go on their side. If they are struggling, you get a trained responder and you keep space rather than keeping hold. Your job in every one of these is to call it in fast, keep the area clear, and stay — presence and a radio have saved far more people at festivals than grip ever has.",
 "move": "Radio first, always, before hands. Use presence and space rather than contact. If someone is unconscious and breathing, recovery position and stay with them. Never face-down, never weight on a torso. Ask your supervisor on day one exactly what you are authorized to do physically, and get the answer.",
 "say": "Control, I need a medic and security at the north bar now, one male unconscious but breathing, I'm with him. — [to bystanders] Give us room please, don't move him, I've got help coming.",
 "truth": "A radio and your presence are the intervention. Hands are the part you were never trained for and the part that kills people.",
}),
]
