# -*- coding: utf-8 -*-
"""B.U.I.L.D. gap scenarios — the drive home, strike phase, faked competence."""

ADD = [
("build", {
 "section": "CONDITION",
 "hook": "THE DRIVE HOME",
 "archetype": "The Most Dangerous Hour Of The Whole Build",
 "clinical": "Fatigue-Impaired Driving / Post-Event Collapse",
 "who": "You, on the Monday, after a three-week build and a two-day strike, with a van full of kit and four hours of motorway between you and a bed.",
 "scene": "Everything is loaded. The site is a field again. You have slept eleven hours in the last three days and you are going to drive home now because that is what everybody does and because the alternative is another night in a field. You will be fine for the first hour. The one that gets people is the third.",
 "tells": [
  "Driving at the end of a long build or a full strike",
  "Fewer than five hours' sleep in each of the preceding nights",
  "Driving in the window your body expects to be asleep",
  "Loaded van, unfamiliar route, motorway",
  "The whole crew leaves at once, so nobody is checking on anybody",
  "“I'll stop if I get tired”, which is the belief that does the damage",
 ],
 "happening": "Fatigue is a leading cause of fatal road collisions and the risk profile matches this exact moment: sustained sleep debt, monotonous roads, and driving at a time of day when the body is trying to shut down. The specific danger is the microsleep — a few seconds of sleep with the eyes open, which the driver does not experience as having happened, which is why “I'll know when I'm too tired” is false. At seventy miles an hour, four seconds is a hundred and twenty metres of unattended vehicle.",
 "check": "B.U.I.L.D. — “D” CHECK: “How many hours have I slept in the last three nights?” If it is under fifteen, you are not driving tonight. That is arithmetic, not opinion.",
 "darkTitle": "Crews Lose People On The Monday",
 "dark": "This is the one that actually kills build crew, and it happens after the dangerous work is finished, which is exactly why nobody plans for it. The whole site has spent weeks being careful about heights and plant and blades, and then everybody gets in a vehicle in the worst physiological state of the entire job and drives home alone. Budget the extra night the way you budget fuel — sleep on site and leave Tuesday morning, or put the money for a room in the quote. If you are running the build, build it into the schedule and say out loud that nobody drives on Monday, because a crew will not do it individually if the culture expects the Monday drive.",
 "move": "Sleep before you drive — one more night on site is cheaper than any alternative. Share the driving and stop every two hours regardless of how you feel. Caffeine buys twenty minutes, not four hours. Text somebody when you arrive so a missing message means something.",
 "say": "I'm not driving tonight, I've had about four hours a night all week — I'll go first thing. — Crew rule this year: nobody drives on the Monday. Put the extra night in the budget.",
 "truth": "The build did not hurt you. The drive home is the part that kills people, and it happens after you think the job is over.",
}),
("build", {
 "section": "CONDITION",
 "hook": "STRIKE IS WHEN IT ALL GOES WRONG",
 "archetype": "Teardown / The Phase Nobody Briefs",
 "clinical": "Post-Event Risk Concentration / Governance Collapse",
 "who": "The last forty-eight hours, when the audience has gone, the production office has half packed, most of the supervisors have left, and whoever is still on site is dismantling in the dark with the fewest people and the least oversight of the entire job.",
 "scene": "Everyone is exhausted, the structures are coming down in reverse order by people who did not put them up, half the crew are new faces brought in for the teardown, and the person who would have said no to something is already on a train. There is no briefing for strike. There never is.",
 "tells": [
  "No strike briefing, though there was a build one",
  "Structures dismantled by people who did not erect them",
  "Supervisors and safety leads already departed",
  "New casual crew with unverified experience",
  "Everyone at their most fatigued, working at speed to finish",
  "Payment and paperwork also leaving the site, with you unpaid",
 ],
 "happening": "Teardown concentrates every risk factor in this guide into the shortest window: maximum fatigue, minimum supervision, unfamiliar crews, and a strong collective incentive to be finished. Dismantling is more dangerous than erecting, because loads shift unpredictably when a structure comes apart and because the people taking it down often do not know how it went together. It is also when the money leaves — the production company is closing the site down, and a worker who is owed and has not been paid is now chasing an organization that has physically gone.",
 "check": "B.U.I.L.D. — “U” CHECK: “Who is supervising strike, and who am I handing this structure to?” If nobody can answer, that is the finding, on day one of teardown.",
 "darkTitle": "The Money Leaves With The Site",
 "dark": "Two things walk off during strike and both matter. The first is competence: the people who know how each structure was built leave before it comes down, so ask for a handover from whoever erected it and do not guess a load path. The second is your wage. Payment at settle-up is bad enough; payment at settle-up during a teardown, when the office is packing and the crew is dispersing, is how people go home unpaid with no one left to ask. Get your hours signed before strike begins, not after, while there is still somebody on site whose job it is to sign them.",
 "move": "Insist on a strike briefing, even a five-minute one. Get a handover from whoever built a structure before you take it down. Get your hours signed and confirmed before teardown starts. Keep the buddy rule and the fatigue rule harder in strike than in build.",
 "say": "Before we start pulling this down — who put it up, and can they walk me through it? — Can you sign off my hours today rather than Monday, while there's still an office?",
 "truth": "Strike has the most fatigue, the fewest supervisors and the least oversight of the whole job, and nobody briefs it. Ask for the briefing.",
}),
("build", {
 "section": "CONTROL",
 "hook": "YEAH, I'VE DRIVEN ONE OF THESE",
 "archetype": "Faked Competence / The Ticket Nobody Checked",
 "clinical": "Unverified Qualification / Plant Operation Risk",
 "who": "Somebody who needs the work and has said yes to a question they should have said no to — usually not out of recklessness, but because admitting it on a site where everyone else seems to know what they are doing feels impossible.",
 "scene": "He is on the telehandler moving a two-tonne load over a walkway and his movements are not right and everybody can see it and nobody is saying anything, because saying something means calling a man a liar in front of the crew. You are standing in the area he is swinging over.",
 "tells": [
  "Nobody has asked to see a ticket, licence or certification",
  "Hesitant, jerky or improvised operation of plant or lifting equipment",
  "Vague or deflecting answers about where and when they trained",
  "No banksman, no exclusion zone, no lift plan",
  "The crew has noticed and is communicating about it by eye contact",
  "The site has no record of anybody's qualifications",
 ],
 "happening": "Plant, lifting and height work are ticketed for a reason and festival builds are one of the last places where nobody asks to see the ticket. The pressure runs both ways: an operator who overstates their experience is usually somebody who could not afford to lose the gig, and a crew that will not challenge it is protecting a man's dignity at the expense of everyone standing underneath. Neither of those is malice, and the outcome is the same as if it were.",
 "check": "B.U.I.L.D. — “U” CHECK: “Has anybody actually seen this person's ticket?” Assumed competence is not competence, and you are standing in the swing radius.",
 "darkTitle": "Say It To The Supervisor, Not To The Man",
 "dark": "The reason this persists is entirely social, so the fix has to be social too. Challenging the operator directly in front of the crew is humiliating and will be resisted, which is why nobody does it and why the situation runs for days. Take it to the supervisor as a question about paperwork rather than about a person — have we got tickets on file for the plant operators — and it becomes an administrative matter with no one accused of anything. And remember the other half: if you are the one who said yes to something you cannot do, saying so now costs you a job, and saying so after costs somebody a life. Nobody on a site has ever been fired for saying they need a hand with a machine they do not know.",
 "move": "Ask the supervisor for tickets to be on file as a site-wide matter, not about an individual. Stay out of swing and drop zones regardless. Insist on a banksman for every lift. And if it is you: say so, today, to one person.",
 "say": "Have we got plant tickets on file for everyone? Worth having if anything happens. — [if it's you] I've not run one of these before, I said yes when I shouldn't have. Can I get shown properly or put somewhere else?",
 "truth": "Nobody wants to call a man a liar in front of the crew. Make it a question about paperwork and it stops being about him.",
}),
]
