# -*- coding: utf-8 -*-
"""C.A.R.E. gap scenarios — a death on shift, police interference, scope."""

ADD = [
("care", {
 "section": "EMERGENCY",
 "hook": "SOMEBODY DIED ON YOUR SHIFT",
 "archetype": "The Critical Incident And The Weeks After It",
 "clinical": "Critical Incident Stress / Post-Fatality Response",
 "who": "Nobody did anything wrong. This page is for the hours and the months after the worst night, and it is written because almost nobody in this role is prepared for it and it happens every season somewhere.",
 "scene": "You did everything right. You did CPR, you called it in, the medics came, and it did not matter. It is four in the morning and the tent is still open and there are eleven people outside who need things, and somebody is asking you where the water is.",
 "tells": [
  "You kept working, because the tent was still open",
  "You are recounting the timeline compulsively, looking for the error",
  "Nobody senior has formally stood you down",
  "There is no organizational debrief scheduled, only a gap",
  "You have not told the people at home, to protect them",
  "You are fine, loudly, and have started sleeping badly",
 ],
 "happening": "A death on shift is a critical incident, and the response to it is well established even though this sector rarely provides it: stand down immediately rather than finishing the shift, a factual operational debrief within twenty-four hours that is separate from any emotional processing, and follow-up over weeks rather than a single conversation on the night. What does not help, and is the standard offering, is an unstructured group conversation at four in the morning with everyone still activated. What helps is sleep, food, being stood down, and a scheduled conversation later with somebody trained.",
 "check": "C.A.R.E. — “E” CHECK: “Am I still working?” If yes, that is the first thing to change. You are not a resource tonight.",
 "darkTitle": "The Review Will Find You Did Not Fail",
 "dark": "The thing that hurts people in this role is not the death, it is the replay — the compulsive re-examination of the timeline looking for the two minutes where it could have gone differently. Almost always there is no such moment, and being told that by somebody who knows the clinical picture is enormously more useful than being told it by a friend. Ask for the operational debrief and ask to be walked through what actually happened medically, because unanswered questions are what the replay feeds on. And put the follow-up in the diary for three and six weeks, when everyone has gone home and it gets much louder. Bereaved-by-suicide and critical-incident support services exist for responders and volunteers, not only for family.",
 "move": "Stand down now, not at the end of the shift — hand over and say you are unfit to continue, which is a clinical statement rather than a request. Eat, hydrate, sleep. Ask for a factual operational debrief within a day and book a proper one for three weeks out. Tell one person at home something true.",
 "say": "I'm standing down — I'm not fit to be on this tent tonight, someone needs to take over. — I want an operational debrief in the next day, and I want to be walked through what happened clinically.",
 "truth": "Finishing the shift is not resilience. Standing down is the first piece of clinical judgement you make about yourself.",
}),
("care", {
 "section": "CONTROL",
 "hook": "SECURITY WANTS TO COME IN",
 "archetype": "Police And Security At The Harm Reduction Tent",
 "clinical": "Service Integrity / Third-Party Interference",
 "who": "An officer, a security supervisor, or an event manager standing at the entrance of your tent asking a question you should not answer, usually politely, and usually believing they are entitled to.",
 "scene": "There is a young woman in the corner who came in twenty minutes ago in a bad state and is only just settling, and there is now a uniform at the door asking what she took and whether he can have a word. Everybody in the tent has gone quiet and is watching what you do, and what you do in the next ten seconds determines whether anybody uses this tent again this weekend.",
 "tells": [
  "Uniformed presence at or inside the service space",
  "Requests for names, substances, or details about a participant",
  "Being asked to identify who is holding, or to point somebody out",
  "Security using the tent as an observation post",
  "An event manager asking for information to manage reputation",
  "Participants stopping at the door, looking in, and walking away",
 ],
 "happening": "The entire clinical value of a harm reduction service rests on one thing: people believing they can come in without consequence. That belief is fragile, it is community knowledge rather than individual knowledge, and it is destroyed by a single visible interaction — one person seen speaking to police at the tent door ends the service's usefulness for the rest of the weekend, because the word travels faster than anything you can say to correct it. Protecting the boundary is not obstruction; it is the operational requirement that makes the service work at all.",
 "check": "C.A.R.E. — “A” CHECK: “What does this look like to the people watching from inside my tent?” That perception is the service, and it is what you are protecting.",
 "darkTitle": "Agree It In Writing Before The Gates Open",
 "dark": "The failure is almost always a planning failure rather than a confrontation. Services that get this right have a written agreement with the event and with police before the event opens — where the boundary is, what is and is not shared, and who to escalate to — and services that get it wrong are improvising it at two in the morning with an officer at the door and a frightened participant behind them. Get the memorandum in advance, get the senior officer's name, and brief every volunteer on the single sentence they use so that nobody has to invent one under pressure. Nobody should be working out an organization's information-sharing policy while somebody watches from a beanbag.",
 "move": "Step outside to speak rather than letting the conversation happen in the space. Give one clear sentence, escalate to your coordinator, and do not disclose participant information. Afterwards, tell the room plainly what did and did not happen.",
 "say": "I'll come out to you — let's talk out here. We don't share participant information; if you need something formally, my coordinator is the person for that and I'll get them now. — [to the room] Nobody's name was given and nobody's getting spoken to. You're fine here.",
 "truth": "A single conversation at your door can close the service for the whole weekend. Step outside and protect what the room believes.",
}),
("care", {
 "section": "TOOLS",
 "hook": "THAT IS MEDICAL, NOT US",
 "archetype": "The Line Between Harm Reduction And Medicine",
 "clinical": "Scope of Practice / Escalation Thresholds",
 "who": "For everyone on a harm reduction or welfare shift, holding a role with no clinical registration and a queue of people whose conditions you are not qualified to assess.",
 "scene": "He has been sitting with you for an hour and is not improving, and you are not sure whether this is a long comedown, dehydration, a reaction, or something genuinely medical. Walking him to the medics feels like escalating, and you have a specific fear of being the volunteer who overreacts and looks green in front of the medical team.",
 "tells": [
  "Not improving, or getting worse, over time you would expect improvement",
  "Temperature: very hot and not sweating, or cold and clammy",
  "Breathing that is slow, irregular, snoring or noisy",
  "Unrousable, or rousable only briefly, or seizing",
  "Chest pain, a head injury, or an unexplained one-sided weakness",
  "You are debating it with yourself, which is itself the threshold",
 ],
 "happening": "Harm reduction and welfare workers are the first point of contact for a great many situations and are not clinicians, and the most consequential skill in the role is a low, pre-decided threshold for escalation. Every serious festival incident review finds the same thing: the delay happened because somebody was not sure it was serious enough. The thresholds above are not judgement calls and should not be treated as any — temperature extremes, breathing changes, unrousability, seizures and head injuries go to medical immediately, every time, without a discussion about whether it warrants it.",
 "check": "C.A.R.E. — “R” CHECK: “Am I debating whether this is medical?” The debate is the answer. Escalate while you are still discussing it.",
 "darkTitle": "Nobody Was Ever Criticized For The Early Call",
 "dark": "Name the fear, because it is what causes the delay: you do not want to be the volunteer who walked someone over and was told it was nothing. Ask any festival medic and they will tell you the opposite — early calls are welcome, they would far rather see ten people who were fine than one an hour late, and the ones that go badly are always the late ones. The specific pattern to watch for is the person who is quietly deteriorating while the tent is busy, because a quiet person gets less attention than a loud one and deterioration is quiet by nature. Set a review time for everybody you are holding, and check them even when nothing has changed.",
 "move": "Pre-decide the thresholds and escalate on any of them without deliberating. Set an explicit review time for every person you are holding. Walk them to medical rather than sending them. Hand over factually: what they took if known, when, what you have observed, what has changed.",
 "say": "I'm walking you over to the medics — not because it's dramatic, just because it's their call and not mine. — [handing over] Male, about twenty-five, in with us ninety minutes, reports MDMA around ten, temperature's up and he's not sweating, and he's less responsive than he was.",
 "truth": "If you are debating whether it is medical, it is medical. No medic has ever complained about being called early.",
}),
]
