# -*- coding: utf-8 -*-
"""L.E.A.D. gap scenarios — removing someone, handling a report between members, camp money."""

ADD = [
("lead", {
 "section": "TOOLS",
 "hook": "HOW YOU ACTUALLY REMOVE SOMEONE",
 "archetype": "The Conversation Camp Leads Avoid For Years",
 "clinical": "Exclusion Process / Safe Removal Practice",
 "who": "You, holding a decision you have already made and have been postponing for eleven months because you do not know how to do the next part without it becoming a scene.",
 "scene": "You know he cannot come back. You have known since August. What you do not have is a way of saying it that does not turn into a two-hour argument in front of the camp, or a group chat meltdown, or him turning up anyway because nothing was ever said clearly enough to be enforceable.",
 "tells": [
  "The decision is made and only the delivery is missing",
  "You are waiting for one more incident to make it defensible",
  "The camp is quietly organizing itself around avoiding him",
  "People have started not coming, and you know which people",
  "There is no written camp agreement to point at",
  "You are planning to do it in person, alone, at the event",
 ],
 "happening": "Most camp exclusions go badly for procedural reasons rather than emotional ones: delivered verbally, at the event, by one person, with no written basis and no defined scope, which makes them arguable, unenforceable and humiliating for everyone present. Every organization that does this well does the same four things — decide off-site, deliver in writing, be specific and short about what and for how long, and do not debate. The last one is the hardest and the most important: the decision is not being negotiated, it is being communicated.",
 "check": "L.E.A.D. — “A” CHECK: “Is this decided, and is it written down?” If it is not written, it is a disagreement rather than a decision, and it will be treated as one.",
 "darkTitle": "Do It Before The Event, Not At It",
 "dark": "Doing it on site is the mistake that produces every bad outcome. He arrives having paid, packed and travelled, in front of an audience, with nowhere to go and nothing to lose — and that is the version that becomes a confrontation, or a scene the whole camp remembers, or a safety issue at two in the morning. Send it weeks out, in writing, and tell the event's safeguarding lead that you have done it so somebody official knows before he turns up. Also protect the person who raised it: never name them, and never let the reasoning be specific enough to identify them, because the single biggest deterrent to anyone else ever reporting anything is watching what happened to the last person who did.",
 "move": "Decide with two other people, not alone. Send it in writing weeks before the event, short, specific, with a clear scope and no invitation to discuss. Tell the event's safeguarding lead. Brief the camp on what is happening without the detail and without names.",
 "say": "You're not camping with us this year. This is a decision, not a discussion, and I'm not going to debate it over messages. If you turn up, we'll be asking the event to handle it.",
 "truth": "Waiting for one more incident means one more person gets hurt. Decide off-site, write it down, and do not debate it.",
}),
("lead", {
 "section": "TOOLS",
 "hook": "TWO OF MY PEOPLE, ONE STORY EACH",
 "archetype": "A Report About Somebody Inside Your Own Camp",
 "clinical": "Internal Report Handling / Conflict of Interest",
 "who": "You, holding a disclosure from one camp member about another, both of whom you like, in a structure with no process, no training and no separation of roles whatsoever.",
 "scene": "She told you what happened on Friday. He has been your friend for nine years. You are now the investigator, the judge, the friend of both parties and the person who has to keep this camp functioning for another two days, and you have no idea what you are doing.",
 "tells": [
  "You are close to both parties and there is no independent person",
  "Your first instinct is to get them in a room together",
  "You are trying to establish what really happened",
  "The camp has begun taking sides before anything is decided",
  "No notes have been taken and it is already three days ago",
  "The reporting person has asked you not to do anything",
 ],
 "happening": "Camp leads are handed reports with none of the structure that makes handling them possible, and the two most common instincts are both wrong. Mediation — getting both parties in a room — is actively harmful where there is any power imbalance or alleged harm, because it requires the person who was harmed to negotiate with the person who harmed them. And investigating, in the sense of establishing the truth, is not your role and you are not equipped for it; your role is immediate safety, accurate notes, and routing it to someone independent.",
 "check": "L.E.A.D. — “L” CHECK: “Am I trying to find out what really happened?” That is not the job. Safety, notes, and handing it on is the job.",
 "darkTitle": "What The Reporting Person Controls And What They Do Not",
 "dark": "Two things have to be held together and it is uncomfortable. The reporting person controls their own disclosure — who they tell, whether they make a formal report, whether they involve police — and you do not override that. But you do control your camp, and if there is an ongoing safety risk you can act on that without their consent, as long as you do it in a way that does not identify them. Separating sleeping arrangements, changing a rota, or removing somebody can all be done as a camp decision rather than as a response to a specific report. And write the notes tonight, factual and dated, because in four months this will come back and memory is not evidence.",
 "move": "Ask what she wants and what she needs to be safe tonight, and do the safety part immediately. Take dated factual notes the same day. Separate them physically without announcing why. Route it to the event's safeguarding lead. Do not mediate, do not investigate, and do not tell the camp.",
 "say": "Thank you for telling me. Two things: what do you need tonight to feel safe, and what do you want to happen next — that part's yours to decide. I'm going to move some sleeping arrangements either way, and I won't say why to anyone.",
 "truth": "You are not an investigator and you are certainly not a mediator. You are safety tonight, notes today, and a handover tomorrow.",
}),
("lead", {
 "section": "CONTROL",
 "hook": "WHO'S HOLDING THE CAMP MONEY",
 "archetype": "Dues, Floats And The Quiet Financial Hold",
 "clinical": "Financial Control / Unaccounted Collective Funds",
 "who": "Whoever collects for the generator, the truck, the food, the sound system and the pitch — often the founder, often for years, often with no accounting anybody has ever seen.",
 "scene": "Everyone pays in two hundred at the start of the season and nobody has ever seen a spreadsheet. It is almost certainly fine. It is also the reason that when somebody wants to leave the camp, or disagrees with him about something, there is an unspoken question about what happens to what they have put in, and nobody asks it out loud.",
 "tells": [
  "One person collects and spends with no reporting",
  "No receipts, no ledger, no statement at the end of the season",
  "Members do not know what they have collectively paid for",
  "Assets — the shade structure, the sound system, the truck — are in one name",
  "Leaving the camp means losing money nobody can quantify",
  "Asking about it would be treated as an accusation",
 ],
 "happening": "Camp money is usually handled by a trusted person acting in good faith, and the problem is structural rather than moral: unaccounted collective funds create an exit cost that nobody can name, and an exit cost is leverage whether or not anybody intends to use it. It compounds with the housing-as-leverage dynamic elsewhere in this guide — if the same person controls where you sleep, what you have paid in, and the assets you helped buy, then disagreeing with them has a price that is real and unquantifiable, which is the worst combination.",
 "check": "L.E.A.D. — “E” CHECK: “Could any member see where the money went, without asking a favour?” If not, trust is doing a job that a spreadsheet should be doing.",
 "darkTitle": "Transparency Protects The Person Holding It",
 "dark": "If you are the one holding the money, the accounting is for you before it is for anybody else. The moment a camp has a falling-out — and camps do — an unaccounted fund becomes the thing people reach for, and years of genuine generosity get reinterpreted in a group chat by people doing arithmetic from memory. A shared sheet, receipts photographed into a folder, and a five-minute end-of-season summary makes that impossible. And put the significant assets somewhere collective, because a shade structure everybody paid for that lives in one person's garage is an ownership question waiting for a bad year.",
 "move": "Run a shared spreadsheet anybody can open, photograph receipts into a shared folder, and post a short end-of-season summary without being asked. Name a second signatory. Write down who owns the major assets and what happens to them if the camp splits.",
 "say": "Putting the camp finances on a shared sheet this year — not because anything's wrong, just so it's never a question. Anyone want to be second pair of eyes on it?",
 "truth": "Unaccounted money is an exit cost nobody can name, and it is leverage even when nobody means it to be.",
}),
]
