# -*- coding: utf-8 -*-
"""E.V.E.N.T. gap scenarios — the report about a headliner, crowd safety, security contractors."""

ADD = [
("event", {
 "section": "ACCOUNTABILITY",
 "hook": "THE REPORT IS ABOUT YOUR HEADLINER",
 "archetype": "When Acting Costs You The Event",
 "clinical": "Conflict of Interest / High-Value Perpetrator",
 "who": "You, holding a credible report about the one person on the bill you cannot replace, forty-eight hours out, with six thousand tickets sold on their name.",
 "scene": "It came through welfare last night and it is specific, it is not the first thing you have half-heard about him, and he is on at ten tomorrow. The maths is doing itself in your head before you have finished reading: refunds, the agent, the insurance, next year's booking relationships, and a field full of people who bought tickets for him.",
 "tells": [
  "The commercial cost of acting is immediately obvious and the cost of not acting is not",
  "You are looking for reasons the report might be unreliable",
  "You are thinking about handling it quietly, after the event",
  "The agent's likely reaction is in your reasoning",
  "You have heard something before and it did not go anywhere",
  "Nobody outside your commercial interest is involved in the decision",
 ],
 "happening": "This is the decision that defines an event, and the pattern of failure across the industry is consistent: not a promoter who decided to protect a predator, but a promoter who decided to handle it after the weekend, and then after the season, and then not at all. Everything about the moment pushes one way — the cost of acting is concrete and immediate, the cost of not acting is diffuse and deferred — and that asymmetry is the whole trap. The counter is structural: a decision rule written when nothing is at stake, and a person outside the commercial line who makes the call.",
 "check": "E.V.E.N.T. — “E” CHECK: “Would I act on this identical report if it were about a volunteer?” If yes, then the only variable is money, and you already know that is not a reason.",
 "darkTitle": "Everything Comes Out Eventually, With Your Name On It",
 "dark": "Every event that has been publicly destroyed by this was destroyed by the cover-up rather than by the incident. It surfaces two or three years later, with the timeline, and the sentence that ends the organization is always that they knew and booked him anyway — because that is provable from a welfare log and an email. The decision looks commercial in the moment and reputational in retrospect, and the reputational version is always the larger number. Act on it now, document the decision and the reasoning, and accept the refunds, because the refunds are the cheap option and you will not believe that until it is too late to choose them.",
 "move": "Take the decision out of the commercial line — your safeguarding lead decides, not you. Act on the current event: remove, or supervise and separate with named conditions. Document the report, the decision and the reasoning the same day. Tell the agent factually and in writing. Write the rule into next year's contracts before you need it again.",
 "say": "This goes to our safeguarding lead and their decision stands, including if it costs us the headline slot. — [to the agent] We've received a report we're acting on. He's not performing. I'm putting the decision and the reasons in writing to you today.",
 "truth": "The refund is the cheap option and it will never feel like it. What ends events is not the incident, it is the email showing you knew.",
}),
("event", {
 "section": "RESPONSIBILITY",
 "hook": "THE FRONT OF THE CROWD",
 "archetype": "Density, Surges And The Thing That Kills People At Festivals",
 "clinical": "Crowd Dynamics / Progressive Crowd Collapse",
 "who": "Physics. Not a bad actor, not a decision anybody made — a density figure, a pinch point, and a moment when a crowd stops being people and becomes a fluid.",
 "scene": "It is the headline act, the barrier is full, there is a surge from the back, and somewhere in the middle of it a person goes down and the people around them cannot bend to help because there is no room to bend. Nothing about this looks dangerous from the mixing desk and it is the single most lethal thing that happens at music events.",
 "tells": [
  "Density above roughly four to five people per square metre",
  "Pinch points, narrowing barriers, or one exit route into a viewing area",
  "Crowd movement that propagates as waves rather than as individuals",
  "No spotters at the barrier and no view from the front looking back",
  "No agreed show-stop authority, or one nobody will use",
  "Late-arriving surges toward a single popular act",
 ],
 "happening": "Deaths in crowds are almost never trampling, which is the popular misconception — they are compressive asphyxia, where density becomes high enough that people cannot expand their chests, and it is survivable for only a few minutes. It is entirely a design and management problem: density limits, monitoring from a position that can see the front, spotters at the barrier, and crucially a named person with unambiguous authority to stop the show. The single factor that turns a dangerous crowd into a fatal one is hesitation about stopping.",
 "check": "E.V.E.N.T. — “E” CHECK: “Who can stop the show, right now, without asking anybody?” If that person is not named and briefed, you do not have a crowd safety plan.",
 "darkTitle": "Somebody Must Be Able To Stop It Without Permission",
 "dark": "Every crowd disaster review finds the same failure: people could see it and nobody stopped it, because stopping meant overriding a headline performance and nobody was sure they were allowed. Name the person, tell them in writing that they have the authority, tell the artist and their management in advance that a show-stop may happen and that they are to stop when asked, and rehearse the call. Give your spotters the same authority to escalate. It costs a few minutes of a set and the alternative is the thing that ends people's lives and organizations. Nobody has ever regretted a show-stop.",
 "move": "Set and monitor density limits with a competent crowd safety adviser. Put spotters at the barrier facing the crowd. Name the show-stop authority in writing and brief artists that it exists. Design out pinch points and single-route viewing areas. Rehearse the stop.",
 "say": "Show-stop authority tonight is Kerry, and it is not subject to anyone's approval including mine. If she calls it, the band stops mid-song. — [to management] Please brief the artist that a show-stop is possible and what it sounds like.",
 "truth": "People do not get trampled, they get compressed, and it takes minutes. Name the person who can stop it without asking.",
}),
("event", {
 "section": "RESPONSIBILITY",
 "hook": "YOU HIRED THEM, YOU OWN THEM",
 "archetype": "The Security Contractor Is Your Responsibility",
 "clinical": "Vicarious Accountability / Contractor Oversight",
 "who": "A security company that you engaged, whose staff you did not select, did not brief on your values, and whose conduct the public will attribute entirely to your event.",
 "scene": "Two complaints come through about the same door team — a search that was handled badly, and someone spoken to in a way that was not acceptable. They are not your employees. They are wearing lanyards with your logo on them, and to everybody who was there they are your festival.",
 "tells": [
  "No briefing given beyond capacity and ejection procedures",
  "No shared standard on searches, gender, or trans attendees",
  "Complaints about security route to the security company, not to you",
  "No mechanism for an attendee to report a guard",
  "The same complaints recur each year with no record kept",
  "You have never checked licensing, or spoken to the guards yourself",
 ],
 "happening": "Security are the most physically interventionist people on site and usually the least integrated into the event's stated values, because they arrive as a contracted service rather than as part of the team. Attendees do not distinguish: a bad search or an aggressive ejection is remembered as something your festival did. The fix is contractual and procedural — brief them as staff, set the standards in the contract, and provide a complaints route that does not run through the company being complained about.",
 "check": "E.V.E.N.T. — “N” CHECK: “Can an attendee complain about a guard to someone who does not work for the security company?” If not, you will never hear about it and it will continue.",
 "darkTitle": "Searches Are Where This Actually Goes Wrong",
 "dark": "The specific, recurring failure is the search, because it is the one moment where a stranger in a uniform makes physical contact with every single person who enters. Get it in writing in the contract: same-gender searching offered as standard, a stated option for trans and non-binary attendees including a private space and an officer of their choosing, no searching of minors without a guardian present, and a stated protocol for assistance dogs, mobility equipment and medication. None of that is exotic and almost no event specifies it, which is why it is improvised at the gate by whoever is on that morning — and improvisation at a gate is how a person's weekend starts badly and how your festival acquires a reputation.",
 "move": "Brief security as staff, in person, on your values and your consent policy. Put the search standards, licensing requirements and conduct expectations in the contract. Publish a complaints route that bypasses the contractor. Log every complaint and review it before renewing.",
 "say": "You're briefed with our team, not separately — our consent policy applies to your staff. Same-gender searches offered as standard, private option available, and complaints come to our welfare lead, not to your supervisor.",
 "truth": "They wear your logo and the public cannot tell the difference. Brief them like staff, or accept what they do in your name.",
}),
]
