# -*- coding: utf-8 -*-
"""S.A.F.E. gap scenarios — crowd crush, weather and evacuation, the drive home."""

ADD = [
("safe", {
 "section": "EMERGENCY",
 "hook": "IF THE CROWD GETS TOO TIGHT",
 "archetype": "Crowd Crush / What To Actually Do Inside One",
 "clinical": "Compressive Asphyxia / Crowd Density Emergency",
 "who": "Nobody. This is physics, and it is the most lethal thing that happens at music events, and almost nobody in a crowd knows the three things that keep them alive in one.",
 "scene": "You are forty rows back and the crowd has stopped feeling like people. You are being moved without walking. Your arms are pinned. There is a wave that goes through from behind and you feel your feet leave the ground briefly, and you cannot get your chest to expand fully on the in-breath.",
 "tells": [
  "You are being carried by the crowd rather than choosing your steps",
  "You cannot raise your arms or take a full breath",
  "Waves of pressure travelling through the crowd rather than individual movement",
  "You are shoulder-to-shoulder on all four sides with no gaps at all",
  "People near you have gone quiet",
  "You cannot see a gap, a barrier gate, or an edge",
 ],
 "happening": "Crowd deaths are compressive asphyxia, not trampling: the pressure of bodies prevents the chest from expanding and a person suffocates upright, frequently while nobody around them realizes what is happening. It becomes dangerous above roughly five people per square metre and the window is short. The three things that matter are simple and completely counterintuitive, which is why they have to be known in advance rather than worked out at the time.",
 "check": "S.A.F.E. — “S” CHECK: “Can I raise my arms and take a full breath?” The moment the answer is no, you are in a crush and you start moving out now, not later.",
 "darkTitle": "The Three Things That Keep You Breathing",
 "dark": "Memorize these now. One: get your arms up in a boxer's guard, hands in front of your chest, elbows out — this creates the few centimetres of space in front of your ribs that lets you keep breathing, and it is the single highest-value action. Two: do not push, do not fight the wave, and above all do not bend down for anything, including a phone or a person — going down in a dense crowd is how people do not come back up, and you cannot help anyone from the floor. Three: move diagonally and with the surges, not against them, using the moments of give to gain half a metre toward an edge; going against a crowd achieves nothing and exhausts you. And if somebody goes down near you, shout, and make a wall with the people around you rather than bending into the gap alone.",
 "move": "Arms up in a guard, protect your chest. Stay upright at all costs. Move diagonally toward an edge during the moments of slack. Shout if somebody goes down and form a wall with the people beside you. If you can, leave before it gets to this — density builds visibly for minutes beforehand.",
 "say": "Arms up! — Somebody's down, make a wall! Don't bend, hold the space! — Back this way, move with it, not against it.",
 "truth": "People suffocate standing up, and it takes minutes. Arms up, stay upright, move diagonally with the wave.",
}),
("safe", {
 "section": "EMERGENCY",
 "hook": "WHEN THE SKY TURNS",
 "archetype": "Storms, Heat And Evacuation In A Field",
 "clinical": "Severe Weather Response / Mass Evacuation",
 "who": "The weather, at a site made of temporary metal structures, canvas, and eighty thousand people with nowhere indoors to go.",
 "scene": "The stage goes dark mid-set and a voice says something you cannot make out over the PA, and the crowd starts to move in a direction, and it is beginning to rain properly. Nobody around you knows whether this is a five-minute pause, a storm hold, or a full evacuation, and the field is already becoming a single large moving mass.",
 "tells": [
  "Stages held or dark with no clear announcement reaching you",
  "Lightning visible, or thunder inside thirty seconds of a flash",
  "Standing water, mud, or wind moving temporary structures",
  "Crowds converging on one route out of an arena",
  "Extreme heat with no shade and long queues for water",
  "You do not know where your site's shelter or muster points are",
 ],
 "happening": "Weather is the likeliest cause of a mass evacuation at an outdoor event and every festival has a plan for it that attendees have almost never read. The two lethal versions are lightning — a field of temporary metal structures with no substantial buildings is close to the worst possible place — and the crowd movement that an evacuation itself produces, which is where the injuries actually happen. Heat is the slower one and it kills more people than storms do, usually through people who have been dancing in sun for hours without shade or salt.",
 "check": "S.A.F.E. — “F” CHECK: “Do I know where my shelter is and where my camp's muster point is?” Find both on Thursday, because there is no time to find them on Saturday.",
 "darkTitle": "Vehicles, Not Tents, And Move Early",
 "dark": "Two specifics worth having in advance. In lightning, a tent is worse than useless — it offers no protection at all and its poles are the tallest thing in a flat field. A hard-topped vehicle is genuine shelter and so is a substantial permanent building; a gazebo, a marquee and a stage structure are not. Get away from metal, from the highest ground and from lone trees, and use the thirty-second rule: if thunder follows the flash within thirty seconds, the storm is close enough to be dangerous. And in any evacuation, move early and sideways — the injuries happen in the converging crush at the main exit, so the moment you think it might be an evacuation, start walking toward a secondary route before the announcement is confirmed.",
 "move": "Find shelter options and your camp's muster point on arrival. Move at the first indication rather than at confirmation, and use secondary exits. In a storm, get to a hard-topped vehicle or a permanent building, not a tent. In heat, shade and electrolytes on a schedule rather than when thirsty.",
 "say": "That's lightning close — we're going to the car, not the tent. Now, before everyone else does. — Muster point's the water tower if we get split up.",
 "truth": "A tent is not shelter from lightning, it is a pole in a field. Move early and sideways, because the crush is at the main exit.",
}),
("safe", {
 "section": "COMMUNITY CARE",
 "hook": "GETTING HOME IS PART OF THE FESTIVAL",
 "archetype": "The Monday Drive / The Most Dangerous Part Of The Weekend",
 "clinical": "Fatigue-Impaired Driving / Residual Impairment",
 "who": "Everybody, on the Monday, in a car park of eleven thousand vehicles all being driven by people who have had four hours' sleep a night since Thursday.",
 "scene": "It is packed up, it is ten in the morning, and everyone is driving home. You feel alright. You had a big weekend, you slept badly in a tent for four nights, you may still have something in your system, and you are about to do three hours on a motorway with three exhausted friends asleep in the car.",
 "tells": [
  "Under five hours of sleep per night across the whole weekend",
  "Substances used within the last twenty-four hours — comedowns impair driving",
  "Still over the limit from the night before, which is very common",
  "Everybody in the car is asleep, so nobody is watching the driver",
  "A long motorway stretch in the early afternoon dip",
  "“I'll stop if I feel tired”, which is not how microsleeps work",
 ],
 "happening": "The drive home is statistically the most dangerous part of a festival weekend and it gets no attention at all because the festival feels over. Three impairments stack: cumulative sleep debt from four nights in a tent, residual substances or a comedown, and in a large number of cases still being over the drink-drive limit the following morning. Fatigue impairment is comparable to alcohol impairment, and the microsleep is the specific killer — a few seconds of sleep that the driver does not know occurred.",
 "check": "S.A.F.E. — “E” CHECK: “How much have I actually slept since Thursday, and what is still in me?” Answer honestly, out loud, to somebody else in the car.",
 "darkTitle": "Sleep First, Then Drive",
 "dark": "The safest thing available is completely free and almost nobody does it: sleep on site on the Monday morning and leave in the afternoon, or in the evening, or on Tuesday. Most events will let you, the car park empties, and you arrive alive. If you must go, make it a rule that the driver has slept and is the one nobody lets stay up on the Sunday — appoint them on Thursday, like a designated driver, and protect their sleep as a group. Swap every two hours, keep one passenger awake with the driver at all times, and stop the moment anybody misses an exit or cannot remember the last few miles, because that is what a microsleep feels like from the inside: nothing at all.",
 "move": "Appoint the Monday driver on Thursday and protect their sleep all weekend. Sleep before you drive, even if it costs you half a day. Swap drivers every two hours, keep one passenger awake, and stop at the first missed exit or lost mile.",
 "say": "You're driving Monday, so you're getting a proper night on Sunday — we'll leave you to it. — I've slept about four hours a night since Thursday, I'm not driving till this afternoon.",
 "truth": "You survived the festival. The car park on Monday is the part that has not finished with you yet.",
}),
]
