# -*- coding: utf-8 -*-
"""H.O.M.E. gap scenarios — unreachable, the partner version, the substance worry."""

ADD = [
("home", {
 "section": "EMERGENCY",
 "hook": "I CAN'T REACH THEM",
 "archetype": "Twenty-Six Hours Of Silence / What To Do And When",
 "clinical": "Contact Loss / Escalation Thresholds for Families",
 "who": "You, at home, watching an unanswered message go from normal to not normal, with no idea where the line is.",
 "scene": "They have not replied since Friday afternoon. It is now Saturday evening. You know the phone probably died, because everyone's phone dies, and you also cannot stop refreshing, and you have no idea whether calling the festival makes you a reasonable parent or a ridiculous one.",
 "tells": [
  "Silence longer than they said it would be",
  "Their last message was odd, short, or unlike them",
  "You do not know who they are with or where they are camped",
  "You have been calling repeatedly, which achieves nothing and floods the line",
  "You are about to post publicly, which you should not do yet",
  "You do not know the festival has a welfare team that does exactly this",
 ],
 "happening": "Silence at a festival is overwhelmingly a dead battery and no signal — mobile networks at large events are saturated, charging queues are hours long, and messages sent from a field frequently never arrive. That is the likeliest explanation and it is worth holding onto. It is also true that every large festival has a welfare team whose job includes locating people and passing on messages, they are contactable, and they will not think you are overreacting. Most families do not know that team exists, so they oscillate between doing nothing and calling the police.",
 "check": "H.O.M.E. — “E” CHECK: “Have I contacted the festival's welfare team?” That is the step between waiting and panicking, and almost nobody knows it exists.",
 "darkTitle": "The Ladder, So You Are Not Choosing Between Nothing And Everything",
 "dark": "Work it in order rather than jumping. One: message the friends they went with, which is why you asked for names before they left — this resolves it most of the time within an hour. Two: call the festival's information or welfare line, give the name, camp area and a description, and ask them to pass a message; they do this many times a day. Three: if there is a genuine reason for concern — a worrying last message, a known health condition, a specific threat — say so to welfare, because that changes what they do. Four: police, and there is no waiting period for a missing person, that is a myth. What not to do is call them forty times, because it drains the battery you are hoping stays alive, and do not post publicly early, because it is very hard to undo and they are almost certainly asleep in a tent.",
 "move": "Message their friends first. Then ring the event's welfare or information line and ask them to pass a message. Send one text, not thirty, saying you are fine and just want a thumbs-up when they see it. Escalate to police if there is a specific reason, without waiting.",
 "say": "Hi — my daughter's at your event, camped in the yellow field, I've not heard from her since Friday and her phone's likely dead. Could someone pass her a message to text home? — [text] No panic at all, just send me a thumbs-up when you see this. Have a brilliant time.",
 "truth": "It is almost always a dead battery. Ring welfare, send one message, and do not call forty times — you are draining the phone you are waiting on.",
}),
("home", {
 "section": "CONDITION",
 "hook": "WHEN IT'S YOUR PARTNER, NOT YOUR KID",
 "archetype": "Worry, Jealousy, And The Line Between Them",
 "clinical": "Relational Anxiety / Coercive Control Risk in Monitoring",
 "who": "You, at home, while somebody you love is somewhere that is uninhibited, physically affectionate, full of strangers, and entirely outside your view for four days.",
 "scene": "You said have a great time and you meant it. It is Saturday night and you have checked their location three times, and you have looked at who is posting from that field, and you have drafted a message that is technically about whether they are okay and is actually about something else, and you are aware that you are doing it.",
 "tells": [
  "Checking location sharing repeatedly rather than once",
  "Messages framed as concern that are asking a different question",
  "Wanting proof of who they are with or what they are doing",
  "Setting expectations for contact frequency that are about reassurance",
  "Feeling relief when they answer and worse forty minutes later",
  "You would not be comfortable if they described your behaviour to a friend",
 ],
 "happening": "Distance plus a scene with a reputation plus no information is an excellent generator of anxiety, and anxiety is not the same thing as a problem in the relationship — but the behaviours it produces are the same behaviours that constitute monitoring, and that is worth being honest about while it is still small. Frequent location checking, demands for contact, and requests for proof are on a continuum whose far end is coercive control, and nobody arrives at the far end on purpose. They get there in small, reasonable-feeling steps, each one justified by worry.",
 "check": "H.O.M.E. — “O” CHECK: “Am I asking for information, or for reassurance?” Both are human. Only one of them is fair to send.",
 "darkTitle": "Say The Real Thing, Or Say Nothing",
 "dark": "The honest version is better than the disguised one in every case. “I'm feeling insecure and I don't need you to fix it, I just wanted to say it” is a sentence that costs you something and does no damage. “Are you okay? Who's there? Why haven't you replied?” is a sentence that looks like care and functions as surveillance, and they will feel the difference even if they cannot name it — and what it produces is a partner who starts managing your anxiety from a field, which is the beginning of them telling you less rather than more. If the checking is compulsive, the work is yours and it is not about this weekend. Deal with it at home, not through their phone.",
 "move": "Agree the contact plan before they go — one message a day, no expectation of a reply within any window — so neither of you is improvising. Then put the phone down and do something. If you are checking location repeatedly, turn the sharing off for the weekend; it is feeding the thing it is supposed to settle.",
 "say": "One message a day, whenever suits you, and no pressure to reply — I'll assume you're having a brilliant time. — I'm feeling a bit insecure this weekend. That's mine, not yours. Just wanted to say it rather than send you weird texts.",
 "truth": "Anxiety and monitoring feel identical from the inside and completely different from the other end. Say the real sentence instead.",
}),
("home", {
 "section": "TOOLS",
 "hook": "I THINK THEY'RE TAKING SOMETHING",
 "archetype": "The Substance Conversation That Does Not Close The Door",
 "clinical": "Harm Reduction Communication / Disclosure Preservation",
 "who": "You, holding a worry you have not said out loud, about to have the conversation that will determine whether you hear anything true from them for the next ten years.",
 "scene": "You are fairly sure. You have one conversation available before they go and two options for how to use it, and one of them ends with them telling you less forever. Everything in you wants to say do not take anything, and that sentence has a known effect, and the effect is not the one you want.",
 "tells": [
  "You are planning to lead with a prohibition",
  "You have facts from headlines rather than from harm reduction sources",
  "You want a promise, and a promise will be given to end the conversation",
  "You have not said the unconditional sentence yet",
  "You do not know what testing kits are, or that they exist",
  "You would rather not know, and they can tell",
 ],
 "happening": "Abstinence-only messaging performs poorly at changing behaviour and performs actively badly at maintaining disclosure — a young person who believes you cannot hear it will simply stop telling you things, and you lose the visibility that was your only real protection. The evidence favours the opposite approach: accurate information, no lecture, and an explicit guarantee that calling you costs them nothing. This is the same conversation as the one earlier in this guide, applied to the specific thing you are most afraid of.",
 "check": "H.O.M.E. — “M” CHECK: “Am I trying to get a promise, or trying to stay somebody they can tell the truth to?” You can have one of those.",
 "darkTitle": "The Three Facts That Actually Save Lives",
 "dark": "If you say nothing else, say these. One: never take something from someone you do not know, and never take something that has not been tested — testing kits are legal and available in most places, and the Bunk Police and DanceSafe exist for exactly this. Two: never mix, especially not with alcohol, and especially not when somebody says it is fine. Three, and this is the one that saves lives: if somebody is in trouble, call for help immediately and tell the medics exactly what was taken, because Good Samaritan protections exist in most places and nobody at a festival medical tent is interested in getting anybody arrested — the deaths happen when people wait because they are frightened of getting in trouble. A young person who knows those three things and knows they can ring you is in a dramatically better position than one who promised you they would not.",
 "move": "Lead with the guarantee, not the prohibition. Give the three facts plainly and without moralizing. Say that you would rather know and be able to help than be protected from the truth. Then stop talking and let them decide what to tell you.",
 "say": "I'd rather you didn't, and I'm not going to pretend that's the end of it. So: don't take anything you haven't tested or that came from someone you don't know, never mix it with drink, and if anyone's in trouble get the medics straight away and tell them exactly what was taken — nobody gets in trouble for that, and waiting is what kills people. And whatever happens, ring me. I won't be angry.",
 "truth": "You can have a promise or you can have the truth for the next ten years. The promise is worth nothing and it costs you the other one.",
}),
]
